### ISSUE TITLE
LiveTV?

### ISSUE THREAD

**Issue by djmuk** [MythTV-Clients/MythTV-Android-Frontend#100]
Is having the facility to watch LiveTV on the roadmap?

There is another 'Mythfrontend' client in the play store which does provide this facility but the developer says he has stopped development because the 'official' android port is available...

https://play.google.com/store/apps/details?id=se.tinelin.android&feature=also_installed#?t=W251bGwsMSwxLDEwNCwic2UudGluZWxpbi5hbmRyb2lkIl0.

developer 'vinoli'

Thanks

David

**Comment by dmfrey** [comment]
David,

At this time, the Mythtv Services API and HTTP Live Streaming do not support Live TV.  Once the backend supports it, we will as well.
