### ISSUE TITLE
If the MythTV backend isn't running, the applications prints the "Unfortunately..." message

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#101]
Running on: mythtv-android-frontend-1.0.4-20-gfd40b08

To duplicate:

<pre>
Shutdown the backend
Start MAF
Select Home
Select Recordings
</pre>

A toast message will warn that the backend isn't connected.

The "Unfortunately, MythTV Android Frontend has stopped" message
will pop up. After pressing OK, the user will be returned to the Home/Away
page.

The fatal exception fires on line 1122 of: http://paste.ubuntu.com/1496660/

 This doesn't happen when either Upcoming or Recording Rules is selected.

Similar to #78.

**Comment by dmfrey** [comment]
i think i know what is going on here...the process to query for images is firing even though the backend connection has not been established.

**Comment by dmfrey** [comment]
should have been fixed with #90 

please re-test and close if no longer occurring

**Comment by billmeek** [comment]
Retested on: mythtv-android-frontend-1.0.4-42-gd6bb6d9.

Fails. Fresh LogCat: http://paste.ubuntu.com/1577526/ see line: 129
later on line 202 the connection fails.

Note:

I tried pressing the Recordings button again after the failure above. The
fatal exception may or may not fire. The user is returned to the Home
screen. In no case did the toast message warn the user that the backend
isn't connected. To me, this appears like a new issue, so let me know if
you'd prefer to treat it that way.

**Comment by billmeek** [comment]
I'm closing this, as I can't duplicate it after doing a complete
remove of the app/data and a reboot.

**Comment by dmfrey** [comment]
When the last error occurred before closing the ticket, were you doing a hls trans code on the back end? The error seemed to indicate it was checking the status of the hls transcode.

**Comment by billmeek** [comment]
Not that I remember.

I just looked in both backends (the 192.168.1.204 means mc0) and there are no
entries in /var/log/mythtv/mythtranscode\* for today.
