### ISSUE TITLE
Writing exception to parcel

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#103]
Running on: mythtv-android-frontend-1.0.4-26-gf2cd2a0

I haven't noticed this exception before. It appears to be new
with the 'pre-transcoding' changes. This is a LogCat error
only, not visable to the user (as far as I can tell.)

To duplicate:

```
Start MAF
Select Home
Exception fires
```

Please see line 239 here: http://paste.ubuntu.com/1507278/

**Comment by billmeek** [comment]
Update.

I've "solved" this by removing the app and all data. Leaving this open in case it comes
back.

This error fires whenever leaving the Recordings, Upcoming, Guide or Recording Rules
screens.

Planting Log.d statements in: src/org/mythtv/provider/MythtvProvider.java in the CHANNELS
case in bulkInsert( Uri uri, ContentValues[] values ) showed that the error fires when the
insert.execute() is done. See the git diff below.

<pre>
--- a/src/org/mythtv/provider/MythtvProvider.java
+++ b/src/org/mythtv/provider/MythtvProvider.java
@@ -1383,7 +1383,6 @@ public class MythtvProvider extends AbstractMythtvContentProvider {
                try {
                    //standard SQL insert statement, that can be reused
                    SQLiteStatement insert = db.compileStatement( ChannelConstants.INSERT_ROW );
-               
                    for( ContentValues value : values ) {
                        insert.bindString( 1, value.getAsString( ChannelConstants.FIELD_CHAN_ID ) );
                        insert.bindString( 2, value.getAsString( ChannelConstants.FIELD_CHAN_NUM ) );
@@ -1412,10 +1411,11 @@ public class MythtvProvider extends AbstractMythtvContentProvider {
                        insert.bindString( 25, value.getAsString( ChannelConstants.FIELD_XMLTV_ID ) );
                        insert.bindString( 26, value.getAsString( ChannelConstants.FIELD_DEFAULT_AUTH ) );
                        insert.bindString( 27, value.getAsString( ChannelConstants.FIELD_HOSTNAME ) );
+                       Log.d( TAG, "inside for, visible = " + value.getAsInteger(ChannelConstants.FIELD_VISIBLE));
                        insert.execute();
+                       Log.d( TAG, "inside for, hostname = " + value.getAsString(ChannelConstants.FIELD_HOSTNAME));
                    }
                    db.setTransactionSuccessful();
                        
                    numInserted = values.length;
                } finally {
                    db.endTransaction()
</pre>

**Comment by dmfrey** [comment]
Fixed with commit d78af4b
