### ISSUE TITLE
Episodes that start recording after the scheduled starttime can't be deleted.

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#106]
Running on: mythtv-android-frontend-1.0.4-29-gd72e7a5

To duplicate:

```
From a frontend's EPG, press r to record a show that is already in progress
Wait until the recording is complete
From the Recordings screen on MAF, try to delete the episode
```

When trying to delete a 'partial' episode, the: "Episode NOT deleted!" toast message
prints. The episode is not deleted on the client or on the backend.

I'm not sure if MAF is sending the wrong data or if the backend is at fault.
The timestamp sent from MAF to the backend is that of the scheduled
starttime, not the actual starttime of the recording.

In this example, the episode was recorded starting at two minutes after the hour:

```
GET /Dvr/RemoveRecorded?ChanId=1201&StartTime=2013-01-12T20%3A00%3A00
```

however, the scheduled starttime was used in the GET.

LogCat: http://paste.ubuntu.com/1528972/

**Comment by billmeek** [comment]
Retested as requested in the commit.

The problem still exists. Here's what I've collected: http://paste.ubuntu.com/1553125/

Note that for 'normal' recordings, e.g. recordings that were not restarted after their
starttime, the fix works. Also note the 1970-1-1 00:00:00 timestamp.

Just to make sure, I changed the code back to the original method and retested.
Trying to delete this recording (and others like it) still gives the user the same
toast message: "Episode NOT deleted!".

Tested on: mythtv-android-frontend-1.0.4-33-g79c4cc5-dirty, which is dirty because
of the change back to program.getStartTime().

**Comment by billmeek** [comment]
Just to verify that the data passed from MythTV is correct/available, I did a:

```
http://mc0:6544/Dvr/GetRecorded?ChanId=1201&StartTime=2013-01-12T20:02:00

    <Recording>
        <Status>-3</Status>
        <Priority>0</Priority>
        <StartTs>2013-01-12T20:02:00Z</StartTs> <-------------------------
        <EndTs>2013-01-12T20:30:00Z</EndTs>
```

I tried adding this just before the change:

```
if( null != program.getRecording() )
    Log.v(TAG, "program.getRecording() is null");
```

and the Log.v did fire.

Full XML is here: http://paste.ubuntu.com/1553453/

**Comment by dmfrey** [comment]
All Recorded programs should have a Recording entry.  I believe that is a 1-1 relationship between recorded and recording.  Can pastebin the sql output of the recording relationship?

I am thinking there has to be a combination of the start timestamp that isn't matching.  Does turning up the upnp logging on the backend show anything when trying to delete this episode via the app?

I think we might need to look at the delete code in the backend services as well.

**Comment by billmeek** [comment]
SQL is here: http://paste.ubuntu.com/1553125/ note the starttime on line 19, the basename
and progstart on lines 49 and 50. Recording began 2 minutes after the hour in this case,
but the scheduled start was on the hour. This happened when I used the frontend's guide
(EPG) and pressed r on a show that had already started.

The backend log lines are on lines 2 and 6 of the file.

The http://paste.ubuntu.com/1553453/ paste has the full XML returned from  this query:

```
http://mc0:6544/Dvr/GetRecorded?ChanId=1201&StartTime=2013-01-12T20:02:00
```

See line 57.

**Comment by dmfrey** [comment]
Yes, i was looking at those files.  The sql i was referring to was the
recording table, not the recorded table.

This is what I think is going on...

When we send that data to the backend to issue a delete, we are sending the
in the timestamp, but they are different, so it is probably trying to find
a recording with either the start time of the recordied or the start
timestamp of the recording, but using that data in the wrong table.  So,
for instance, the recording stimestamp is 2 minutes passed the start time
of the program, but probably trying to query the recorded table the
recording timestamp or vice a versa....make sense?

I think we need to look at the code for the service itself.  I will try to
find it in their github to take a look.

On Sun, Jan 27, 2013 at 10:36 AM, billmeek notifications@github.com wrote:

> SQL is here: http://paste.ubuntu.com/1553125/ note the starttime on line
> 19, the basename
> and progstart on lines 49 and 50. Recording began 2 minutes after the hour
> in this case,
> but the scheduled start was on the hour. This happened when I used the
> frontend's guide
> (EPG) and pressed r on a show that had already started.
> 
> The backend log lines are on lines 2 and 6 of the file.
> 
> The http://paste.ubuntu.com/1553453/ paste has the full XML returned from
> this query:
> 
> http://mc0:6544/Dvr/GetRecorded?ChanId=1201&StartTime=2013-01-12T20:02:00
> 
> See line 57.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/106#issuecomment-12755817.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
Yes, makes sense. Yet when 

```
<StartTs>2013-01-12T20:02:00Z</StartTs>
```

was used, it was null, I don't understand that.

I think this is what you want:

```
http://code.mythtv.org/cgit/mythtv/tree/mythtv/programs/mythbackend/services/dvr.cpp#n182
```

Are you referring to the record table for the SQL?

**Comment by billmeek** [comment]
Documenting some research:

Just to verify that an episode can be removed, I sent these two lines from
my browser. The 1st returned false and the 2nd returned true (and the
recorded table shows: recgroup = Deleted.

http://mc0:6544/Dvr/RemoveRecorded?ChanId=1201&StartTime=2013-01-12T20:00:00
http://mc0:6544/Dvr/RemoveRecorded?ChanId=1201&StartTime=2013-01-12T20:02:00

The timestamps used were, respectively:

```
<StartTime>2013-01-12T20:00:00Z</StartTime> (from recorded.progstart = 2013-01-12 20:00:00)
<Recording>
    <StartTs>2013-01-12T20:02:00Z</StartTs> (from recorded.starttime = 2013-01-12 20:02:00)
```

Trying GetRecorded (on a new show because the above is now gone,) the 1st line
fails and the 2nd works. The episode truly started recording 6 minutes after the hour.

http://mc0:6544/Dvr/GetRecorded?ChanId=1201&StartTime=2013-01-12T19%3A00%3A00
http://mc0:6544/Dvr/GetRecorded?ChanId=1201&StartTime=2013-01-12T19%3A06%3A00

GetRecorded is here and it calls FillProgramInfo which is at the 2nd line:

http://code.mythtv.org/cgit/mythtv/tree/mythtv/programs/mythbackend/services/dvr.cpp#n165
http://code.mythtv.org/cgit/mythtv/tree/mythtv/programs/mythbackend/services/serviceUtil.cpp#n41

```
Lines 49:     pProgram->setStartTime (  pInfo->GetScheduledStartTime());
Line 101:     pRecording->setStartTs ( pInfo->GetRecordingStartTime() );
```

See this for the SQL used to develop the output above: http://paste.ubuntu.com/1584056/
The tables used are recorded, channel, recordedprogram and record. I haven't tied this
all together yet (esp. recordedartwork must be used,) but I'm close.

**Comment by dmfrey** [comment]
I know what is going on here...

The data is loading correctly.  However, to join the Recorded table with the Recording table, my join is on record_id and start time.  Since the two start times are different, a join is never made, so when the start time is off from the program time, the recording record comes back null.  I need to add another key to the table that indicates the program start time as well as the recording start time, so that I can make a join and load the data correctly.  Then the delete should work.
