### ISSUE TITLE
Can't establish connection to MythTV

### ISSUE THREAD

**Issue by ebisumartin** [MythTV-Clients/MythTV-Android-Frontend#109]
I can not get any connection from MythTV Android on my Samsung Galaxy 10.1 tablet to my MythTV backend (Mythbuntu 12.10).

My Mythtv is on 192.168.0.4 and in "Host Address Backend Setup" the Port is 6543 and the Status port is 6544. In the Remote Control section of the General Setup interface, the Network Remote Control port is set to 6546, and Enable Network Remote Control interface is enabled.

I also use Mythmote (on it's own, not within MythTV Android), and for that, the connection port is 6546, and it works.

Following the directions in the MythTV-Android-Frontend FAQ available at https://github.com/MythTV-Clients/MythTV-Android-Frontend/wiki/FAQ , I ensured that my MythTV settings were in compliance with the MythTV Configuration Suggestions. My MythTV version is 0.25 or greater and using_libdns_sd appears in the output of "mythbackend --version":

MythTV Version : v0.26.0-86-g012ebe9
MythTV Branch : fixes/0.26
Network Protocol : 75
Library API : 0.26.20130112-1
QT Version : 4.8.3
Options compiled in:
 linux profile use_hidesyms using_alsa using_oss using_pulse using_pulseoutput using_backend using_bindings_perl using_bindings_python using_bindings_php using_crystalhd using_dvb using_firewire using_frontend using_hdhomerun using_ceton using_hdpvr using_iptv using_ivtv using_joystick_menu using_libcec using_libcrypto using_libdns_sd using_libxml2 using_lirc using_mheg using_opengl_video using_qtwebkit using_qtscript using_qtdbus using_v4l2 using_x11 using_xrandr using_xv using_bindings_perl using_bindings_python using_bindings_php using_mythtranscode using_opengl using_vaapi using_vdpau using_ffmpeg_threads using_live using_mheg using_libass using_libxml2

Lastly, I have the avahi-daemon running:

  923 ?        S      0:00 avahi-daemon: running [mythbuntu.local]
  925 ?        S      0:00 avahi-daemon: chroot helper

In MythTV Frontend on the Android, I open it, press the wrench icon for settings, and then select to "Scan Network". It waits for a bit and then nothing seems to happen. I'm not sure what the expected output should be, but no profiles are created and there doesn't seem to be anything I can act on.

I tried manually creating a home profile, using http://192.168.0.4:6544 as the Backend Address, and no WOL Address, but it hangs on "Retrieving Master Backend Details...". I have to use the Android application manager to kill the process. I also tried port 6543 and 6546, but got the same results.

My only goal is to be able to view my recorded videos (not live TV, or recorded TV, just what's in the "Watch Videos" section of my Media Library) on my Android tablet.

I hope someone can help me get this up and running.

Thank you for any help.

**Comment by billmeek** [comment]
Please try this from a browser on your backend:

```
http://<your backend's IPv4 address>:6544/Myth/GetHostName
```

If that works, try it from your tablet (I have a Galaxy 10.1 too, FYI)

If that fails, on you backend, enter this message:

```
mythbackend --setverbose upnp
```

Then retry the browser tests from the backend and the tablet.

Look in your backend log file, the response should be (in part:)

```
...  GetHostName : GET /Myth/GetHostName HTTP/1.1
```

**Comment by ebisumartin** [comment]
Thank you for your response. I tried your test on my browser on my tablet, and it worked.

After that, the app still wasn't connecting, but I killed the cached process on the tablet, restarted the app, and then I was able to get it working. I'm not sure exactly what step was necessary, but it would seem that it's helpful when trying new settings to completely stop and restart the app.

Unfortunately, after all this, it seems that the option to watch videos via the Android app is not yet functioning. That was the one thing I was hoping to do, so I guess I have to wait.

**Comment by billmeek** [comment]
Glad to hear you've got it running and thanks for your comments.

The Feature Status Wiki has been updated to include the 1.0.4 release.
The status is the same, but 1.0.4 should have been there.

The Connection Troubleshooting Guidelines Wiki mistakenly referred
to "videos", and has been corrected to "recordings".

I'm debating the addition of a 'kill cache' instruction. I do understand
it would have been a quick fix in this case, but it could also prevent
problems from being detected and solved if used too often.

And I completely missed your original comment about watching videos
only. My apologies.

I'm closing this issue. Feel free to reopen if you disagree.

**Comment by billmeek** [comment]
Yet another typo, above doesn't apply to this issue.
