### ISSUE TITLE
Activity org.mythtv.client.ui.preferences.LocationProfileEditor has leaked window

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#111]
Running on: mythtv-android-frontend-1.0.4-46-g2168017

Doesn't crash the app, but I haven't seen this before.

To Duplicate:

```
Start MAF with/or without an empty DB
Scan Network
Select Save
The error is fired
```

LogCat here: http://paste.ubuntu.com/1631142/ lines 145 and 231

**Comment by dmfrey** [comment]
I am not sure what is different between your tablet and mine, but I don't
get these errors on mine.

**Comment by billmeek** [comment]
FWIW: Galaxy 10.1, Android 4.0.4, Kernel 3.1.10.

I just retried the test. The app has been completely removed and reinstalled.
The tablet has been rebooted. I still get the errors (one for each backend.)
My recent commit is still commented out.
