### ISSUE TITLE
If no backends are available, Scan Network displays no popup/status

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#113]
New users may be confused by selecting Setup/Scan Network if
their backends aren't available and or mythbackend isn't running.

No status is given to the user.

When the backend comes up ( and Avahi is working) the Save/Cancel
screen comes up as expected.

To Duplicate:

```
Use Setup/Delete Home Profile, remove all backends
Force Stop the app
Make sure no backends are running
Start the app, select Setup/Scan Network
There will be no notification that the app is searching for backends
```

Tested with/without d9afa87a72933bff7ca9ae37bd68719fbc98b993

LogCat here: http://paste.ubuntu.com/1636862/

**Comment by billmeek** [comment]
Repeated the "To Duplicate" above and still get no notification that
no backend(s) could be reached.

The Scan Network area just turns blue momentarily. 

I was suggesting that something should notify the user that the scan
is in progress. Similar (or exactly the same as) what happens when
the user enters their IP address using Add New Home Profile.

**Comment by dmfrey** [comment]
Ah, i see now.  I mis-read the issue.  I thought you wanted a popup for
when it didn't find anything.

I will adjust it to popup when it starts scanning and stop when it finished.

On Wed, Feb 13, 2013 at 12:39 AM, billmeek notifications@github.com wrote:

> Repeated the "To Duplicate" above and still get no notification that
> no backend(s) could be reached.
> 
> The Scan Network area just turns blue momentarily.
> 
> I was suggesting that something should notify the user that the scan
> is in progress. Similar (or exactly the same as) what happens when
> the user enters their IP address using Add New Home Profile.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/113#issuecomment-13475364.

## 

My Google Profile http://www.google.com/profiles/dmfrey
