### ISSUE TITLE
No recordings on Recordings screen,  Writing exception to parcel fires

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#116]
Working with a user on IRC that has 1051 recordings and 498 channels.

He's unable to see any recordings. Running MythTV 0.25 and MAF 1.0.4.

I tested with mythtv-android-frontend-1.0.4-60-g6877542 and also didn't
see any recordings on the Recordings screen.

LogCat: http://paste.ubuntu.com/1658249/ line 3141

The above is from pressing the Refresh icon on the Recordings screen.

I have GetVideoSourceList, GetChannelInfoList and GetRecordedList available.

**Comment by billmeek** [comment]
I reran the tests in an emulator and looked at the database. It may be
of interest to know that the program_group table is empty. etags is empty
which makes sense for a 0.25 user. program is empty on my mc0 host as
well as his.

**Comment by dmfrey** [comment]
I would expect the program_group table to be populated.  If it is not, then we have a problem parsing the programs to groups.

Correct. etag should be empty for .25

program table is empty for now as it will hold the program guide data when the new method of loading the program guide is enabled.  for now, however, we will still use the downloaded json files.

**Comment by billmeek** [comment]
After commenting out the code that did INSERTs to the recording table, this
started working (as we discussed off list.)

I just retried using an emulator and the program_guide table has 181 entries,
and the 1st and last ones match the display on the Recordings screen.

So, your suggestion that there were combined UPDATE & INSERT queries
going on at the same time appears to be the problem.

I did find this: http://sqlite.org/lang_conflict.html but I'm not sure how using
ON CONFLICT REPLACE would affect what's being stored.

**Comment by dmfrey** [comment]
I will have to check and see if android supports the On Conflict Replace in
its implementation of sqlite.  From what I have found, the version of
sqlite in android is a few versions behind or doesn't implement all of the
features.  I ran into this previously and it affects backwards
compatibility with the app on the different versions of android.

Will do some digging.

On Mon, Feb 18, 2013 at 12:01 AM, billmeek notifications@github.com wrote:

> After commenting out the code that did INSERTs to the recording table, this
> started working (as we discussed off list.)
> 
> I just retried using an emulator and the program_guide table has 181
> entries,
> and the 1st and last ones match the display on the Recordings screen.
> 
> So, your suggestion that there were combined UPDATE & INSERT queries
> going on at the same time appears to be the problem.
> 
> I did find this: http://sqlite.org/lang_conflict.html but I'm not sure
> how using
> ON CONFLICT REPLACE would affect what's being stored.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/116#issuecomment-13706648.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
You're right, maybe this will save you some time:

```
http://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#CONFLICT_IGNORE
```

API level 8. Froyo 2.2-2.3.

**Comment by billmeek** [comment]
Tested with remote user over the internet and with my own Wifi access. Tested with
an the app/data completely removed, then  entering the Recordings screen; with
refreshing with the arrowed circle icon; and finally when the screen shuts off and then
is powered on. All 6 test cases worked A-OK. Closing the issue.
