### ISSUE TITLE
Tracking issue: Crash when downloading the 2nd channel listing

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#120]
Running on: mythtv-android-frontend-1.0.4-69-g141309b

When the channel sync takes place, users without ETags (e.g. 0.25) and
more than one source (as in Cable and OTA) may get a crash. 

LogCat shows that the 2nd request for the source is issued, however, the
backend's log doesn't receive it. Tests with tshark show that the 2nd request
is being send after the backend has already closed the conversation (FIN/ACK.)
The backend host responds to the 2nd request with a TCP RST.

Testing with or without gzip turned on makes little difference.

<pre>
02-16 18:35:59.257: E/ChannelDownloadService(23404): onHandleIntent : error handling files
02-16 18:35:59.257: E/ChannelDownloadService(23404): org.springframework.web.client.ResourceAccessException: I/O error: null; nested exception is java.io.EOFException
02-16 18:35:59.257: E/ChannelDownloadService(23404):    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:491)
02-16 18:35:59.257: E/ChannelDownload
</pre>

**Comment by billmeek** [comment]
Workaround in  commit 458e456

**Comment by dmfrey** [comment]
Please retest on a .25 backend when issue #121 is closed. Downloading channel json has been refactored slightly and should result in cleaner download and processing.

**Comment by billmeek** [comment]
Retested with nap time set to 1ms and had no failures in 20 tests on
my 0.27-pre2 (ETags off) mc0 host and Jeff's 0.25 host. 1ms failed before.

Leaving this open at least for now because the FIN, ACK from the
backend isn't being answered. Still have myself assigned to the issue.

**Comment by billmeek** [comment]
Closing. Will open a new issue if this continues to be a problem.
