### ISSUE TITLE
Should pressing the refresh button on recordings or upcoming trigger a fresh download whether or not the stored etag returns a HTTP 304?

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythTV-Android-Frontend#122]
Just wondering what the app should do in thus case.

**Comment by pot8oe** [comment]
How about leaving refresh as it stands and add a reset menu item. Reset
would clear and repull everything. does that make sense?

**Comment by dmfrey** [comment]
That would work. Is reset the appropriate term here?

**Comment by pot8oe** [comment]
I don't know. Reset was the first thing that came to mind. Clear data?

**Comment by billmeek** [comment]
Need an update from the developers. I'd suggest making the Refresh icon trigger a
fresh download. As opposed to adding another menu item. There should be no
need to refresh unless there's something's missing in the current display or if the
user knows that something has changed in Upcoming/Recordings.

**Comment by pot8oe** [comment]
I agree. Fresh download!

-Tom

**Comment by dmfrey** [comment]
This will be pretty easy to fix. Just delete the etag for the respective
service endpoint when the refresh button is pressed.

I will take a look tonight.
