### ISSUE TITLE
User-created playback profiles

### ISSUE THREAD

**Issue by Prefect47** [MythTV-Clients/MythTV-Android-Frontend#126]
I modified the 540p to match the PAL "resolution" of 768x576. Is it possible to instead add your own profiles?

**Comment by dmfrey** [comment]
This could be added.  Will add as an enhancement.

@Prefect47 Do you have PAL equivalents for what we currently default to in playback profiles?  Maybe we could enhance this so that based on your country specified in your system settings, we load the appropriate list of defaults.

**Comment by billmeek** [comment]
No response after 6 months. Please reopen with the suggested PAL
equivalents. Thanks.
