### ISSUE TITLE
"Syncing Recorded Programs" notification never disappears

### ISSUE THREAD

**Issue by Prefect47** [MythTV-Clients/MythTV-Android-Frontend#127]
The "Syncing recorded programs" notification never disappears, unless I force stop the app.

I've tried this on two devices.

**Comment by dmfrey** [comment]
@Prefect47 can you send us the specifications for your devices, android versions, etc.

These notifications will be changing in the next release of the app, btw.  They will be more in-app, versus in the notification bar.

**Comment by billmeek** [comment]
The following is from a user I'd been working with off list on another item. He has data
that matches the original post (including the attached screenshot) and has emailed it
to me:

```
Android Version:  4.2.2  (JellyBean) Cyanogenmod 10
Device Name & Model: Samsung Captivate i897  (1GHz Arm8 Cpu, 512MB ram, 16GB flash + 32GB uSDHC)
MAF Version:          1.10.1
MythTV Version       v0.26.0-155-gac5525d   (GIT pull of 0.26-fixes earlier in the week)
```

Starting _after a boot_ of the device, the failure is created by:

```
1. Start MAF
2. Click "Home"
3. Click "Recordings"
4. The list of shows populates quickly [just a few seconds]
5. Select a recording, then the Eyeball (Watch), then "Play with HLS".
6. Recording starts playing in a bit (pretty quick for MPEG2 [5-20 secs], takes a while for H.264 [30-45 secs])
-   and sometimes pauses or exits if the backend can't transcode fast enough.
7. Exit out of a recording during playback.  (status bar items are still there)
8. Even after exiting MAF or killing it with a task killer, the notifications are not cancelled.
9. Starting MAF again and doing the same sequence results in more status bar notifications that 'stick'
10. Notifications do not go away unless I re-boot my phone.
```

Going back with the 'back' button ends up creating another 'Syncing
Recorded Programs' status bar entry.  It would appear that it's never being
cancelled.

![syncrecdprogsnevergoesaway](https://f.cloud.github.com/assets/1831699/522257/bf115f54-c013-11e2-8a72-a7f11b47beb6.png)

**Comment by dmfrey** [comment]
notifications are gone and will be replaced with an in app indicator to verify if the service is running or not
