### ISSUE TITLE
Playing the same HLS stream from two devices?

### ISSUE THREAD

**Issue by Prefect47** [MythTV-Clients/MythTV-Android-Frontend#128]
I set my tablet to transcode three shows to 768x576. When the first one was finished I tried playing it in DICE, and it worked fine. Though the link to the m3u file says 1024x576 which is not what I configured...

Then I played it with HLS on a second device, but forgot to modify the 540p profile and it started trsnacoding. I pressed the "X" but the transcoding doesn't stop. So I went into port 6544 on my backend (web interface) and stopped all transcodings and attempted to delete them, but it just keeps refreshing and nothing changes (backend is 0.25.1). Restarting mythbackend fixes the blinking but is probably not related.

Now the playback works on the first device, but on the second device it shows the transcoding to be 64788%  (64 thousand percent) complete and playback always fails. This stays even if I restart the device. I will try to clear the app data/cache and try again.

**Comment by dmfrey** [comment]
We need to add a sync process for the HLS streams as identified in issue #123 

Will move this to that issue to track the progress of that feature.
