### ISSUE TITLE
Backend off, select Home, NPE fires

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#129]
Running on: mythtv-android-frontend-1.10.1-2-g8ae01ae

Trying to duplicate errors found on the Developer Console.

Similar to #78, #101 and #113.

To Duplicate:

<pre>
Start app
Verify backend mc0 is configured
Select a backend mc1
Stop app
Verify backend mc0 is powered down
Start app
From Settings, select mc0
Press Home
</pre>

At this point the app will NPE on attempts to connect to any host. Even
Force Stop/Clear Cache and a tablet restart don't help.

<pre>
select * from location_profile;
_id|TYPE|NAME|URL|SELECTED|CONNECTED|VERSION|PROTOCOL_VERSION|WOL_ADDRESS|HOSTNAME
1|HOME|Mythbackend on mc1|http://192.168.1.223:6544/|0|0||||mc1
2|HOME|Mythbackend on mc0|http://192.168.1.204:6544/|1|1||||mc0

select * from status;
_id|KEY|VALUE|DATE
1|MASTER_BACKEND_CONNECTED|FALSE|1362440696591
</pre>

Watching the backend with tshark showed no protocol was being sent from the app,
except if Scan Network was used.

Only after doing an adb uninstall org.mythtv did the app start working again.

The following fires (full LogCat: http://pastebin.com/raw.php?i=jbvr3dPB ):

<pre>
03-06 14:05:24.464: W/dalvikvm(5159): threadid=11: thread exiting with uncaught exception (group=0x40c471f8)
03-06 14:05:24.474: E/AndroidRuntime(5159): FATAL EXCEPTION: IntentService[ProgamGuideDownloadService]
03-06 14:05:24.474: E/AndroidRuntime(5159): java.lang.NullPointerException
03-06 14:05:24.474: E/AndroidRuntime(5159):     at org.mythtv.service.guide.ProgramGuideCleanupService$1.accept(ProgramGuideCleanupService.java:94)
03-06 14:05:24.474: E/AndroidRuntime(5159):     at java.io.File.list(File.java:775)
03-06 14:05:24.474: E/AndroidRuntime(5159):     at org.mythtv.service.guide.ProgramGuideCleanupService.cleanup(ProgramGuideCleanupService.java:100)
03-06 14:05:24.474: E/AndroidRuntime(5159):     at org.mythtv.service.guide.ProgramGuideCleanupService.onHandleIntent(ProgramGuideCleanupService.java:69)
03-06 14:05:24.474: E/AndroidRuntime(5159):     at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
03-06 14:05:24.474: E/AndroidRuntime(5159):     at android.os.Handler.dispatchMessage(Handler.java:99)
03-06 14:05:24.474: E/AndroidRuntime(5159):     at android.os.Looper.loop(Looper.java:137)
03-06 14:05:24.474: E/AndroidRuntime(5159):     at android.os.HandlerThread.run(HandlerThread.java:60)
</pre>

**Comment by dmfrey** [comment]
please retest, this is now a part of the backend status page which should gracefully fall back to a "not connected" page

**Comment by dmfrey** [comment]
closing for now as backend status gracefully falls back to a "not connected" screen

**Comment by billmeek** [comment]
Repeated initial test. Confirmed closed.
