### ISSUE TITLE
Multi-host enhancement Slave Backend test results

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#130]
From the mythtv-users list (Yianni,) recordings that are made on a Slave Backend
have their titles displayed on the Recordings screen, however individual episodes
are not.

Looking in the recorded table, the episode is there. The hostname column
correctly lists the Slave Backend's hostname (mc1 in my test case) while the
Selected Home Profile's Master Backend is different (mc0 in the test.)

On the Guide screen, the episode being recorded has no red boarder.

The Recording Rules  screen appears correct.

The Upcoming screen does not reflect a future episode scheduled to record on
the Slave Backend. Using: http://mc0:6544/Dvr/GetUpcomingList does show the
episode and the host is mc1.

As in the past, I've lumped the tests of all 4 screens into one ticket, not knowing
if the solution is a generic one or not. It appears that keeping the HOSTNAME
column is desirable, but perhaps adding and filtering on some other column
would be correct.

**Comment by dmfrey** [comment]
I think i might have an idea of what is going on here.  The recorded list
already has a hostname in it.  I guess I need to store the hostname in all
the tables as masterbackend hostname and then leave the one coming back in
the list alone.

On Thu, Mar 7, 2013 at 2:44 PM, billmeek notifications@github.com wrote:

> From the mythtv-users list (Yainni,) recordings that are made on a Slave
> Backend
> have their titles displayed on the Recordings screen, however individual
> episodes
> are not.
> 
> Looking in the recorded table, the episode is there. The hostname column
> correctly lists the Slave Backend's hostname (mc1 in my test case) while
> the
> Selected Home Profile's Master Backend is different (mc0 in the test.)
> 
> On the Guide screen, the episode being recorded has no red boarder.
> 
> The Recording Rules screen appears correct.
> 
> The Upcoming screen does not reflect a future episode scheduled to record
> on
> the Slave Backend. Using: http://mc0:6544/Dvr/GetUpcomingList does show
> the
> episode and the host is mc1.
> 
> As in the past, I've lumped the tests of all 4 screens into one ticket,
> not knowing
> if the solution is a generic one or not. It appears that keeping the
> HOSTNAME
> column is desirable, but perhaps adding and filtering on some other column
> would be correct.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/130
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
Leaving this issue closed and linking it to #148, which I'll reopen.
