### ISSUE TITLE
Recording Rules screen: Fatal Error if backend becomes unavailable

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#131]
Running on: mythtv-android-frontend-1.10.1-2-g8ae01ae. Trying to
duplicate a Developer Console report. This doesn't create an exact
match, but it's close.

To Duplicate:

```
Verify that the backend is running
Go to the Recording Rules screen
Stop the backend
Press any rule's 0/1 button
```

App sends TCP SYN to the backend, backend correctly returns an RST
because port 6544 has no listener. Exception fires (ResourceAccessException).

Seems to be a common case that the org.spring doesn't handle
TCP errors. Including link errors, mythbackend not running, backend host
failure etc. to name the most common cases.

<pre>
07-30 18:26:22.470: V/NetworkHelper(2254): getMythServicesApi : enter
07-30 18:26:22.470: V/NetworkHelper(2254): getMythServicesApi : exit
07-30 18:26:22.540: W/dalvikvm(2254): threadid=12: thread exiting with uncaught exception (group=0x40c361f8)
07-30 18:26:22.560: E/AndroidRuntime(2254): FATAL EXCEPTION: AsyncTask #2
07-30 18:26:22.560: E/AndroidRuntime(2254): java.lang.RuntimeException: An error occured while executing doInBackground()
07-30 18:26:22.560: E/AndroidRuntime(2254):     at android.os.AsyncTask$3.done(AsyncTask.java:278)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at java.lang.Thread.run(Thread.java:856)
07-30 18:26:22.560: E/AndroidRuntime(2254): Caused by: org.springframework.web.client.ResourceAccessException: I/O error: failed to connect to /192.168.1.223 (port 6544): connect failed: ECONNREFUSED (Connection refused); nested exception is java.net.ConnectException: failed to connect to /192.168.1.223 (port 6544): connect failed: ECONNREFUSED (Connection refused)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:491)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:453)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:429)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at org.mythtv.services.api.dvr.impl.DvrTemplate.disableRecordingSchedule(DvrTemplate.java:154)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at org.mythtv.client.ui.dvr.RecordingRulesFragment$SetRuleActiveStateTask.doInBackground(RecordingRulesFragment.java:357)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at org.mythtv.client.ui.dvr.RecordingRulesFragment$SetRuleActiveStateTask.doInBackground(RecordingRulesFragment.java:1)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at android.os.AsyncTask$2.call(AsyncTask.java:264)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
07-30 18:26:22.560: E/AndroidRuntime(2254):     ... 5 more
07-30 18:26:22.560: E/AndroidRuntime(2254): Caused by: java.net.ConnectException: failed to connect to /192.168.1.223 (port 6544): connect failed: ECONNREFUSED (Connection refused)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at libcore.io.IoBridge.connect(IoBridge.java:114)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at java.net.Socket.connect(Socket.java:842)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at libcore.net.http.HttpConnection.<init>(HttpConnection.java:77)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at libcore.net.http.HttpConnection.<init>(HttpConnection.java:50)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:351)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:86)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at libcore.net.http.HttpConnection.connect(HttpConnection.java:128)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:308)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at libcore.net.http.HttpEngine.connect(HttpEngine.java:303)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:282)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:232)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at libcore.net.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:80)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:72)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:46)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:63)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:476)
07-30 18:26:22.560: E/AndroidRuntime(2254):     ... 12 more
07-30 18:26:22.560: E/AndroidRuntime(2254): Caused by: libcore.io.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at libcore.io.Posix.connect(Native Method)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:85)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at libcore.io.IoBridge.connectErrno(IoBridge.java:127)
07-30 18:26:22.560: E/AndroidRuntime(2254):     at libcore.io.IoBridge.connect(IoBridge.java:112)
07-30 18:26:22.560: E/AndroidRuntime(2254):     ... 29 more
07-30 18:26:22.610: V/AbstractMythFragment(2254): onStart : enter
</pre>

Protocol:

```
12:41:26.317646   tab0.local -> mc1.local    TCP 74 40234 > lds-dump [SYN] Seq=0
12:41:26.317742    mc1.local -> tab0.local   TCP 54 lds-dump > 40234 [RST, ACK] 
```

**Comment by billmeek** [comment]
Retested on: mythtv-android-frontend-1.10.1-178-ge34b3aa 
in the sidebar_menu branch and  replaced expired link to LogCat
with new in-line output in the original comment in this thread.

**Comment by dmfrey** [comment]
this is no longer an issue as this functionality was removed with #150 in commit 5bda505

This functionality will be moved to the recording rule dialog fragment that is forthcoming.
