### ISSUE TITLE
Live TV

### ISSUE THREAD

**Issue by phoniclynx** [MythTV-Clients/MythTV-Android-Frontend#135]
Is it possible to get Live TV transcoding.. its great to view recordings and such.. but one BIG feature is the ability to watch TV as its happening.. Not sure why no one has done this part yet as its one of the big things Myth was designed for lol.

**Comment by dmfrey** [comment]
We can only implement what the myth services api makes available to us.
Unfortunately, live TV is not a feature they support yet.

If/when the myth services api supports it, we will also support it.

closes #135

**Comment by phoniclynx** [comment]
Where do we start partitioning for something like this? Kinda a fundamental thing to the whole ecosystem lol.

**Comment by dmfrey** [comment]
It would have to be with the core mythtv project. I would open a ticket in
their bug tracker.

**Comment by billmeek** [comment]
@phoniclynx,  Keep in mind that requests for features are usually closed in Trac as a
"Feature Request Without a Patch" if one isn't provided. Note the 4th bullet item under
First Steps here: http://code.mythtv.org/trac/wiki/TicketHowTo

**Comment by billmeek** [comment]
Closing, can be reopened as an Enhancement _if_ it becomes available
in the MythTV Services API
