### ISSUE TITLE
Sort Program Guide By Channel Number

### ISSUE THREAD

**Issue by TheFuzz4** [MythTV-Clients/MythTV-Android-Frontend#137]
Is it possible to have the Program Guide Sorted by Channel Number instead of the random sort that it is currently in?  Thanks.

**Comment by dmfrey** [comment]
The program guide is sorted by channel number.  Are your channel numbers
OTA channels where they usually have something like an '_' in them?

The program guide is going to be be completely rewritten, btw.

On Tue, Apr 9, 2013 at 3:01 PM, TheFuzz4 notifications@github.com wrote:

> Is it possible to have the Program Guide Sorted by Channel Number instead
> of the random sort that it is currently in? Thanks.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/137
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by TheFuzz4** [comment]
Only one channel has a - in it.  Would you like a screenshot of this?  BTW I would like to help you with the coding.  I am no developer but I figure I can pull down the code and take a look at it.

**Comment by pot8oe** [comment]
I have OTA channels 2_1, 2_2, 4_1, etc ... and they sort fine.

-Tom

**Comment by dmfrey** [comment]
Yes, please attach a screenshot to this thread.

If you would like to build the app, please take a look at our wiki page to
setup the development environment.  Please let me know if you have any
issues getting it setup.  I would be glad to help you be able to run the
code locally.  Once you are familiar with the environment and how the
project is laid out, you can start looking at the code.

On Tue, Apr 9, 2013 at 3:09 PM, TheFuzz4 notifications@github.com wrote:

> Only one channel has a - in it. Would you like a screenshot of this? BTW I
> would like to help you with the coding. I am no developer but I figure I
> can pull down the code and take a look at it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/137#issuecomment-16133521
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by TheFuzz4** [comment]
![Program Guide Screen Shot](https://f.cloud.github.com/assets/325957/358735/52d7039e-a14a-11e2-88a2-b0c0d17e9350.png)

The only thing that I can think of about this is that I have 2 guide sources because I have an internal tuner card that I use for my locals and then I have a HD Homerun Prime that I also use for locals as well as the rest of my lineups.  They do display properly in the schedule and on my mythweb.

**Comment by dmfrey** [comment]
hmm, it is probably coming back from the web service this way.  These are
just json file stored locally.  We don't do any manipulating of them.

On Tue, Apr 9, 2013 at 3:21 PM, TheFuzz4 notifications@github.com wrote:

> [image: Program Guide Screen Shot]https://f.cloud.github.com/assets/325957/358735/52d7039e-a14a-11e2-88a2-b0c0d17e9350.png
> 
> The only thing that I can think of about this is that I have 2 guide
> sources because I have an internal tuner card that I use for my locals and
> then I have a HD Homerun Prime that I also use for locals as well as the
> rest of my lineups. They do display properly in the schedule and on my
> mythweb.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/137#issuecomment-16134208
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
I don't have the problem and have one guide source for OTA and one for Cable
(PCI card and HDHR-Prime) too.

I think the issue is that the sorting is done by chanid, not channum, on the MythTV host
and, as TheFuzz4 points out, he has locals on his cable source (which I don't.)

@TheFuzz4, please run the following mysql command:

```
SELECT DISTINCT p.chanid,c.channum FROM program AS p,channel AS c WHERE p.chanid = c.chanid ORDER BY c.chanid;
```

and put the output in pastebin.com (or any other pastebin you like) and put a link to
the result in your response to this comment. 

You can also generate the source for one hour's worth of Guide data by running
the following from a browser:

```
http://<yourMythTVBackendHost>:6544/Guide/GetProgramGuide?StartTime=2013-05-13T05%3A00%3A00&EndTime=2013-05-13T05%3A59%3A59&StartChanId=1
```

Obviously, the timestamps need to be set to reasonable values.

**Comment by billmeek** [comment]
I'm seeing this in the new Guide screen.

@dmfrey, I suggest that this can be solved by sorting by FIELD_CHAN_ID rather than
FIELD_CHAN_NUM_FORMATTED. I've tested the fix in the sidebar_menu branch.

Rather than seeing 101, 102 ... 199, 2_1, 3xx etc, I now see 2_1, 101, 102 ...  In other
words, the channels are grouped by Source and channel. So all the OTA channels
show up 1st (in my case.)

Let me know if this is OK with your plans and I'll push it.

**Comment by dmfrey** [comment]
Chan_id is the id used when the channels are inserted into the db on the
backend.  If you delete a lineup and readd it, they will all get new ids
and bet bumped to the end.  I added the formatted one to handle adding
channel nums with alpha chars in them.  Do we just need to tweak how
certain numbers get formatted?

On Mon, Jul 8, 2013 at 10:51 AM, billmeek notifications@github.com wrote:

> I'm seeing this in the new Guide screen.
> 
> @dmfrey https://github.com/dmfrey, I suggest that this can be solved by
> sorting by FIELD_CHAN_ID rather than
> FIELD_CHAN_NUM_FORMATTED. I've tested the fix in the sidebar_menu branch.
> 
> Rather than seeing 101, 102 ... 199, 2_1, 3xx etc, I now see 2_1, 101, 102
> ... In other
> words, the channels are grouped by Source and channel. So all the OTA
> channels
> show up 1st (in my case.)
> 
> Let me know if this is OK with your plans and I'll push it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/137#issuecomment-20610663
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
Re: Do we just need to tweak how certain numbers get formatted?

I'd say yes. Looking back at my comment on this issue 2 months 
ago, I wasn't seeing the problem, that is, all of my Over The Air
channels were displayed followed by my HDHR Prime channels.

**Comment by dmfrey** [comment]
program guide data is now stored in the local database and channels are sorted by channel number (could be a number or could be text like 2_1).  This should no longer be an issue

**Comment by billmeek** [comment]
Running on: mythtv-android-frontend-1.10.1-414-g6745950. This still appears
to be an issue. My Over-theAir channels are intermixed with cable, for example:

```
141, 143, 2_1, 301 ... 382, 5_1, 602 ... 691, 7_1, 9_1, 11_1
```

I understand your comment about Chan_Id being changeable if the backend's
sources are redone. Would it be possible to add the channel.SOURCE_ID
to the sort process? I know that can change too, but isn't a fresh copy loaded
each time the app is started?

**Comment by dmfrey** [comment]
yes, this is possible.  It is easy to add this. What specifically would you
like to sort on.

On Mon, Aug 26, 2013 at 3:57 PM, billmeek notifications@github.com wrote:

> Running on: mythtv-android-frontend-1.10.1-414-g6745950. This still appears
> to be an issue. My Over-theAir channels are intermixed with cable, for
> example:
> 
> 141, 143, 2_1, 301 ... 382, 5_1, 602 ... 691, 7_1, 9_1, 11_1
> 
> I understand your comment about Chan_Id being changeable if the backend's
> sources are redone. Would it be possible to add the channel.SOURCE_ID
> to the sort process? I know that can change too, but isn't a fresh copy
> loaded
> each time the app is started?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/137#issuecomment-23290072
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
I couldn't figure out how to do it on the MAF data with sqlbrowser, but on the
backend/MySQL, it was:

```
... ORDER BY sourceid,channum
```

(although in MySQL that puts 11_1 before  2_1 while your existing sort has
them in the correct order, just interspersed with the cable channels)

**Comment by dmfrey** [comment]
I think I am converting all channel numbers to a floating point numbers and
then sorting.

So 2 would be 2.0 and 11_1 would be 11.1.

I thought this was handling the sort

**Comment by billmeek** [comment]
I believe that would work great for my case. But, I don't have any channels below 100
active for my cable box (and my highest OTA channel is 50_1.) Users with analog 
channels or low numbered cable channels would still see the intermixing.

**Comment by dmfrey** [comment]
@billmeek  what does the chan_num_formated column in your sqlite db look like?

I was slightly off in my previous description of the formatted column.  I am padding these out with zeros and then formatting them as text.  I think the issue is that these text formated channel numbers are not always in the 2_1 fomrat.  The underscore could be any number.

**Comment by billmeek** [comment]
@dmfrey there are OTA lines like 05_2 and _5_3 (which is an 'invisible' channel in MythTV.)
They are left adjusted. Cable channels all look like 0xxx e.g. 0142.

This is from an 8/22/13 dump. Let me know if something has changed and you need a 
fresh one.

**Comment by dmfrey** [comment]
@billmeek try this again.  I made the switch over to making the formatted channels a float where everything after the  delimiter is on the right of the decimal point.  I inspect each for the delimiter and use it if it is different than an underscore

**Comment by billmeek** [comment]
Works for me. Interesting note: 5_1 is stored as: 5.19999980926514.
All of the other X_Y channels with the exception of 26_5 have the
correct tenths digit, but 12 digits following e.g. 9.10000038146973.
26_5 has the expected value of exactly 26.5.
