### ISSUE TITLE
Activating the MythTV Miscellaneous Status Option Results in Fatal Exceptions

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#139]
Running on: mythtv-android-frontend-1.10.1-95-g8917008, sidebar_menu branch.

MythTV allows users to add additional information to their status page. If
a user has activated this option, the following fires:

LogCat: http://pastebin.com/raw.php?i=FAzGvgLd

Look for the 12th line in the above and note the following:

<pre>
Element 'Miscellaneous' does not have a match in class org.mythtv.services.api.status.Status at line 55
</pre>

Simple workaround. Use mythtv-setup, Miscellaneous Settings page,
Miscellaneous status application, blank the field.

The additional section will always begin with Miscellaneous if the user
has added the option. The data following it is the output of the  program
the user has written/copied and isn't predictable by any app.

http://code.mythtv.org/cgit/mythtv/tree/mythtv/programs/mythbackend/httpstatus.cpp#n567

**Comment by dmfrey** [comment]
Do we know if there is a schema available for the Status XML?  Honestly, i was unaware of this setting in mythtv.  I am gonna enable it and see what extra data comes back.  A schema would help take all the guess work out of it, however.

**Comment by billmeek** [comment]
http://www.mythtv.org/wiki/Miscellaneous_Status_Information

Here's a simple version of a user defined status script:

<pre>
#!/bin/sh
# Get data for the WEB Miscellaneous backend status.
mythshutdown --check --verbose general --loglevel notice | \
    grep " N " | grep -v -f /usr/local/sbin/MythStatus.ignore | \
    sed -e 's/^.......................//' | \
    awk '{ printf "%s %s %s %s %s[]:[].[]:[]\n", $3, $4, $5, $6, $7 }'
# Enter your user/password here:
mysql -u mythtv -pmythtv mythconverg -e \
    "SELECT value,data FROM settings WHERE value='MythShutdownLock'" | \
    awk '/MythShutdownLock/ { printf "Shutdown Lock Count = %s[]:[].[]:[]\n", $2 }'
pgrep mythfrontend > /dev/null
if [ $? = 0 ]
then echo "Media Center Frontend Is Running[]:[].[]:[]"
else echo "Media Center Frontend Is Not Running[]:[].[]:[]"
fi
</pre>

The output of the above is just:

```
Shutdown Lock Count = 1[]:[].[]:[]
Media Center Frontend Is Not Running[]:[].[]:[]
```

I happened to have something like the above on both of my backends.
So this was pretty much a lucky catch. Truth be told, I really don't look
at the web status page much.

**Comment by billmeek** [comment]
To answer you schema question, I believe the answer is that there is none.
Any user can write a script that returns whatever they wish. One example
in the Wiki is used to report the temperature of the backend. I was interested
in things that prevent my system from shutting down, e.g. the lock counter.

**Comment by dmfrey** [comment]
I was referring to an XML schema or wsdl for the status XML being returned.

Can you dump your status XML and post it here? I will use that fix the
service api.

**Comment by billmeek** [comment]
Using: mc1:6544/Status/GetStatus, the XML added after the 
'normal' </MachineInfo> section is:

```
<Miscellaneous>
<Information display="Shutdown Lock Count = 1" name="."/>
<Information display="Media Center Frontend Is Not Running" name="."/>
</Miscellaneous>
```

Lines 227 through 231 here are the HTML from mythweb's status display:

   http://pastebin.com/v9v0yTEn

Also, I think this is where the Miscellaneous heading gets created:

http://code.mythtv.org/cgit/mythtv/tree/mythtv/programs/mythbackend/httpstatus.cpp#n572

```
QDomElement misc = pDoc->createElement("Miscellaneous");
```

And then for each line:

```
DomElement info = pDoc->createElement("Information");
```

**Comment by billmeek** [comment]
I've updated the MythTV Wiki page that covers this topic to include reference
to the Services API.  The XML format is described in this section:

http://www.mythtv.org/wiki/Miscellaneous_Status_Information#Backend_Status_Format

**Comment by dmfrey** [comment]
added optional Miscellaneous tag to Status response in myth services api 0.0.32-SNAPSHOT.  Will be released as 0.0.32 when all other tests have been completed

**Comment by billmeek** [comment]
No crash, however the status line is no longer displayed (it was one
line that included the hostname.)

**Comment by dmfrey** [comment]
hmm, that is telling me that it isn't fully functional yet.

I will enable the miscellaneous fields this weekend and try it out on my
backend.

On Fri, May 17, 2013 at 8:17 AM, billmeek notifications@github.com wrote:

> No crash, however the status line is no longer displayed (it was one
> line that included the hostname.)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/139#issuecomment-18058152
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
I just did a Force Stop and Clear Cache on the app then restarted it. The original
one line status display returned:

```
Connected to Mythbackend on mc1
```

@dmfrey, is the above everything I should expect to see at this time, as
opposed to what is returned when http://mc1:6544/Status/GetStatus is
send from a browser? The one line status is the same as I was getting 
before this fix went in, so I'm closing this issue.

**Comment by dmfrey** [comment]
this morning i added some of the scripts you recommended in the links.
 will try the app with them loaded to test as well.

On Fri, May 17, 2013 at 10:05 AM, billmeek notifications@github.com wrote:

> I just did a Force Stop and Clear Cache on the app then restarted it. The
> original
> one line status display returned:
> 
> Connected to Mythbackend on mc1
> 
> @dmfrey https://github.com/dmfrey, is the above everything I should
> expect to see at this time, as
> opposed to what is returned when http://mc1:6544/Status/GetStatus is
> send from a browser? The one line status is the same as I was getting
> before this fix went in, so I'm closing this issue.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/139#issuecomment-18063208
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
This is a simpler version just to test the position of the results,
as well as making sure that MythTV doesn't honor more than
the 3 allowed attributes. Seems the 2nd and 3rd get reversed
by the backend, not the app.

<pre>
echo "No Delimiters"
echo "One <B>Delimiter</B>, empty trailing attribute[]:[]"
echo "One Delimiter[]:[]Two attributes"
echo "Two Delimiters[]:[]Two attributes[]:[]"
echo "Two Delimiters[]:[]Three attributes[]:[]This is the 3rd attribute"
echo "Three Delimiters[]:[]2nd attribute[]:[]3rd attribute[]:[]"
echo "Three Delimiters[]:[]2nd attribute[]:[]3rd attribute[]:[]4th attribute, shouldn't print"
</pre>
