### ISSUE TITLE
After MythTV v0.27-pre, Commit 286593 the Recording Rules Screen Fails

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#140]
http://code.mythtv.org/trac/changeset/286593

Enhances the Recording Rules Services API and changes the version from
1.10 to 1.11. AddRecordSchedule and GetRecordSchedule have been 
improved. UpdateRecordSchedule has been added.

**Comment by dmfrey** [comment]
This gives me reason to refactor this so that it is using the same content
provider rules the rest of the app does.  This way they can be viewed
offline.

Now that work has subsided a bit, i will be able to back on this.

On Tue, May 7, 2013 at 3:45 PM, billmeek notifications@github.com wrote:

> http://code.mythtv.org/trac/changeset/286593
> 
> Enhances the Recording Rules Services API and changes the version from
> 1.10 to 1.11. AddRecordSchedule and GetRecordSchedule have been
> improved. UpdataRecordSchedule has been added.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/140
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by dmfrey** [comment]
Actually, what we are considering is a refactoring the myth services api to
be version based.  So when we get the major/minor version from the status
endpoint, only correct functionality appropriate to your backend will be
able to be fired.  This might go right along with this issue as it would
break pre-.27 backends.

On Tue, May 7, 2013 at 4:09 PM, Daniel Frey dmfrey@gmail.com wrote:

> This gives me reason to refactor this so that it is using the same content
> provider rules the rest of the app does.  This way they can be viewed
> offline.
> 
> Now that work has subsided a bit, i will be able to back on this.
> 
> On Tue, May 7, 2013 at 3:45 PM, billmeek notifications@github.com wrote:
> 
> > http://code.mythtv.org/trac/changeset/286593
> > 
> > Enhances the Recording Rules Services API and changes the version from
> > 1.10 to 1.11. AddRecordSchedule and GetRecordSchedule have been
> > improved. UpdataRecordSchedule has been added.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/140
> > .
> 
> ## 
> 
> My Google Profile http://www.google.com/profiles/dmfrey

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
Still fails.

Running on: mythtv-android-frontend-1.10.1-98-g8585521 sidebar_menu branch

The MythTV source for this is here (has a list of the fields:)
http://code.mythtv.org/cgit/mythtv/tree/mythtv/libs/libmythservicecontracts/datacontracts/recRule.h

Day, Time and FindId were replaced with FindDay and FindTime

```
<RecRuleList version="1.0" serializerVersion="1.1">
<StartIndex>0</StartIndex>
<Count>13</Count>
<TotalAvailable>13</TotalAvailable>
<AsOf>2013-05-16T05:36:54Z</AsOf>
<Version>0.27.20130430-1</Version>
<ProtoVer>77</ProtoVer>
<RecRules>
    <RecRule>
        <Id>35</Id>
        <ParentId>0</ParentId>
        <Inactive>false</Inactive>
        <Title>Blue Bloods</Title>
        <SubTitle/>
        <Description>A Reagan's life is in danger after three criminals are released from prison.</Description>
        <Season>0</Season>
        <Episode>0</Episode>
        <Category>Unknown</Category>
        <StartTime>2011-08-26T05:00:00Z</StartTime>
        <EndTime>2011-08-26T05:00:00Z</EndTime>
        <SeriesId/>
        <ProgramId/>
        <Inetref/>
        <ChanId>1021</ChanId>
        <CallSign>CBS2 HD</CallSign>
        <FindDay>6</FindDay>
        <FindTime>21:00:00</FindTime>
        <Type>Record All</Type>
        <SearchType>None</SearchType>
        <RecPriority>2</RecPriority>
        <PreferredInput>0</PreferredInput>
        <StartOffset>0</StartOffset>
        <EndOffset>0</EndOffset>
        <DupMethod>Subtitle and Description</DupMethod>
        <DupIn>All Recordings</DupIn>
        <Filter>1024</Filter>
        <RecProfile>Default</RecProfile>
        <RecGroup>Default</RecGroup>
        <StorageGroup>Default</StorageGroup>
        <PlayGroup>Default</PlayGroup>
        <AutoExpire>true</AutoExpire>
        <MaxEpisodes>0</MaxEpisodes>
        <MaxNewest>false</MaxNewest>
        <AutoCommflag>true</AutoCommflag>
        <AutoTranscode>false</AutoTranscode>
        <AutoMetaLookup>true</AutoMetaLookup>
        <AutoUserJob1>false</AutoUserJob1>
        <AutoUserJob2>false</AutoUserJob2>
        <AutoUserJob3>false</AutoUserJob3>
        <AutoUserJob4>false</AutoUserJob4>
        <Transcoder>0</Transcoder>
        <NextRecording>2013-05-25T01:00:00Z</NextRecording>
        <LastRecorded>2013-05-04T02:00:00Z</LastRecorded>
        <LastDeleted>2013-05-04T16:48:25Z</LastDeleted>
        <AverageDelay>0</AverageDelay>
    </RecRule>
```

Fails with:

<pre>
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971): org.springframework.http.converter.HttpMessageNotReadableException: Could not read JSON: Unrecognized field "FindDay" (class org.mythtv.services.api.dvr.RecRule), not marked as ignorable (47 known properties: , "LastDeleted", "Season", "ParentId", "LastRecorded", "AutoTranscode", "AverageDelay", "MaxNewest", "PlayGroup", "Inactive", "AutoMetaLookup", "AutoExpire", "SeriesId", "FindId" [truncated]])
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):  at [Source: java.util.zip.GZIPInputStream@415f1be0; line: 1, column: 582] (through reference chain: org.mythtv.services.api.dvr.RecRuleList["RecRuleList"]->org.mythtv.services.api.dvr.RecRules["RecRules"]->org.mythtv.services.api.dvr.RecRule["FindDay"]); nested exception is com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "FindDay" (class org.mythtv.services.api.dvr.RecRule), not marked as ignorable (47 known properties: , "LastDeleted", "Season", "ParentId", "LastRecorded", "AutoTranscode", "AverageDelay", "MaxNewest", "PlayGroup", "Inactive", "AutoMetaLookup", "AutoExpire", "SeriesId", "FindId" [truncated]])
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):  at [Source: java.util.zip.GZIPInputStream@415f1be0; line: 1, column: 582] (through reference chain: org.mythtv.services.api.dvr.RecRuleList["RecRuleList"]->org.mythtv.services.api.dvr.RecRules["RecRules"]->org.mythtv.services.api.dvr.RecRule["FindDay"])
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at org.springframework.http.converter.json.MappingJackson2HttpMessageConverter.readInternal(MappingJackson2HttpMessageConverter.java:126)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at org.springframework.http.converter.AbstractHttpMessageConverter.read(AbstractHttpMessageConverter.java:147)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:76)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:655)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:641)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:484)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:453)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:429)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at org.mythtv.services.api.dvr.impl.DvrTemplate.getRecordScheduleList(DvrTemplate.java:316)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at org.mythtv.service.dvr.RecordingRuleDownloadService.download(RecordingRuleDownloadService.java:158)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at org.mythtv.service.dvr.RecordingRuleDownloadService.onHandleIntent(RecordingRuleDownloadService.java:126)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at android.os.Handler.dispatchMessage(Handler.java:99)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at android.os.Looper.loop(Looper.java:137)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at android.os.HandlerThread.run(HandlerThread.java:60)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971): Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "FindDay" (class org.mythtv.services.api.dvr.RecRule), not marked as ignorable (47 known properties: , "LastDeleted", "Season", "ParentId", "LastRecorded", "AutoTranscode", "AverageDelay", "MaxNewest", "PlayGroup", "Inactive", "AutoMetaLookup", "AutoExpire", "SeriesId", "FindId" [truncated]])
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):  at [Source: java.util.zip.GZIPInputStream@415f1be0; line: 1, column: 582] (through reference chain: org.mythtv.services.api.dvr.RecRuleList["RecRuleList"]->org.mythtv.services.api.dvr.RecRules["RecRules"]->org.mythtv.services.api.dvr.RecRule["FindDay"])
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:579)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:672)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:906)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:328)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:226)
05-16 00:31:23.633: E/RecordingRuleDownloadService(5971):   at com.fasterxml.jackson.da
</pre>

**Comment by billmeek** [comment]
The Recording Rules screen now loads. I removed the Critical label from this issue,
but left it open to track the final solution. Let me know if you want it closed and an
new issue opened to track it.

**Comment by dmfrey** [comment]
Versioning the api should be tracked in the api issues. Let's open one over
there.

Should probably keep this open till we get the the next version of the api
released.

**Comment by billmeek** [comment]
Sorry for the delay in testing. I didn't expand the ellipses on the issues list, so
I didn't spot your requests.

8/22/2013, I'm running with this in pom.xml (I didn't change anything.)
    <mythtv.service.api-version>0.0.32</mythtv.service.api-version>

Let me know if that's not a proper test setup.

There is a new problem with enable/disable, but I'll open a new issue on that.
