### ISSUE TITLE
Swiping from the navigation page of the remote to the numbers gives an error.

### ISSUE THREAD

**Issue by misformichael** [MythTV-Clients/MythTV-Android-Frontend#141]
Running the front end on my galaxy nexus with 4.2.2.
Swiping from the navigation  page to the numbers page gives me an exception.

Get Status Error Could not read JSON: Unrecognized field "FrontendActionList" (class org.mythtv.services.api.frontend.F rontendActionList), not marked as ignorable (one known property: "ActionList"]) at [Source: Java.util.zip.GZIPInputStream@41 810020; line: 1, column: 25](through reference chain: org.mythtv.services.api.frontend.F rontendActionList["FrontendAction List"]); nested exception is com.fasterxml.jackson.databind.e xc.UnrecognizedPropertyExceptio n: Unrecognized field "FrontendActionList" (class org.mythtv.services.api.frontend.F rontendActionList), not marked as ignorable (one known property: "ActionList"]) at [Source: 
Java.util.zip.GZIPInputStream@41 810020; line: 1, column: 25](through reference chain: org.mythtv.services.api.frontend.F rorrtendActionList["FrontendAction List"])

**Comment by pot8oe** [comment]
This is a known issue. It was my mistake committing code with
FrontendActionList enabled.

Thanks,
Tom

-Tom

**Comment by misformichael** [comment]
Cool thanks; sorry: I couldn’t see it in the list of bugs, but probably wasn’t looking straight.
