### ISSUE TITLE
Not Connecting to Backend

### ISSUE THREAD

**Issue by goffa72** [MythTV-Clients/MythTV-Android-Frontend#144]
If I try and add a new home profile the frontend app gets stuck at retrieving the master back end details. I'm using version 1.10.1
I am doing the following
scan network - i get the following information
Mythbackend on htpc-desktop
http://10.0.0.1:6544/

after pressing save - Please wait - Retrieving Master Backend Details...
nothing seems to happen and the screen just blanks out. I have also tried using just 10.0.0.1 as the address.

entering the 10.0.0.1:6544 into the web browser opens the web services.

**Comment by dmfrey** [comment]
What happens if you enter the following in your browser?

http://10.0.0.1:6544/DVR/GetRecorderdList

Do you see XML showing all your recordings?

What version of mythbackend are you running?

**Comment by billmeek** [comment]
No response in 30 days, closing. However, there is a typo in
the previous command. Feel free to reopen and provide the
backend version (mythbackend --version) and answer if
XML was received. Thanks.

Use: http://10.0.0.1:6544/Dvr/GetRecordedList
