### ISSUE TITLE
Commit 778f3dd seems to require API revision 17 but manifest still specifies 14

### ISSUE THREAD

**Issue by tekrantz** [MythTV-Clients/MythTV-Android-Frontend#146]
From the online doumentation:

 public final FragmentManager getChildFragmentManager ()
Added in API level 17

And running it on my 4.0.3 device results in :

08-01 13:29:10.908: E/AndroidRuntime(13882): FATAL EXCEPTION: main
08-01 13:29:10.908: E/AndroidRuntime(13882): java.lang.NoSuchMethodError: org.mythtv.client.ui.dvr.RecordingsParentFragment.getChildFragmentManager
08-01 13:29:10.908: E/AndroidRuntime(13882):    at org.mythtv.client.ui.dvr.RecordingsParentFragment.onActivityCreated(RecordingsParentFragment.java:93)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:847)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1032)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at android.app.BackStackRecord.run(BackStackRecord.java:622)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1382)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at android.app.Activity.performStart(Activity.java:4478)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1941)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1993)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at android.app.ActivityThread.access$600(ActivityThread.java:127)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1159)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at android.os.Handler.dispatchMessage(Handler.java:99)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at android.os.Looper.loop(Looper.java:137)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at android.app.ActivityThread.main(ActivityThread.java:4512)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at java.lang.reflect.Method.invokeNative(Native Method)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at java.lang.reflect.Method.invoke(Method.java:511)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:978)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
08-01 13:29:10.908: E/AndroidRuntime(13882):    at dalvik.system.NativeStart.main(Native Method)

**Comment by dmfrey** [comment]
the support library has been updated to the latest. Can you re-test and verify this issue is still occurring?

**Comment by tekrantz** [comment]
The problem has been resolved.  Thank you.

I am having issues with the latest master though.  In particular playback never starts unless I come back later (after transcoding finishes) and request the episode again.  Would you like a bug report on this?  

Tim

**Comment by dmfrey** [comment]
Tim,

Can you capture the details and open a new ticket?

Thanks,
Dan
