### ISSUE TITLE
Recording Rules: Active/Inactive toggles if a changed rule is scrolled off then on screen.

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#150]
To duplicate:

<pre>
Choose an Active (1) rule
Switch that rule from Active to Inactive (0) on the Recording Rules screen
Scroll that rule off the screen
Scroll again to display the rule
Note that the rule is reset to Active
</pre>

LogCat with all Garbage collection messages deleted:

<pre>
08-23 00:05:01.206: V/NetworkHelper(7351): getMythServicesApi : enter
08-23 00:05:01.206: V/NetworkHelper(7351): getMythServicesApi : exit
08-23 00:05:01.466: V/RecordingRulesFragment(7351): onLoadFinished : enter
08-23 00:05:01.466: V/RecordingRulesFragment(7351): onLoadFinished : exit
08-23 00:05:05.976: V/NetworkHelper(7351): getMythServicesApi : enter
08-23 00:05:05.976: V/NetworkHelper(7351): getMythServicesApi : exit
08-23 00:05:06.336: V/ProgramGuideDownloadServiceNew(7409): process : programsAdded=294
08-23 00:05:06.336: V/ProgramGuideDownloadServiceNew(7409): process : exit
08-23 00:05:06.346: I/ProgramGuideDownloadServiceNew(7409): download : saving etag: "671d9794f389acc0db532c9eaa1491d1f9179b6c"
08-23 00:05:06.436: I/ProgramGuideDownloadServiceNew(7409): download : starting download for [43 of 112] 2013-08-26 21:00, end time=2013-08-27 00:00
08-23 00:05:06.536: V/ProgramGuideDownloadServiceNew(7409): download : etag=EtagInfoDelegate [id=52, endpoint=GET_PROGRAM_GUIDE, ETAG="500dcf31e68b0d8aade1412c5d459120a6978720", value="500dcf31e68b0d8aade1412c5d459120a6978720", dataId=43, date=2013-08-20T23:16:15.652-05:00, masterHostname=mc0, lastModified=2013-08-20T23:16:15.652-05:00]
08-23 00:05:06.536: V/ProgramGuideDownloadServiceNew(7409): download : next mythfilldatabase has passed
08-23 00:05:06.536: V/NetworkHelper(7409): getMythServicesApi : enter
08-23 00:05:06.536: V/NetworkHelper(7409): getMythServicesApi : exit
08-23 00:05:06.796: V/RecordingRulesFragment(7351): onLoadFinished : enter
08-23 00:05:06.796: V/RecordingRulesFragment(7351): onLoadFinished : exit
08-23 00:05:07.226: D/BounceScrollRunnableDefault(7351): start(4773.033), mBounceExtent:-109.0
08-23 00:05:07.226: D/BounceScrollRunnableDefault(7351): mBounceExtentCoef = -442.93747
08-23 00:05:07.656: I/ProgramGuideDownloadServiceNew(7409): download : GET_PROGRAM_GUIDE returned 200 OK
08-23 00:05:07.656: V/ProgramGuideDownloadServiceNew(7409): process : enter
08-23 00:05:07.656: V/ProgramGuideDownloadServiceNew(7409): process : saving program guide for host [mc0:http://192.168.1.204:6544/]
08-23 00:05:11.186: D/BounceScrollRunnableDefault(7351): start(-2217.8562), mBounceExtent:178.0
08-23 00:05:11.196: D/BounceScrollRunnableDefault(7351): mBounceExtentCoef = 205.81705
08-23 00:05:19.486: V/ProgramGuideDownloadServiceNew(7409): process : programsAdded=287
</pre>

Backend log messages:

<pre>
2013-08-23 00:03:04.084158 I [1155/2560] HttpServer51 servicehost.cpp:294 (ProcessRequest) - ServiceHost::ProcessRequest: DisableRecordSchedule : POST /Dvr/DisableRecordSchedule?RecordId=528 HTTP/
1.1^
2013-08-23 00:03:08.865624 I [1155/2560] HttpServer51 servicehost.cpp:294 (ProcessRequest) - ServiceHost::ProcessRequest: EnableRecordSchedule : POST /Dvr/EnableRecordSchedule?RecordId=528 HTTP/1.
1
</pre>

**Comment by dmfrey** [comment]
did some looking into this and it appears that the compondbutton that is backing the control is firing even when it is scrolling, instead of just on the toggle.  I am planning on moving that button off of the list anyway and it will become a part of a reusable popup that will eventually be used across guide, upcoming, recorded and the backend status view.

**Comment by billmeek** [comment]
If the newly disabled buttons are pressed, the following exception prints.
At 1st, I was pressing the 0/1 buttons just because users might still try
to. I had to repeat this as many as nine times before this fired.

Then, I just tried pressing a row on the left (title) side and on the 1st try
this fired.

Lines below are unfolded for readability.

<pre>
08-27 09:54:46.632: D/AndroidRuntime(25522): Shutting down VM
08-27 09:54:46.642: W/dalvikvm(25522): threadid=1: thread exiting with uncaught exception (group=0x40c5b1f8)
08-27 09:54:46.652: E/AndroidRuntime(25522): FATAL EXCEPTION: main
08-27 09:54:46.652: E/AndroidRuntime(25522): android.database.sqlite.SQLiteException: ambiguous column name: _id: ,
while compiling: SELECT channel.FREQUENCY_TABLE as channel_FREQUENCY_TABLE,
channel.FORMAT as channel_FORMAT,
recording_rule.MAX_NEWEST as recording_rule_MAX_NEWEST,
channel.CHAN_FILTERS as channel_CHAN_FILTERS,
channel.LAST_MODIFIED_DATE as channel_LAST_MODIFIED_DATE,
recording_rule.SERIES_ID as recording_rule_SERIES_ID,
channel.CHAN_NUM_FORMATTED as channel_CHAN_NUM_FORMATTED,
recording_rule.TIME as recording_rule_TIME,
channel._id as _id,
recording_rule.NEXT_RECORDING as recording_rule_NEXT_RECORDING,
recording_rule.CALLSIGN as recording_rule_CALLSIGN,
63 lines deleted...
channel.MODULATION as channel_MODULATION,
recording_rule._id as _id,
recording_rule.REC_PROFILE as recording_rule_REC_PROFILE,
chann
</pre>

LogCat stops at the line above
