### ISSUE TITLE
Dark remote icon/black text difficult to read on Navigation Menu

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#154]
See screenshot for remote example. The timestamps for the
four DVR screens are black and nearly impossible to read
against the dark Navigation Drawer.

The attached does not accurately reflect the Drawer on my
tablet. It appears even darker.

Running on: mythtv-android-frontend-1.10.1-414-g6745950

![dark-screenshot](https://f.cloud.github.com/assets/1831699/1030030/02771f30-0ea8-11e3-8d68-6bb8c608d2d7.jpg)

**Comment by pot8oe** [comment]
I believe I fixed all instances of dark text/icons and am closing this issue.

Reopen if any occurrences still exists.

**Comment by billmeek** [comment]
@pot8oe, much better, thanks. The triangle for selecting the active frontend is 
still black.

**Comment by pot8oe** [comment]
I'll have to check if the triangle is editable by us. It's part of the
android spinner control.

**Comment by pot8oe** [comment]
Pain in the ass but I was able to create a custom background drawable that closely resembles the default spinner but lighter in color.
