### ISSUE TITLE
Recording playback does not start

### ISSUE THREAD

**Issue by tekrantz** [MythTV-Clients/MythTV-Android-Frontend#155]
With all recent master versions (8/27/2013 and back) selecting a recording for playback does start the transcode.  I can verify this by running "top" on the backend machine AND I see the "processing" percent count appear and increment on the android frontend.  But playback never starts.  Running the 1.10 android frontend on the same android device against the same backend does play the recording.

Attached is the logcat from a session this morning.  I let the "processing" percent go to 3 percent before capturing the log.

Ok, I can't attach the file and it is too big to copy the text here.  I am ignorant of the appropriate manner in which to get this info into the "issue" so I will email it to Mr. Frey. Sorry about that.

**Comment by billmeek** [comment]
@tekrantz, please see if this matches #148. Especially the line, roughly in the
middle, of the LogCat that says:

<pre>
08-20 23:21:30.303: D/LiveStreamService(9462): onHandleIntent : exit, Recorded program not found
</pre>

**Comment by tekrantz** [comment]
No sir.  I do believe I saw that one also but my logcat has no instances of onHandleIntent : exit with a no program found…..

Tim
