### ISSUE TITLE
Parsing of Status.Load does not support comma as decimal separator

### ISSUE THREAD

**Issue by espenaf** [MythTV-Clients/MythTV-Android-Frontend#163]
My MythTV 0.26 installation spits out a Load status using comma as a decimal separator like this:

``` xml
 <Load avg1="0,6" avg2="0,7" avg3="0,67"/>
```

This is probably related to my linux box using the following locale settings:

LC_NUMERIC=nb_NO.UTF-8

Which uses comma as an decimal seperator rather than dot for en_US.UTF-8.

**Comment by pot8oe** [comment]
Do you run your android device with a similar locale?

**Comment by espenaf** [comment]
The Android device is not running with the same LC_NUMERIC locale, but en_US. 

The actual problem is the parser throws an NumberFormatException.

**Comment by dmfrey** [comment]
Opened myth-services-api issue 15 to track:
https://github.com/MythTV-Clients/MythTV-Service-API/issues/15

**Comment by dmfrey** [comment]
@espenaf do you need to run with differing locale's between devices?

I think it is safe to close this issue.

@billmeek we might need to put a message in the play store entry indicating that you should be running with the locale on both your phone and master backend.

I am also removing the bug label from this.

**Comment by billmeek** [comment]
@dmfrey, I'm a bit leery of adding instructions to the Play Store. Would
you be OK if locale was added to the FAQ? It would be the 2nd item on
the list.

**Comment by dmfrey** [comment]
@billmeek Yes, i do not believe this should be in the play store.  FAQ is perfect for this.

**Comment by billmeek** [comment]
Locale instructions added to my off-line copy. It's ready to push when
1.20.0 is released.

**Comment by billmeek** [comment]
Based on the comments in 227 and it's fix, the matching locale 'rule'
has been removed from the Wiki FAQ.
