### ISSUE TITLE
Processing percent not chaging as of commit ea72243

### ISSUE THREAD

**Issue by tekrantz** [MythTV-Clients/MythTV-Android-Frontend#164]
Just upgraded to commit ea722432fd574e047c453d0b5729ed9caeee4bac.

Pressing the "eyeball" on a recording starts transcoding and "Processing 0%" appears above the recording but never changes from that 0 percent. Changing to another recording and back even after 15 minutes still results in 0 percent.

**Comment by billmeek** [comment]
May need to define the expected way the % changes. Previously,
when it would keep updating. If the show or episode was changed
and the user returned to the episode that was in progress, the %
would be updated in a few seconds.

Now, there may be one update and nothing else until the user changes
from the show/episode and returns to it. Let me know if there should be
a new ticket or if this should be worked here. Reopening for now.
Tested with recordings made on a Master and on a Slave Backend.
