### ISSUE TITLE
Recordings: Delete last recording doesn't remove banner and All entry until refresh

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#166]
To Duplicate:

```
Select a program with only one episode
Press Menu/Delete confirm Delete
```

Note that neither the banner for the title nor the episode is
removed from the screen. Also, the episode remains in the
"All" listing. Changing to another title and returning to the
newly deleted title has the same result.

Pressing the refresh icon deletes the title's banner and episode,
however the "All" listing still displays the episode.

**Comment by dmfrey** [comment]
Did you get the Toast message indicating that the episode was deleted?

On Tue, Sep 10, 2013 at 2:27 PM, billmeek notifications@github.com wrote:

> To Duplicate:
> 
> Select a program with only one episode
> Press Menu/Delete confirm Delete
> 
> Note that neither the banner for the title nor the episode is
> removed from the screen. Also, the episode remains in the
> "All" listing. Changing to another title and returning to the
> newly deleted title has the same result.
> 
> Pressing the refresh icon deletes the title's banner and episode,
> however the "All" listing still displays the episode.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/166
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
Yes, the Toast message said "Episode deleted!" Just retried on my
production backend. Same result. Also, in the backend log, there
was:

```
2013-09-10 15:11:07.245345 I [2319/8809] HttpServer80 servicehost.cpp:294 (ProcessRequest) - ServiceHost::ProcessRequest: RemoveRecorded : GET /Dvr/RemoveRecorded?ChanId=1021&StartTime=2013-04-28T23%3A00%3A00 HTTP/1.1^M

2013-09-10 15:11:07.247106 I [2319/8809] HttpServer80 httprequest.cpp:244 (SendResponse) - HTTPRequest::SendResponse(xml/html) () :200 OK -> 192.168.1.231: 4
```

Also looked in the frontend and the episode is gone.

**Comment by billmeek** [comment]
If you could get rid of the "Recorded program not found" Toast and
Log.d message this would be perfect (I know how to remove them,
but not how to leave them in but prevent them from printing.)

Not reopening the issue.

**Comment by dmfrey** [comment]
I will remove the toast messages. I want them all gone anyway, except for a
few occurrences.

Which Log.d are you referring to?

**Comment by billmeek** [comment]
I didn't revert the fix to retest, but the Log.d is:

```
src/org/mythtv/service/content/LiveStreamService.java Line  83
```

has the only  "Recorded program not found" left that I can find. I didn't touch it
because I don't know if it's used elsewhere.
