### ISSUE TITLE
App Crash when backend not accessible

### ISSUE THREAD

**Issue by pot8oe** [MythTV-Clients/MythTV-Android-Frontend#167]
Reproduce:
1. Connected via ssh tunnel so MAF was configured to connect to a home profile with address localhost:6544
2. Returned home and started the app.

Only work around is to recreate the ssh tunnel.

Full Stack Trace:

09-10 20:35:47.680: E/AndroidRuntime(27101): FATAL EXCEPTION: AsyncTask #1
09-10 20:35:47.680: E/AndroidRuntime(27101): java.lang.RuntimeException: An error occured while executing doInBackground()
09-10 20:35:47.680: E/AndroidRuntime(27101):    at android.os.AsyncTask$3.done(AsyncTask.java:299)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at java.util.concurrent.FutureTask.run(FutureTask.java:239)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at java.lang.Thread.run(Thread.java:841)
09-10 20:35:47.680: E/AndroidRuntime(27101): Caused by: org.mythtv.services.api.MythServiceApiRuntimeException: java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 6544): connect failed: ECONNREFUSED (Connection refused); nested exception is java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 6544): connect failed: ECONNREFUSED (Connection refused)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at org.mythtv.services.api.connect.MythAccessFactory.isServerReachable(MythAccessFactory.java:136)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at org.mythtv.service.util.NetworkHelper.isMasterBackendConnected(NetworkHelper.java:114)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at org.mythtv.client.ui.navigationDrawer.ProfileRow$ConnectBackendTask.doInBackground(ProfileRow.java:281)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at org.mythtv.client.ui.navigationDrawer.ProfileRow$ConnectBackendTask.doInBackground(ProfileRow.java:1)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at android.os.AsyncTask$2.call(AsyncTask.java:287)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at java.util.concurrent.FutureTask.run(FutureTask.java:234)
09-10 20:35:47.680: E/AndroidRuntime(27101):    ... 4 more
09-10 20:35:47.680: E/AndroidRuntime(27101): Caused by: java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 6544): connect failed: ECONNREFUSED (Connection refused)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at libcore.io.IoBridge.connect(IoBridge.java:114)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at java.net.Socket.connect(Socket.java:842)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at libcore.net.http.HttpConnection.<init>(HttpConnection.java:76)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at libcore.net.http.HttpConnection.<init>(HttpConnection.java:50)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:340)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:87)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at libcore.net.http.HttpConnection.connect(HttpConnection.java:128)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:316)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at libcore.net.http.HttpEngine.connect(HttpEngine.java:311)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:282)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at org.mythtv.services.api.connect.MythAccessFactory.isServerReachable(MythAccessFactory.java:133)
09-10 20:35:47.680: E/AndroidRuntime(27101):    ... 9 more
09-10 20:35:47.680: E/AndroidRuntime(27101): Caused by: libcore.io.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at libcore.io.Posix.connect(Native Method)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:85)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at libcore.io.IoBridge.connectErrno(IoBridge.java:127)
09-10 20:35:47.680: E/AndroidRuntime(27101):    at libcore.io.IoBridge.connect(IoBridge.java:112)
09-10 20:35:47.680: E/AndroidRuntime(27101):    ... 24 more
09-10 20:35:48.361: E/WindowManager(27101): Activity org.mythtv.client.ui.NavigationDrawerActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{41ba71b0 V.E..... R....... 0,0-1026,486} that was originally added here
09-10 20:35:48.361: E/WindowManager(27101): android.view.WindowLeaked: Activity org.mythtv.client.ui.NavigationDrawerActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{41ba71b0 V.E..... R....... 0,0-1026,486} that was originally added here
09-10 20:35:48.361: E/WindowManager(27101):     at android.view.ViewRootImpl.<init>(ViewRootImpl.java:355)
09-10 20:35:48.361: E/WindowManager(27101):     at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:239)
09-10 20:35:48.361: E/WindowManager(27101):     at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:69)
09-10 20:35:48.361: E/WindowManager(27101):     at android.app.Dialog.show(Dialog.java:281)
09-10 20:35:48.361: E/WindowManager(27101):     at org.mythtv.client.ui.navigationDrawer.ProfileRow$ConnectBackendTask.onPreExecute(ProfileRow.java:269)
09-10 20:35:48.361: E/WindowManager(27101):     at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:586)
09-10 20:35:48.361: E/WindowManager(27101):     at android.os.AsyncTask.execute(AsyncTask.java:534)
09-10 20:35:48.361: E/WindowManager(27101):     at org.mythtv.client.ui.navigationDrawer.ProfileRow$ProfileToggleCheckChangedListener.onCheckedChanged(ProfileRow.java:74)
09-10 20:35:48.361: E/WindowManager(27101):     at org.mythtv.client.ui.navigationDrawer.ProfileRow.backendConnectionUpdate(ProfileRow.java:150)
09-10 20:35:48.361: E/WindowManager(27101):     at org.mythtv.client.ui.NavigationDrawerActivity.onResume(NavigationDrawerActivity.java:282)
09-10 20:35:48.361: E/WindowManager(27101):     at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1251)
09-10 20:35:48.361: E/WindowManager(27101):     at android.app.Activity.performResume(Activity.java:5211)
09-10 20:35:48.361: E/WindowManager(27101):     at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2908)
09-10 20:35:48.361: E/WindowManager(27101):     at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2947)
09-10 20:35:48.361: E/WindowManager(27101):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2303)
09-10 20:35:48.361: E/WindowManager(27101):     at android.app.ActivityThread.access$600(ActivityThread.java:142)
09-10 20:35:48.361: E/WindowManager(27101):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1285)
09-10 20:35:48.361: E/WindowManager(27101):     at android.os.Handler.dispatchMessage(Handler.java:99)
09-10 20:35:48.361: E/WindowManager(27101):     at android.os.Looper.loop(Looper.java:137)
09-10 20:35:48.361: E/WindowManager(27101):     at android.app.ActivityThread.main(ActivityThread.java:5270)
09-10 20:35:48.361: E/WindowManager(27101):     at java.lang.reflect.Method.invokeNative(Native Method)
09-10 20:35:48.361: E/WindowManager(27101):     at java.lang.reflect.Method.invoke(Method.java:525)
09-10 20:35:48.361: E/WindowManager(27101):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:974)
09-10 20:35:48.361: E/WindowManager(27101):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:790)
09-10 20:35:48.361: E/WindowManager(27101):     at dalvik.system.NativeStart.main(Native Method)
09-10 20:35:48.451: E/AndroidRuntime(27122): FATAL EXCEPTION: IntentService[BackendStatusService]
09-10 20:35:48.451: E/AndroidRuntime(27122): org.mythtv.services.api.MythServiceApiRuntimeException: java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 6544): connect failed: ECONNREFUSED (Connection refused); nested exception is java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 6544): connect failed: ECONNREFUSED (Connection refused)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at org.mythtv.services.api.connect.MythAccessFactory.isServerReachable(MythAccessFactory.java:136)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at org.mythtv.service.status.v26.BackendStatusHelperV26.process(BackendStatusHelperV26.java:99)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at org.mythtv.service.status.BackendStatusService.onHandleIntent(BackendStatusService.java:55)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at android.os.Handler.dispatchMessage(Handler.java:99)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at android.os.Looper.loop(Looper.java:137)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at android.os.HandlerThread.run(HandlerThread.java:61)
09-10 20:35:48.451: E/AndroidRuntime(27122): Caused by: java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 6544): connect failed: ECONNREFUSED (Connection refused)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at libcore.io.IoBridge.connect(IoBridge.java:114)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at java.net.Socket.connect(Socket.java:842)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at libcore.net.http.HttpConnection.<init>(HttpConnection.java:76)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at libcore.net.http.HttpConnection.<init>(HttpConnection.java:50)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at libcore.net.http.HttpConnection$Address.connect(HttpConnection.java:340)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at libcore.net.http.HttpConnectionPool.get(HttpConnectionPool.java:87)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at libcore.net.http.HttpConnection.connect(HttpConnection.java:128)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at libcore.net.http.HttpEngine.openSocketConnection(HttpEngine.java:316)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at libcore.net.http.HttpEngine.connect(HttpEngine.java:311)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at libcore.net.http.HttpEngine.sendSocketRequest(HttpEngine.java:290)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at libcore.net.http.HttpEngine.sendRequest(HttpEngine.java:240)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:282)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at org.mythtv.services.api.connect.MythAccessFactory.isServerReachable(MythAccessFactory.java:133)
09-10 20:35:48.451: E/AndroidRuntime(27122):    ... 6 more
09-10 20:35:48.451: E/AndroidRuntime(27122): Caused by: libcore.io.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at libcore.io.Posix.connect(Native Method)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:85)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at libcore.io.IoBridge.connectErrno(IoBridge.java:127)
09-10 20:35:48.451: E/AndroidRuntime(27122):    at libcore.io.IoBridge.connect(IoBridge.java:112)
09-10 20:35:48.451: E/AndroidRuntime(27122):    ... 21 more

**Comment by pot8oe** [comment]
I can also recreate on a new device and by manually creating a home profile pointing to localhost. The app will crash attempting to contact the masterbackend and then crash on subsequent application starts.

I assume manually creating a profile to any unreachable address will reproduce this. 

I'm going to elevate this to critical because there is no easy work around to choose a second valid profile. The app becomes unusable until the selected profile's backend is reachable.

-Tom

**Comment by dmfrey** [comment]
I am adding a catch in there for the MythtvServiceApiRuntimeException and will return false if raised.

But should this also reset any connected backends??
