### ISSUE TITLE
0.27 AddLiveStream using -1 for parameters that aren't to be sent

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#168]
Discovered while reproducing #164.

@dmfrey, please review. I changed the 0.27 MAF code to use nulls,
but when I tried 0.26, Ellipse showed an error. So I left 0.26 as -1.

Looking at the backend log after using: mythbackend --setverbose upnp,system
The following is seen. Note the -1 values.

```
GET /Content/AddLiveStream?FileName=2117_20130719030000.mpg&HostName=mc0&MaxSegments=-1&Width=-1&Height=540&Bitrate=1000000&AudioBitrate=128000&SampleRate=48000
```

Probably a case where the backend should either take the absolute value of
a parameter, range check it  or return a 400 response.

Unfortunately, this will cause the backend to create one HUGE file. In my case
over 100GB which caused all old recordings to be expired and a new one to
fail to finish recording. (only my test backend, no harm, no foul)

Also noted that the Default (null) storage group is always used.

**Comment by tekrantz** [comment]
I noticed the same behaviour.  My file went over 500GB, filled my drive and cause me to miss races 5 and 6 of the America's cup (sad face).
