### ISSUE TITLE
NullPointerException when starting playback

### ISSUE THREAD

**Issue by Prefect47** [MythTV-Clients/MythTV-Android-Frontend#17]
I often get the NullPointerException dialog every time I start a recording. Have to force stop the app to play another one.

Best guess is that it happens if the MythTV activity has died and I go back into the recordings list to start playback.

**Comment by dmfrey** [comment]
Which player are you using?  The default one in Android is not great.  We have been testing with BS Player Lite.

**Comment by Prefect47** [comment]
Didn't see this when I played around now so I'm closing the issue.
