### ISSUE TITLE
0.27 MythMote Fatal Exception, any keypress

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#170]
To Duplicate:

```
Select the MythMote icon
Press any key (I actually only tested Enter and Down)
```

Exception fires.

In the backend log, only: SendAction : /Frontend is seen,
no Action=Enter etc. The backend returns a 404 error.

```
09-12 23:30:32.448: V/MythmoteActivity(4978): onCreate : enter
09-12 23:30:32.448: I/AbstractMythtvFragmentActivity(4978): onCreate : enter
09-12 23:30:32.448: V/AbstractMythtvFragmentActivity(4978): onCreate : enter
09-12 23:30:32.448: V/AbstractMythtvFragmentActivity(4978): setupActionBar : enter
09-12 23:30:32.458: V/AbstractMythtvFragmentActivity(4978): setupActionBar : exit
09-12 23:30:32.458: V/MythmoteActivity(4978): MythmoteActivity.setupActionBar : enter
09-12 23:30:32.458: V/MythmoteActivity(4978): MythmoteActivity.setupActionBar : exit
09-12 23:30:32.458: V/AbstractMythtvFragmentActivity(4978): onCreate : device hxw - 752 x 1280
09-12 23:30:32.458: V/AbstractMythtvFragmentActivity(4978): onCreate : exit
09-12 23:30:32.458: V/AbstractMythtvFragmentActivity(4978): setupActionBar : enter
09-12 23:30:32.458: V/AbstractMythtvFragmentActivity(4978): setupActionBar : exit
09-12 23:30:32.458: V/MythmoteActivity(4978): MythmoteActivity.setupActionBar : enter
09-12 23:30:32.458: V/MythmoteActivity(4978): MythmoteActivity.setupActionBar : exit
09-12 23:30:32.458: I/AbstractMythtvFragmentActivity(4978): onCreate : exit
09-12 23:30:32.478: V/MythmoteActivity(4978): onCreate : exit
09-12 23:30:32.658: V/AbstractMythtvFragmentActivity(4978): onCreateOptionsMenu : enter
09-12 23:30:32.658: V/MenuHelper(4978): helpSubMenu : enter
09-12 23:30:32.658: V/MenuHelper(4978): helpSubMenu : exit
09-12 23:30:32.658: V/AbstractMythtvFragmentActivity(4978): onCreateOptionsMenu : exit
09-12 23:30:32.718: D/OpenGLRenderer(4978): Flushing caches (mode 0)
09-12 23:30:32.948: V/BackendStatusFragment(4978): onStop : enter
09-12 23:30:32.948: V/BackendStatusFragment(4978): onStop : exit
09-12 23:30:37.638: D/SendActionTask(4978): doInBackground : enter
09-12 23:30:37.758: I/dalvikvm(4978): Jit: resizing JitTable from 4096 to 8192
09-12 23:30:37.858: W/RestTemplate(4978): GET request for "http://192.168.1.204:6544/Frontend/SendAction?Action=SELECT&Width=0&Height=0" resulted in 404 (Not Found); invoking error handler
09-12 23:30:37.858: W/dalvikvm(4978): threadid=15: thread exiting with uncaught exception (group=0x40c401f8)
09-12 23:30:37.868: E/AndroidRuntime(4978): FATAL EXCEPTION: AsyncTask #2
09-12 23:30:37.868: E/AndroidRuntime(4978): java.lang.RuntimeException: An error occured while executing doInBackground()
09-12 23:30:37.868: E/AndroidRuntime(4978):     at android.os.AsyncTask$3.done(AsyncTask.java:278)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at java.util.concurrent.FutureTask.run(FutureTask.java:137)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at java.lang.Thread.run(Thread.java:856)
09-12 23:30:37.868: E/AndroidRuntime(4978): Caused by: org.mythtv.services.api.MythServiceApiRuntimeException: org.springframework.web.client.HttpClientErrorException: 404 Not Found; nested exception is org.springframework.web.client.HttpClientErrorException: 404 Not Found
09-12 23:30:37.868: E/AndroidRuntime(4978):     at org.mythtv.services.api.MythServicesErrorHandler.handleError(MythServicesErrorHandler.java:39)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at org.springframework.web.client.RestTemplate.handleResponseError(RestTemplate.java:524)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:481)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:453)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:429)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at org.mythtv.services.api.v027.impl.FrontendTemplate.sendAction(FrontendTemplate.java:121)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at org.mythtv.service.frontends.SendActionTask.doInBackground(SendActionTask.java:73)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at org.mythtv.service.frontends.SendActionTask.doInBackground(SendActionTask.java:1)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at android.os.AsyncTask$2.call(AsyncTask.java:264)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
09-12 23:30:37.868: E/AndroidRuntime(4978):     ... 5 more
09-12 23:30:37.868: E/AndroidRuntime(4978): Caused by: org.springframework.web.client.HttpClientErrorException: 404 Not Found
09-12 23:30:37.868: E/AndroidRuntime(4978):     at org.springframework.web.client.DefaultResponseErrorHandler.handleError(DefaultResponseErrorHandler.java:76)
09-12 23:30:37.868: E/AndroidRuntime(4978):     at org.mythtv.services.api.MythServicesErrorHandler.handleError(MythServicesErrorHandler.java:37)
09-12 23:30:37.868: E/AndroidRuntime(4978):     ... 14 more
```

**Comment by pot8oe** [comment]
The error is on port 6544 but frontend service runs on port 6547.

According to the mythtv wiki there is a parameter "File" that is required. 
http://www.mythtv.org/wiki/Frontend_Service#SendAction

The MythTV Services API 0.27 has a "Value" parameter that is always NULL and not being sent.

@billmeek Can you try the following and let me know if any work. All three work on my 0.26 frontend.
curl "http://192.168.1.204:6547/Frontend/SendAction?Action=SELECT&Width=0&Height=0"
curl "http://192.168.1.204:6547/Frontend/SendAction?Action=SELECT&FILE=empty&Width=0&Height=0"
curl "http://192.168.1.204:6547/Frontend/SendAction?Action=SELECT&VALUE=empty&Width=0&Height=0"

-Tom

**Comment by billmeek** [comment]
@pot8oe, none of them work, because the IP is for my backend that
has no frontend running. _Which I should have noticed_. If I change the
address to end in .200 where I have a frontend running, all three work
fine.

When I reran the test this morning, I didn't get an exception, but no
commands were sent to my running FE and I didn't see any messages
coming into the FE watching with the tshark protocol tool.

I did spot this in LogCat:

```
09-13 08:37:18.970: E/FrontendsRow(10722): Frontend selected but no frontends in ArrayList
```

And, even though I don't usually select a frontend, I did tap on the only choice
and then use the Remote icon. Still no control and no Exception.

I don't see how the URL is passed to the 0.27 Services API code. 

```
src/main/java/org/mythtv/services/api/v026/FrontendOperations.java: ResponseEntity<Bool> sendAction( String frontedApiUrlBase, String action, String file, int width, int height ) throws MythServiceApiRuntimeException;

src/main/java/org/mythtv/services/api/v027/FrontendOperations.java: ResponseEntity<Bool> sendAction(String action, String value, Integer width, Integer height, ETagInfo etagInfo) throws MythServiceApiRuntimeException;
```

**Comment by tafypz** [comment]
@billmeek 
the service api code for 0.27 is now auto generated from the wsdl and xsd,
The frontend endpoint wsdl doesn't contain a parameter frontendApiURL so it is generated. 
So using this endpoint requires you to have the connection already established to the frontend so that it can send the request to it.

**Comment by dmfrey** [comment]
i think i know what I have to do in this case.  I will take a look tonight.
 I believe my service is passing in the location profile and getting access
with the url contained in the location profile, instead of passing in the
frontend url.  This one needs to be handled differently than any other
service post v1 refactor.

On Fri, Sep 13, 2013 at 10:09 AM, Sebastien Astie
notifications@github.comwrote:

> @billmeek https://github.com/billmeek
> the service api code for 0.27 is now auto generated from the wsdl and xsd,
> The frontend endpoint wsdl doesn't contain a parameter frontendApiURL so
> it is generated.
> So using this endpoint requires you to have the connection already
> established to the frontend so that it can send the request to it.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/170#issuecomment-24396880
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by pot8oe** [comment]
I have just received a similar error. The NavBar frontends list remembered
all found frontends. I closed the selected frontend and then went to
Mythmote and tried to control it. Crashed MythMote activity and dropped me
back to MythTV activity. We need to provide better feedback to the user and
not fail out.

-Tom

**Comment by billmeek** [comment]
@dmfrey, tests A-OK, would you like me to change the lines like:

```
Log.w( TAG, "process : Master Backend '" + mLocationProfile.getHostname() + "' is unreachable" ); 
```

to refer to the Frontend and print the URL used?

**Comment by dmfrey** [comment]
yes, go ahead

On Fri, Sep 13, 2013 at 1:31 PM, billmeek notifications@github.com wrote:

> @dmfrey https://github.com/dmfrey, tests A-OK, would you like me to
> change the lines like:
> 
> Log.w( TAG, "process : Master Backend '" + mLocationProfile.getHostname() + "' is unreachable" );
> 
> to refer to the Frontend and print the URL used?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/170#issuecomment-24410909
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey
