### ISSUE TITLE
Tracking Issue: Handle invalid timestamps passed to MAF by MythTV (was #107)

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#171]
Opening this as a bug. #107 has gotten too old and has too many 
comments to easily follow. 

MAF needs to decide how to treat invalid timestamps caused by
corrupt data in the MythTV DB.

**Comment by billmeek** [comment]
The original workaround put 0 timestamps in the MAF db and set IN_ERROR
in the db. This was changed in e920f7a and now every time a corrupt episode
is loaded, a new record is created (I currently have 16 for 1 show.) The failed
episode is not displayed on Recordings.

https://github.com/MythTV-Clients/MythTV-Android-Frontend/blob/master/src/org/mythtv/db/dvr/ProgramDaoHelper.java#L432

**Comment by dmfrey** [comment]
Recent database changes now make it impossible for multiple entries to make it into the db for a given program or recording record.

These tables are created with unique constraints and they are set to replace the current entry when a conflict is raised.  Also, foreign key constraints are also enabled and they are set to cascade delete as well.

**Comment by billmeek** [comment]
Tested with a blank MAF DB. The episode didn't display.
There was an entry in the MAF DB.

Pressed the refresh icon to get a new  copy of the recorded
shows and there was still only one entry in the MAF DB. And
it still didn't display.

Off-line of the Wiki has been updated and is ready for release.

Closing the issue.

**Comment by billmeek** [comment]
Just discovered a show with an invalid  timestamp shows up in
the All category. It doesn't show up in the list of shows, but it's
coverart, description etc. is displayed. No doubt a clever design
choice that helps users locate bad data. The Wiki will reflect this.
Really!

**Comment by dmfrey** [comment]
That wasn't my intent :-)

I can leave it that way if you want.

Does that close the issue?

**Comment by billmeek** [comment]
It was already closed. I hadn't checked the All category when
testing. Let's just leave it in. The 1st MAF Easter Egg.

**Comment by onley** [comment]
I hate to bring up an old thread but I just installed 1.10.1 and am having this problem with a 0.26 backend on Debian 7 and have not yet been able to find a solution. If I call getrecordedlist from a browser I get an 1.2MB file with all my recording information but the android never shows any recordings despite claiming to sync successfully.

I have used mythtv for over 10 years and have recordings that old on my system. I have changed sources at least 3 times and have many recordings that were recorded on channels that I no longer have sources for but I can still watch them. 

I would like to use this app but do not want to drop 10 years of favorite recordings to do so.

**Comment by billmeek** [comment]
Before going further, I'd suggest getting the Beta version of 1.20.6 available at:
https://play.google.com/apps/testing/org.mythtv . If that doesn't help, please open
a new issue. The same symptom can show  up, for example, with invalid UTF
characters. Thanks.
