### ISSUE TITLE
1.20.0 Android LInt

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#173]
There are 9 errors and 263 warnings at the time this issue 
was created.

Although commenting out the following reduces the errors to 3. I'm loathe to
commit this because I don't know its affect. I did search for RecordingsActivity
and found every match was a comment (except for the Manifest.)

```
git grep RecordingsActivity - returns all commented lines
AndroidManifest.xml:            android:name=".client.ui.dvr.RecordingsActivity"
```

Opening as a design discussion. Suggesting that prior to release, there
should be 0 errors.

**Comment by dmfrey** [comment]
If there are any errors, the app will not run. Can you send me the errors?

**Comment by billmeek** [comment]
The remaining are "Unexpected namespace" the 1st one is this:

```
        <TableLayout
            xmlns:android="http://schemas.android.com/apk/res/android"
            android:id="@+id/TableLayoutLocationEditor"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:stretchColumns="0,1" >
```

**Comment by billmeek** [comment]
Sorry, my control key is sticking. The file for the above is:

```
res/layout/preference_playback_profile_editor.xml
```

**Comment by dmfrey** [comment]
When I look at the Problems tab in Eclipse, I only see 34 Warnings and no Errors.  Where are you seeing all these errors and warnings?

**Comment by billmeek** [comment]
It's in the Java Perspective, Window menu, 2nd to last line 
"Run Android Lint".  Here's the remaining three errors:

```
Description Resource    Path    Location    Type
Unexpected namespace prefix "xmlns" found for tag TableLayout   preference_playback_profile_editor.xml  /MythTV-Android-Frontend/res/layout line 30 Android Lint Problem
Unexpected namespace prefix "xmlns" found for tag TableLayout   preference_location_profile_editor.xml  /MythTV-Android-Frontend/res/layout line 30 Android Lint Problem
Unexpected namespace prefix "xmlns" found for tag TextView  program_row.xml /MythTV-Android-Frontend/res/layout line 43 Android Lint Problem
```

Odd thing is, when I commented out the:

```
AndroidManifest.xml:            android:name=".client.ui.dvr.RecordingsActivity"
```

"error" and then reverted the fix. It didn't come back. That's after multiple Project
Cleans and restarting Eclipse. I'm not sure how good this tool is (value vs. time.)
And multiple re-runs of Android Lint.

**Comment by billmeek** [comment]
There's still one error in Android Lint. I'll suggest that after
this one is removed, we should consider this closed. I'm 
sensing from recent email that release is imminent and 
shouldn't work on the 173 errors (93 of which are unused
strings we talked about.) Especially with Michael working 
on the German translations.

```
Class referenced in the layout file, org.mythtv.client.ui.dvr.ProgramGroupsListFragment, was not found in the project or the libraries
```

```
git grep org.mythtv.client.ui.dvr.ProgramGroupsListFragment
res/layout-large/activity_dvr_program_groups.xml:    <fragment android:name="org.mythtv.client.ui.dvr.ProgramGroupsListFragment"
res/layout/activity_dvr_program_groups.xml:        android:name="org.mythtv.client.ui.dvr.ProgramGroupsListFragment"
```
