### ISSUE TITLE
Add German translation

### ISSUE THREAD

**Issue by tensberg** [MythTV-Clients/MythTV-Android-Frontend#174]
I am currently working on translating the strings.xml to German. I can create a pull request once I am ready if you are interested.

**Comment by dmfrey** [comment]
Michael,

Thank you very much for this.  Also, you may find some hard coded strings
in the code. We are trying to be good about always putting them in the
strings.xml, but sometimes we miss them.  Please feel free to move them
into the original strings.xml and create your respective translations.

Dan

On Sat, Sep 14, 2013 at 3:00 PM, Michael Koch notifications@github.comwrote:

> I am currently working on translating the strings.xml to German. I can
> create a pull request once I am ready if you are interested.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/174
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
Michael,

I've been running Lint on the application. It found 37 hard coded strings
and I've added 31 of them to the strings.xml file (some strings are used
in multiple places.)

If you haven't started addressing the hard coded strings yet, I'll probably push
about 1600 UTC on 9/15. Everything I added is at the end of the existing file.

If you already have started, I'll just revert my changes. Please let me know
which you prefer. Thank you.

**Comment by tensberg** [comment]
Thanks for your fast responses.

> If you haven't started addressing the hard coded strings yet, I'll probably push about 1600 UTC on 9/15.

Please do this. While I feel pretty comfortable with Java and Eclipse, my copy of "Android in Action" is still sitting unread in my bookshelf. I'd therefore think that it is better if you do the code changes.

**Comment by billmeek** [comment]
Michael;

If you click on the commit above, you'll see the changes made to the
default strings.xml. There were a couple of typos in the existing file
but most of the work is at the bottom.

**Comment by tensberg** [comment]
When testing the translations I found some more strings which are hardcoded in the source. I've started moving them to the resources in my fork. Could you review my commit 45f6cf7 if I've done everything OK? If yes, I will also change the other places I find and send a pull request afterwards.

**Comment by billmeek** [comment]
Looks good to me (but mostly I do the Wiki and testing.) I also loaded
your strings.xml. It works great! Unfortunately I _barely_ speak the language.

I added a new Wiki page to help others that might attempt what you've done.
https://github.com/MythTV-Clients/MythTV-Android-Frontend/wiki/_Translation-Process

Vielen Dank!

**Comment by tensberg** [comment]
> Vielen Dank!

Gerne :smiley:

I've read the wiki page and think that it is very helpful. One question: I can't find a way to add a label ( _translations_ ) to an issue. I guess it is only possible for project members.

**Comment by billmeek** [comment]
Thanks for spotting that! The Wiki has been updated.

**Comment by tensberg** [comment]
I've completed the translations of the current master as far as I could see in my tests and created a pull request.

If there are more string changes before the next release, please post here so that I can update the translations.

**Comment by billmeek** [comment]
@tensberg, Thank you Michael! I'm closing this issue, so that it shows
up in the release notes as fixed. But I like your idea of reporting any string
changes here (for 1.20.x.)

**Comment by billmeek** [comment]
Commit      b91427a added 2 new strings.

**Comment by billmeek** [comment]
Michael;

When the official 1.20.0 release goes out, there will be mention of the German translation
as a new feature. You should certainly get credit for all your work.

Would you like to be mentioned by name in the Play Store text? I'd only do so with your
permission.

**Comment by dmfrey** [comment]
Michael,

If you are interested, we will also have to see about setting you up access
to the Google Play Store Developer Console so that you can translate the
Play Store listing to German as well.

Thanks for your help.

Dan

On Thu, Oct 10, 2013 at 10:48 AM, billmeek notifications@github.com wrote:

> Michael;
> 
> When the official 1.30.0 release goes out, there will be mention of the
> German translation
> as a new feature. You should certainly get credit for all your work.
> 
> Would you like to be mentioned by name in the Play Store text? I'd only do
> so with your
> permission.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/174#issuecomment-26059971
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by tensberg** [comment]
@billmeek 

> Would you like to be mentioned by name in the Play Store text?

Gladly, but only if it is clear that I only contributed the translation. You all deserve the credit for all the great work.

@dmfrey 

> we will also have to see about setting you up access to the Google Play
> Store Developer Console so that you can translate the Play Store listing
> to German as well.

Yes, I could do that. I haven't used the Play Store Console so far, but I'd sure be interested to give it a go. Don't know if I have time for it in the next one or two weeks, though.

**Comment by dmfrey** [comment]
Michael,

Can you send me your gmail off list and I can add you to the Developer
Console.  It is very easy to add translations (it seems).  They duplicate
the current store listing, and I believe you just select which language you
would like to translate for.

Speaking of translations...One of the items the Developer Console
recommends is to translate images as well as text.  Since you have been
through the app, are there any images that you would recommend
internationalizing?  Just something to think about going forward.

Thanks
Dan

On Thu, Oct 10, 2013 at 2:22 PM, Michael Koch notifications@github.comwrote:

> @billmeek https://github.com/billmeek
> 
> Would you like to be mentioned by name in the Play Store text?
> 
> Gladly, but only if it is clear that I only contributed the translation.
> You all deserve the credit for all the great work.
> 
> @dmfrey https://github.com/dmfrey
> 
> we will also have to see about setting you up access to the Google Play
> Store Developer Console so that you can translate the Play Store listing
> to German as well.
> 
> Yes, I could do that. I haven't used the Play Store Console so far, but
> I'd sure be interested to give it a go. Don't know if I have time for it in
> the next one or two weeks, though.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/174#issuecomment-26078142
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by tensberg** [comment]
I finally got around to translate the Play Store texts to German. I have just published the changes through the Play Developer Console. Now I am curious if there will be any feedback on the translation.

The Play Store description links to the Wiki in some places for further information. I think translating the Wiki pages would only be worth it if there is actual demand by the users.

I think maintaining the Play Store texts in the GitHub repository would help translators to keep the translations updated. I'll open a separate issue for this for discussion.

**Comment by billmeek** [comment]
Thanks for the  pull request.  There is a new menu item: "Release Notes"
Michael, what is the correct German translation?

**Comment by tensberg** [comment]
> There is a new menu item: "Release Notes"
> Michael, what is the correct German translation?

Good question. Like with many computer terms I am so used to the English term that I am not sure what is commonly used in German translations. The literal translation sounds awkward, and the translations from dict.leo.org also sound pretty uncommon to me.

I found a page with example translations: http://www.linguee.de/englisch-deutsch/uebersetzung/release+notes.html . "Versionshinweise" ("version notes") seems to be commonly used and sounds good to my native speaker ears.
