### ISSUE TITLE
Maven build fails due to missing license headers

### ISSUE THREAD

**Issue by tensberg** [MythTV-Clients/MythTV-Android-Frontend#175]
When I run `mvn install` on the command line, the build fails because the _maven-license-plugin_ complains about missing license headers. Coding and running in Eclipse works fine, though, because the plugin is ignored.

**Comment by billmeek** [comment]
I may have done an apt-get install maven, and I do have a
directory ~/.m2/repository/com/mycila/maven-license-plugin.  For
what it's worth, I'm running Ubuntu 13.04 and haven't seen a
mvn install with that error. Here's a dpkg -l|grep -i maven FYI:

```
http://pastebin.com/raw.php?i=yu3DvKun
```

**Comment by dmfrey** [comment]
it might be that you are trying to do a deploy.  We have a target in there
to keep the license header up to date.  It might not have been run in a
while.  If so, run that first. It should clear up the issue.

On Sat, Sep 14, 2013 at 3:45 PM, billmeek notifications@github.com wrote:

> I may have done an apt-get install maven, and I do have a
> directory ~/.m2/repository/com/mycila/maven-license-plugin. For
> what it's worth, I'm running Ubuntu 13.04 and haven't seen a
> mvn install with that error. Here's a dpkg -l|grep -i maven FYI:
> 
> http://pastebin.com/raw.php?i=yu3DvKun
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/175#issuecomment-24457000
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by tensberg** [comment]
Thanks for the fast responses.

> We have a target in there to keep the license header up to date.

I've had a look at the [license plugin documentation](http://code.mycila.com/license-maven-plugin/) and think you are referring to the `license:format` goal. Running this goal fixed the `mvn install` build as you predicted. Perhaps you'd like to do this and push the changes.

**Comment by dmfrey** [comment]
Mvn install is going to build the app and install it into your local
repository. You shouldn't need to do that just to work on the app.

Eclipse will handle building the app for you. In fact, for an android app,
I never run mvn install.

**Comment by tensberg** [comment]
Of course. I am just used to the Maven build being the project health indicator, so I thought I'd report this. Please close the issue if you think it is not so important.
