### ISSUE TITLE
Recordings: Some episodes disappear at times

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#176]
No "To Duplicate section" yet. But this needs to be documented.

Running on: mythtv-android-frontend-1.10.1-503-g02a8dc3

For example, I have 8 episodes of "Mr. Selfridge" from "Masterpiece Classic".
I just picked up my idle tablet and noticed only episode 8 appeared. Touching
other shows and returning to "Masterpiece Classic" didn't display the missing
7 episodes. Pressing the "new" Refresh icon restored all 8 episodes.

**Comment by dmfrey** [comment]
I started noticing this as well.  Probably a problem with the query on the recordings list

**Comment by dmfrey** [comment]
it appears to be an issue with how programs are getting loaded, some are getting missed

**Comment by dmfrey** [comment]
found it...wrong last modified field was being used to clean up stale recordings.  Program has a last modified date that gets returned in the xml. We maintain a last modified date to indicate in the app when the record was last modified.

**Comment by billmeek** [comment]
@dmfrey, sorry, it's still happening. Running on: mythtv-android-frontend-1.10.1-521-g571c990.
It seems totally random. Even the new Default coverart doesn't display at times.

**Comment by dmfrey** [comment]
@billmeek 

Can you uncomment Lines 87 and 97 in ProgramHelperV27.java and Lines 73 and 83 in RecordingHelperV27.java

Then, in the logcat view, setup a new filter:
Filter Name: org.mythtv:recorded
by Application Name: org.mythtv:recorded
All other fields blank.

Do successive refreshes.  Unless something is actively recording, you should only ever see the UPDATE messages.  If you are also seeing inserts, then the delete process is removing some of your episodes after they have been processed from the web service.

Basic Logic:
1. Download most current list of recordings
2. Establish lastModified date as right now in UTC
3. For each program
- Make sure program is not in livetv or deleted recording group
- Make sure program start and end times are not null
  - If so, mark recording as IN_ERROR = true
    1. Query db for recorded start time and channel id
- If found, perform an UPDATE, setting lastModified date
- if not found, perform an INSERT, setting lastModified date
  1. Check for channel
- Program data has updated channel details, For first program under each channel, check it and add it to local cache so it is not checked anymore for that channel
  - If found, perform an UPDATE, setting lastModified date
  - if not found, perform an INSERT (this is really for if you have miro and mirobridge setup and the miro channel is not in an existing channel lineup), setting lastModified date
    1. If program is NOT IN_ERROR, check the recording
- If found, perform an UPDATE, setting lastModified date
- If not found, perform an INSERT, setting lastModified date
  1. Query all records that are to be deleted
- lastModified date is less than last modified date established in 2 above
- If found, check all existing programs for live stream, send each to RemoveLiveStreamTask
  1. Delete all recorded programs with lastModifed date less than last modified date established in 2 above
     9 8. Delete all recorded program recordings with lastModifed date less than last modified date established in 2 above

All of this is performed in batches.  If a batch reaches at least 100 records, the batch is executed and the count is restarted.  A final processBatch is called periodically after the loop to handle any left over programs that don't surpass a count of 100 and for the delete processes.

Once we verify all the data is getting loaded, we can rule out this portion and move on to the view and try to determine why they are disappearing from your screen

**Comment by billmeek** [comment]
@dmfrey;

OK, Nothing is recording. 

I stashed my changes, so the only differences between my source and
master are the new Log messages.

Corrupted timestamp removed from the backend.

Cleared MAF cache and DB before starting.

On the 1st entry to the Recordings screen there were lots of INSERTS
naturally, 'cause the MAF DB was empty.

On refresh, there were both UPDATES and INSERTS. pastebin:

http://pastebin.com/raw.php?i=vuG7KYnf

Looking at the MAF recorded table, there are 41 entries. I would
have expected over 284 entries. I didn't check every one, but the
lines in MAF recorded do display on the Recordings screen. And,
screen entries that don't display aren't in the DB.

```
GetRecordedList returns <TotalAvailable>284</TotalAvailable>
```

I did another Recordings screen refresh and dumped the MAF DB 
again and now there are 253 entries in it.

**Comment by billmeek** [comment]
Significantly better. However, there were still times episodes were
missed. I've commented out 6 Log messages like that were always
telling me a null channel id and 1969 timestamp. With them gone,
things look even better.

**Comment by dmfrey** [comment]
@billmeek 

Can you check the following...
1. run GetHostName

``` bash
curl -X GET -H "Accept: application/json" http://localhost:6544/Myth/GetHostName
```
1. run GetRecordedList

```
curl -X GET -H "Accept: application/json" http://localhost:6544/Dvr/GetRecordedList -o GetRecordedList.json
jsonlint -f GetRecordedList.json > GetRecordedList_formatted.json
```
1. Confirm the hostnames in the program entries match what is returned from GetHostHostname

I was connected to @pot8oe master backend and noticed this discrepency.  Since we use the hostname to keep items in sync across backends, if this is wrong, i believe it will be failing to load and keep the data correctly

**Comment by billmeek** [comment]
@dmfrey, they do match. {"String": "mc1"} =  "HostName": "mc1", On my
production host (mc0) the same is true, except for the  recordings that
were made when mc1 was running as a slave it it, in which case the
HostName is slave-mc1.

**Comment by billmeek** [comment]
This should have been closed on 9/23/2013, but my commit (49cb8764)
had a space between the sharp sign and this issue number.

**Comment by billmeek** [comment]
Reopening, there is still a case where this fails.

```
Start with an empty MAF DB (or possibly just a stale Etag)
Configure and let the Status screen begin
Go to the Recordings screen immediately
Note that there may be missing episodes
Note that if the Recordings screen is refreshed, all is well
```

Looking at the protocol, for the Status screen alone, I see
GetStatus, GetVideoSources, GetChannelInfoList (SourceID 1,2&3 for me)
then 15 Banner retrievals and a GetRecordedList. 

Going to the Recorded screen, a 2nd GetRecordedList is
sent. Followed by Coverart 15x and Banners 16x.

So, my question is: will the 2 GetRecordedList commands
or their processing conflict with each other?

**Comment by billmeek** [comment]
@dmfrey, sorry, significantly worse now. Of 47 shows, only 7 had episodes.
After pressing refresh, all episodes were there.

**Comment by billmeek** [comment]
Still having problems. My 4.1.2 tablet wasn't doing anything,
just picked it up and in the All section, there were only 3
recordings (should be over 250.) Interesting to note that
the three were all recorded tonight. Pressing all the banners,
no coverart showed up except for the three new recordings
and they had the single episode recorded tonight.

Dumping the MAF DB and looking at it with the browser,
there are only 3 recordings in the recorded and
recorded_upcoming tables. The same 3 as above.

**Comment by dmfrey** [comment]
@billmeek can you capture the log for just the org.mythtv:recorded process
and post that to me? You can filter on just the process in the logcat view
in eclipse.

There has to be something slightly different with 4.1.2 than 4.2+.

**Comment by billmeek** [comment]
@dmfrey, this is the shortened version. I'll pastebin the
whole thing if that's of value. Looks like everything gets
loaded then deleted?

```
09-28 09:24:02.226: D/RecordedService(9029): onHandleIntent : enter
09-28 09:24:02.242: I/RecordedService(9029): onHandleIntent : DOWNLOAD action selected
09-28 09:24:02.242: V/RecordedHelperV27(9029): process : enter
09-28 09:24:02.414: V/RecordedHelperV27(9029): downloadRecorded : enter
09-28 09:24:02.421: D/RecordedHelperV27(9029): downloadRecorded : etag="6dd2f89db59894277e2c3d38cdfe4ddf0c9abf97"
09-28 09:24:06.734: I/RecordedHelperV27(9029): download : GetRecordedList returned 200 OK
09-28 09:24:06.734: D/RecordedHelperV27(9029): load : enter
09-28 09:24:06.734: V/RecordedHelperV27(9029): processProgramGroups : enter
09-28 09:24:06.742: V/RecordedHelperV27(9029): processProgramGroups : adding 'All' program group in programGroups
09-28 09:24:06.742: V/RecordedHelperV27(9029): processProgramGroups : processing programGroup '2013 Indianapolis 500'

... (40 lines deleted)

09-28 09:24:07.492: V/RecordedHelperV27(9029): processProgramGroups : processing programGroup 'Woodsmith Shop'
09-28 09:24:07.507: V/RecordedHelperV27(9029): processProgramGroups : applying batch for '42' transactions
09-28 09:24:07.718: V/RecordedHelperV27(9029): processProgramGroups : remove deleted program groups
09-28 09:24:07.718: V/RecordedHelperV27(9029): processProgramGroups : applying batch for '42' transactions
09-28 09:24:07.742: V/RecordedHelperV27(9029): processProgramGroups : exit
09-28 09:24:07.742: V/ProgramHelperV27(9029): processProgram : INSERT PROGRAM : Castle:Love Me Dead:1071:2013-09-09T06:00:00.000Z:2013-09-09T07:00:00.000Z:mc0:recorded
09-28 09:24:07.757: V/RecordingHelperV27(9029): processRecording : INSERT RECORDING : Castle:Love Me Dead, recording=409:recording_recorded

...  540 INSERT RECORDING couplets deleted, but I left the following in

161 09-28 09:24:08.585: I/RecordedHelperV27(9029): load : applying batch for '100' transactions
262 09-28 09:24:09.437: I/RecordedHelperV27(9029): load : applying batch for '100' transactions
363 09-28 09:24:10.304: I/RecordedHelperV27(9029): load : applying batch for '101' transactions
462 09-28 09:24:11.296: I/RecordedHelperV27(9029): load : applying batch for '100' transactions
563 09-28 09:24:11.984: I/RecordedHelperV27(9029): load : applying batch for '100' transactions

09-28 09:24:12.773: V/ProgramHelperV27(9029): processProgram : INSERT PROGRAM : The Dr. Oz Show:Viewers Take Over Dr. Oz!:1321:2013-09-20T20:00:00.000Z:2013-09-20T21:00:00.000Z:mc0:recorded
09-28 09:24:12.781: V/RecordingHelperV27(9029): processRecording : INSERT RECORDING : The Dr. Oz Show:Viewers Take Over Dr. Oz!, recording=388:recording_recorded
09-28 09:24:12.781: I/RecordedHelperV27(9029): load : applying final batch for '57' transactions
09-28 09:24:13.171: V/RecordedHelperV27(9029): load : remove deleted recording live streams
09-28 09:24:13.382: V/RecordedHelperV27(9029): load : queued deleted program - Castle:Love Me Dead:2013-09-28T08:24:13.183-05:00:2013-09-28T00:15:05.833-05:00 (false)

... (272 similar lines deleted)

09-28 09:24:19.359: V/RecordedHelperV27(9029): load : queued deleted program - The Dr. Oz Show:Viewers Take Over Dr. Oz!:2013-09-28T08:24:13.183-05:00:2013-09-28T00:15:10.935-05:00 (false)
09-28 09:24:19.382: V/RecordedHelperV27(9029): load : queued deleted programs - 269
09-28 09:24:19.382: V/ProgramHelperV27(9029): deletePrograms : enter
09-28 09:24:19.382: V/ProgramHelperV27(9029): deletePrograms : exit 
09-28 09:24:19.382: V/RecordingHelperV27(9029): deleteRecordings : enter
09-28 09:24:19.382: V/RecordingHelperV27(9029): deleteRecordings : exit
09-28 09:24:19.382: I/RecordedHelperV27(9029): load : applying delete batch for transactions
09-28 09:24:19.484: I/RecordedHelperV27(9029): download : saving etag: "6cadfd2fa641fdde722697b8ced2a696b2f05043"
09-28 09:24:19.531: V/RecordedHelperV27(9029): downloadRecorded : exit
09-28 09:24:19.531: V/RecordedHelperV27(9029): process : exit
09-28 09:24:19.531: D/RecordedService(9029): onHandleIntent : exit
```

**Comment by billmeek** [comment]
How 'bout this. I'm doing my testing with both tablets on at the
same time. I just noticed that my 10" tablet had no programs
all. Now my 7" one had a full set. Both are configured to listen to
the same backend.

Other than taking the 9/28/2013 commits, neither tablet has
seen much activity.

Is testing with 2 devices causing errors? It's unusual, but
we have no 'rules' that say don't do it.

**Comment by pot8oe** [comment]
I usually test with 2 phones and 1 tablet at the same time. The clients
should not interfere with each other.

**Comment by billmeek** [comment]
Running on: 3cfee4d

On the Guide screen, only channels with scheduled recordings
are showing up, no other data. I started with an empty MAF DB.

**Comment by dmfrey** [comment]
is the guide table populated in your db?

On Wed, Oct 2, 2013 at 1:59 PM, billmeek notifications@github.com wrote:

> Running on: 3cfee4dhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/commit/3cfee4d
> 
> On the Guide screen, only channels with scheduled recordings
> are showing up, no other data. I started with an empty MAF DB.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/176#issuecomment-25561591
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
Yes, but there are only 91 entries, all of which are shows I
record. There are 91 entries in the upcoming table too.

**Comment by dmfrey** [comment]
it sounds like the program guide service never ran

On Wed, Oct 2, 2013 at 2:13 PM, billmeek notifications@github.com wrote:

> Yes, but there are only 91 entries, all of which are shows I
> record. There are 91 entries in the upcoming table too.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/176#issuecomment-25562747
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
You're right. So, I thought I'd restart the test and left the
Guide screen and THEN the downloads started. Thought
it was related to the latest commit.

Back to the original topic of this issue, I'll have to wait and
see if any recordings disappear. Everything looks good now.

**Comment by billmeek** [comment]
1615, one episode left on the Recordings screen.
As usual, all the banners are there, just empty
except 1 (and All, which has the same recording.)

It's a show that just started recording at 1600.
Both recorded and recording_recorded have one entry.
FWIW, the_id=401.

And, before I pressed the Comment button, I looked
at the screen again and everything is there. And 
there are 270 entries in the DB.

**Comment by billmeek** [comment]
To Duplicate

```
Get a 'normal' Recording screen
Wait for any show to record in MythTV
Observe all recordings are gone except for the ones recorded today
```

I have a 3169 lline LogCat saved. Lots of INSERTs and then
almost everything is deleted:

``` l
...
10-02 17:42:26.792: V/RecordedHelperV27(5396): load : queued deleted program - The Dr. Oz Show:Viewers Take Over Dr. Oz!:2013-10-02T16:42:24.017-05:00:2013-10-02T16:38:27.991-05:00 (false)
10-02 17:42:26.792: V/RecordedHelperV27(5396): load : queued deleted programs - 269
```

It looks like the test-to-delete is based on: lastModified = lastModified.minusHours( 1 ),
yet I have recordings that are from last May (and other users simply archive everything
in MythTV recordings. Should this check be removed?)

**Comment by dmfrey** [comment]
i wanted to make sure we were deleting everything that wasn't touched in over an hour.

I wonder if instead of basing this on time, I do something like generate a UUID for each run and use that the key off of.  So set a UUID column on each table and delete anything that doesn't match after all the new data has been processed.

I am really starting to find that storing dates in the db that need to be acted upon are not reliable.  

Thoughts?

**Comment by dmfrey** [comment]
retest #176

**Comment by billmeek** [comment]
Still looses previous recordings. Slightly updated To Duplicate steps:

```
Get a 'normal' Recording screen, 2xx items for me
Wait for any show to record in MythTV
Tap the Refresh icon
Observe all recordings are gone except for the one(s) the one just recorded
Tap on the Refresh icon and all recordings appear.
```

As to your "Thoughts?" question...

I have been think about this. I don't know of any easy solution. Something
to consider for 1.xx.x, use GetTitleInfoList that returns _much_ less data and
then if a user selects a title, use GetRecordedList with the TitleRegEx argument
to retrieve only data for that show. Delete everything for that show in the 
MAF recorded DB before getting the new data. Completely new design and
not for 1.20.0.

**Comment by billmeek** [comment]
Closing. Running on master mythtv-android-frontend-1.10.1-609-g68d06fa.
Discussing the issue of new recordings showing up without pressing the
refresh icon off-list.
