### ISSUE TITLE
More transcoder options

### ISSUE THREAD

**Issue by Prefect47** [MythTV-Clients/MythTV-Android-Frontend#18]
It would be nice to be able to configure playback profiles with cropping (for recordings with black bars).

And to be able to switch playback profile easier. Not that it's all that hard right now of course, but you should maybe be able to reach the prefs screen from the recordings list?

**Comment by dmfrey** [comment]
I will have to review the myth service api for initiating a live stream to see if it accept crop settings and such.

I will also see about placing a subset of preferences on the recordings page.

**Comment by rhpot1991** [comment]
It actually only passes the height in for the API call, so the width is calculated based on the aspect ratio by the backend.

**Comment by dmfrey** [comment]
@rhpot1991 added a number of options for playback profile choices.  Do you want more options than what is in there.  You could also adjust the settings on some of the existing ones as well to try out other settings.

**Comment by dmfrey** [comment]
@Prefect47 are the playback options satisfactory?  If so, please close the issue.  

Thanks.

**Comment by Prefect47** [comment]
They are appreciated. :)

If the API doesn't support it then nothing much can be done, so I'm clising this issue.
