### ISSUE TITLE
Recordings: Watch icon does everything up to playing an episode for 'off hour' start time

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#185]
Looks like the next step after #148. The MAF display shows 
Processing 0%. However, on the backend, the livestream
table shows 100% complete, there are proper files in the
steaming directory, and mythtranscode's log shows a
normal termination.

There wasn't a slave backend involved for this test.

A recording with 'matching' start times is OK.

Running on: mythtv-android-frontend-1.10.1-510-g443c550

``` sql
select
  r.title, r.sub_title, r.start_time, rr.start_ts, rr.start_time
from
  recorded r
    left join recording_recorded rr on r.start_time = rr.start_time and r.record_id = rr.record_id and r.master_hostname = rr.master_hostname
where
    r.master_hostname = 'mc1' and not rr.start_time = rr.start_ts
order by
    r.start_time desc;
```

Returns:

```
Jeopardy!||1379359800000|1379360220000|1379359800000
```

```
$ date --utc --date='@1379360220'
Mon Sep 16 19:37:00 UTC 2013

$ date --utc --date='@1379359800'
Mon Sep 16 19:30:00 UTC 2013
```

**Comment by dmfrey** [comment]
@billmeek can you retest this issue now and let me know if it is still  happening?  Changes were made to how episode handling occurred between the app and the backend as it relates to playback, live stream handling and deletes,  I do not think this issue is still occurring.

**Comment by billmeek** [comment]
Looks good.
