### ISSUE TITLE
Guide screen: Missing programs

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#189]
I went to the Guide screen. All channels from 2_1 through
115 displayed a full day's worth of programs.

Icon downloading is turned off for this test.

Next, I pressed the channel 117, it's the next in the list
of channels. Only one  program was shown.

Note that the program is scheduled to record and has the 
red dot. Also, the only other channel that should record is 2_1,
and it doesn't have a red dot.

Looking in the MAF DB, with:

``` sql
select title,start_time from guide
   where channel_id=2117
      order by start_time;
```

There are 14 entries, all for The Daily Show..., no other programs.

Doing: 

```
http://mc0:6544/Guide/GetProgramGuide?StartTime=2013-09-25T00:00:00&EndTime=2013-09-25T23:59:59&StartChanId=2117&NumChannels=1
```

Returns a Count of 40 shows.

Happens on Android 4.0.4 & 4.1.2, using the same MBE.

**Comment by dmfrey** [comment]
in those 40 programs, do any stand out that should not be loaded for any reason (i.e. invalid date/times, not visible, etc.)?

**Comment by billmeek** [comment]
``` xml
<StartTs xsi:nil="true"/>
<EndTs xsi:nil="true"/>
```

But this is true for good and bad channels.

Looking now, channel 117 looks fine on the Guide screen,
as does the next channel 141, but 142 has no data. 143 is
fine as is 225. 301 and 302 are blank, 303 is fine etc.

Channel 2142  has Visible true

FWIW. 2xxx and 3xxx both get their MythTV EPG info from
Schedules Direct for the SAME cable provider.
The channels marked visible are:
21xx
23xx
36xx
No other channels are visible in these ranges. The 1xxx
channels are over the air and all look OK.

**Comment by billmeek** [comment]
Looking at a fresh dump of the MAF DB, there are 2619 entries
in the guide table. There are 81 entries in the recording_guide
table. The 1st 81 entries in guide look good. the remainder have
no season, episode, description, inetref and other data. Should
there be 2619 entries in recording_guide?

**Comment by dmfrey** [comment]
guide Program entries do not have Recording entries, they are only present
on Recorded and Upcoming listing.

They entries you are seeing in the recording_guide table are directly
related to updating the guide data based on refreshing the Upcoming  data
or the backend status.

These entries update the recording_guide table so that we can indicate a
program in the guide is scheduled to be recorded with the red dot.

**Comment by dmfrey** [comment]
@billmeek are you still missing recordings on the program guide with all the recent changes that have been made?

**Comment by billmeek** [comment]
Yes, but I have a MythTV fix that solves it for me. Now I"m trying to
test other permutations of source/channel/visible configurations.
My guess is that this can be closed, but I haven't convinced myself
yet. My test platform works fine, as I suspect yours does.

**Comment by dmfrey** [comment]
Go ahead and close it when you are comfortable that it has been resolved.

**Comment by billmeek** [comment]
Closing as I'm convinced this is unique to one of my configurations. I'm
not going to label it upstream/won't fix/invalid. There's an issue here, 
just not sure of the root cause.
