### ISSUE TITLE
Recording playback choppy

### ISSUE THREAD

**Issue by Prefect47** [MythTV-Clients/MythTV-Android-Frontend#19]
I get pauses in playback that seem to be around every second, but only the video, not the audio. Maybe it's a problem on the server side (transcoding) but I don't see it if I play the same stream in the backend web interface on another computer.

For some recordings I also see a bleeding effect when this happens - everything bleeds a bit downwards right before the small pause, and when it comes back it looks good again. Very annoying since it happens around every second. Again, only the video, not the audio.

**Comment by rhpot1991** [comment]
What video player are you using?  If using the default try something else like bsplayer lite.

**Comment by dmfrey** [comment]
Can you also add which playback profile you are using.  Also, some hardware specs on your backend may be helpful.  Thanks.

**Comment by dmfrey** [comment]
@Prefect47 sorry, forgot to tag you in this so you get alerted to the comments above.

**Comment by Prefect47** [comment]
Sorry for the late reply, but I finally have time now that my vacation has started :)

The latest version (2012-06-30) seems to work much better. But only in BSPlayer with SW decoding (or BSPlayers accelerated decoding). The effect I saw is gone but in the native player and MXPlayer playback is choppy, though only visible as dropped frames.

My backend is an i7 so no problems with transcoding power there.

**Comment by Prefect47** [comment]
Spoke too soon. The effect still happens but only in the 720p profile. If I use the default 540p profile video is smooth in BSPlayer.

**Comment by dmfrey** [comment]
@Prefect47 when HLS is fixed in myth backend, can you try HLS through the web player and something like vlc?  Do you experience the same choppiness?

**Comment by dmfrey** [comment]
@Prefect47 closing the issue for now. If this issue is still occurring for you, please re-open the issue and update with your findings.
