### ISSUE TITLE
Guide: Duplicate channel numbers

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#190]
May be related to #189.

``` sql
.mode column
select callsign,chan_id,chan_num from channel order by chan_id;
```

```
Video source 1, 12 OTA Channels A-OK

CBS2-HD     1021        2_1       
NBC5        1051        5_1       
WLS-HD      1071        7_1       
WGN-DT      1091        9_1       
WTTW-HD     1111        11_1      
WTTW-DT     1112        11_2      
WTTW-DT     1113        11_3      
WYCC HD     1201        20_1      
WCIU-HD     1261        26_1      
WFLD        1321        32_1      
ION         1381        38_1      
WPWR-TV     1501        50_1      

Video source 2, 28 Cable Channels, starts out OK...

AETV        2105        105       
BRAVO       2106        106       
TBS         2107        107       
TNT         2108        108       
USA         2109        109       
SPIKETV     2110        110       
FX          2111        111       
SYFY        2112        112       
E           2115        115       
COMEDY      2117        117       
FMC         2141        141       
AMC         2142        142      
HGTV        2225        225       

The problems start here with channels that appear in video sources 2 AND 3.
The comments after the DB dump is what displays on the Guide.

CSPAN       2301        301       n and 0,  n = A reasonable number,
CSPAN2      2302        302       n and 0      I didn't count all of them
CSPAN3      2303        303       n and 0
CNN         2305        305       n and 0
HLN         2306        306       n and 0
CNBC        2310        310       n and 0
MSNBC       2311        311       n and 0
FNC         2315        315       n and 0
TRAV        2333        333       n and 0
DSC         2335        335       n and 0
HISTORY     2340        340       n and 0
TLC         2345        345       34 in one chl. 345 listing, 1 in the other,
                                  (which is missing from the group of 34)
ESPN        2363        363       n and 0
ESPN2       2364        364       n and 0
NBCSN       2382        382       24 in one chl. 382 listing, 1 in the other,
                                  (which is missing from the group of 24)

Video source 3, 41 HD Home Run Prime Cable Channels..........

CSPAN       3301        301       
CSPAN2      3302        302       
CSPAN3      3303        303       
CNN         3305        305       
HLN         3306        306       
CNBC        3310        310       
MSNBC       3311        311       
FNC         3315        315       
TRAV        3333        333       
DSC         3335        335       
HISTORY     3340        340       
TLC         3345        345       
ESPN        3363        363       
ESPN2       3364        364       
NBCSN       3382        382       

And now the Video source 3 channels that don't exist in source 2

WBBMDT      3602        602       1 show
WMAQDT      3605        605       0 shows
WLSDT       3607        607       0 shows
WPWRDT      3608        608       0 shows
WGNDT       3609        609       0 shows
WTTWDT      3611        611       0 shows
WFLDDT      3612        612       1 show
WCPXDT      3615        615       1 show
AETVHD      3620        620       0 shows
BRAVOHD     3621        621       0 shows
TBSHD       3622        622       0 shows
TNTHD       3623        623       0 shows
USAHD       3624        624       1 show
SPIKEHD     3625        625       1 show
FXHD        3626        626       0 shows
SYFYHD      3630        630       0 shows
APLHD       3631        631       0 shows
CCHD        3632        632       36 shows, looks like the shows missing from 117
EHD         3637        637       1 show
HGTVD       3643        643       1 show
WEATHHD     3655        655       2 shows
DSCHD       3661        661       0 shows
HSTRYHD     3662        662       0 shows
TLCHD       3663        663       18 shows
AMCHD       3667        667       6 shows
NBCSNHD     3691        691       0 shows
```

The total number of channels in the 3 sources matches the
total number of visible channels in MythtV's DB.

``` sql
select callsign,chanid,channum from channel where visible > 0 order by chanid;
+----------+--------+---------+
| callsign | chanid | channum |
+----------+--------+---------+
| CBS2-HD  |   1021 | 2_1     |
| NBC5     |   1051 | 5_1     |
| WLS-HD   |   1071 | 7_1     |
...
+----------+--------+---------+
81 rows in set (0.00 sec)
```

**Comment by billmeek** [comment]
I didn't see a commit for this, but at 17:53 9/28/2013, there
are no duplicate channels. I did change the callsign on 3
channels in MythTV in the 600 range, but none in the 300s,
which is where the duplicates were showing up.

**Comment by dmfrey** [comment]
After running with commit 3cfee4d dump your sqlite database and execute the following query:

``` sql
select distinct 
    chan_num_major as _ID, callsign,xmltv_id
from 
    channel 
order by
    chan_num_formatted
```
1. Does this now return unique results from the db?
2. Does this now return unique results in the program guide?

I only have unique records in my 2 video sources, so I cannot test this accurately

**Comment by billmeek** [comment]
Running on: 3cfee4d.

I added chan_id to your SQL after looking at the initial result
and then atsc_major_chan (which has correct data.)

Three odd things here. The chan_num_major's are wrong for
all of my over-the-air channels.

2143 shows up even though in the MythTV DB it is marked
with visible=0. 2143 is also the last channel in the unsorted
MAF list of channels. It's not last in the XML.

http://mc0:6544/Channel/GetChannelInfoList?SourceID=2
returns `<Visible>false</Visible>` for 2143.

Third, in Guide, only channels with scheduled recordings
are showing up, no other data. I'll add that comment to
#176.

``` sql
sqlite> .mode columns
sqlite> select distinct 
    chan_id, atsc_major_chan, chan_num_major as _ID, callsign,xmltv_id
from 
    channel 
order by
    chan_num_formatted; 

1021        2                       CBS2-HD     20454     
1051        5                       NBC5        20452     
1071        7                       WLS-HD      20456     
1091        9                       WGN-DT      20455     
1111        11          1           WTTW-HD     30415     
1112        11          1           WTTW-DT2    36111     
1113        11          1           WTTW-DT3    49346     
1201        20          2           WYCC HD     34542     
1261        26          2           WCIU-HD     36099     
1321        32          3           WFLD        20361     
1381        38          3           ION         24024     
1501        50          5           WPWR-TV     34662     
2105        105         105         AETV        10035     
2106        106         106         BRAVO       10057     
2107        107         107         TBS         11867     
2108        108         108         TNT         11164     
2109        109         109         USA         11207     
2110        110         110         SPIKETV     11163     
2111        111         111         FX          14321     
2112        112         112         SYFY        11097     
2115        115         115         E           10989     
2117        117         117         COMEDY      10149     
2141        141         141         FMC         14988     
2142        142         142         AMC         10021     
2143        0           143         TCM                   
2225        225         225         HGTV        14902     
2301        301         301         CSPAN       10161     
2302        302         302         CSPAN2      10162     
2303        303         303         CSPAN3      17665     
2305        305         305         CNN         10142     
2306        306         306         HLN         10145     
2310        310         310         CNBC        10139     
2311        311         311         MSNBC       16300     
2315        315         315         FNC         16374     
2333        333         333         TRAV        11180     
2335        335         335         DSC         11150     
2340        340         340         HISTORY     14771     
2345        345         345         TLC         11158     
2363        363         363         ESPN        10179     
2364        364         364         ESPN2       12444     
2382        382         382         NBCSN       15952     
3602        602         602         CBS2-HD     20454     
3605        605         605         WMAQDT      20452     
3607        607         607         WLS-HD      20456     
3608        608         608         WPWRDT      34662     
3609        609         609         WGNDT       20455     
3611        611         611         WTTW-HD     30415     
3612        612         612         WTTW-DT2    20361     
3615        615         615         WCPXDT      24024     
3620        620         620         AETVHD      51529     
3621        621         621         BRAVOHD     58625     
3622        622         622         TBSHD       58515     
3623        623         623         TNTHD       42642     
3624        624         624         USAHD       58452     
3625        625         625         SPIKEHD     59186     
3626        626         626         FXHD        58574     
3630        630         630         SYFYHD      58623     
3631        631         631         APLHD       57394     
3632        632         632         CCHD        62420     
3637        637         637         EHD         61812     
3643        643         643         HGTVD       49788     
3655        655         655         WEATHHD     58812     
3661        661         661         DSCHD       56905     
3662        662         662         HSTRYHD     57708     
3663        663         663         TLCHD       57391     
3667        667         667         AMCHD       59337     
3691        691         691         NBCSNHD     48639
```

**Comment by dmfrey** [comment]
what is your atsc_major on your OTA channels?  I added the chan_num_major,
but I was really looking for the atsc_major, so that was probably not needed

On Wed, Oct 2, 2013 at 2:02 PM, billmeek notifications@github.com wrote:

> Running on: 3cfee4dhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/commit/3cfee4d
> .
> 
> I added chan_id to your SQL after looking at the initial result
> and then atsc_major_chan (which has correct data.)
> 
> Three odd things here. The chan_num_major's are wrong for
> all of my over-the-air channels.
> 
> 2143 shows up even though in the MythTV DB it is marked
> with visible=0. 2143 is also the last channel in the unsorted
> MAF list of channels. It's not last in the XML.
> 
> http://mc0:6544/Channel/GetChannelInfoList?SourceID=2
> returns <Visible>false</Visible> for 2143.
> 
> Third, in Guide, only channels with scheduled recordings
> are showing up, no other data. I'll add that comment to
> #176https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/176
> .
> 
> sqlite> .mode columnssqlite> select distinct
>     chan_id, atsc_major_chan, chan_num_major as _ID, callsign,xmltv_idfrom
>     channel order by
>     chan_num_formatted;
> 1021        2                       CBS2-HD     20454     1051        5                       NBC5        20452     1071        7                       WLS-HD      20456     1091        9                       WGN-DT      20455     1111        11          1           WTTW-HD     30415     1112        11          1           WTTW-DT2    36111     1113        11          1           WTTW-DT3    49346     1201        20          2           WYCC HD     34542     1261        26          2           WCIU-HD     36099     1321        32          3           WFLD        20361     1381        38          3           ION         24024     1501        50          5           WPWR-TV     34662     2105        105         105         AETV        10035     2106        106         106         BRAVO       10057     2107        107         107         TBS         11867     2108        108         108         TNT         11164     2109        109         109         USA         11207     2110        110         110         SPIKETV     11163     2111        111         111         FX          14321     2112        112         112         SYFY        11097     2115        115         115         E           10989     2117        117         117         COMEDY      10149     2141        141         141         FMC         14988     2142        142         142         AMC         10021     2143        0           143         TCM                   2225        225         225         HGTV        14902     2301        301         301         CSPAN       10161     2302        302         302         CSPAN2      10162     2303        303         303         CSPAN3      17665     2305        305         305         CNN         10142     2306        306         306         HLN         10145     2310        310         310         CNBC        10139     2311        311         311         MSNBC       16300     2315        315         315         FNC         16374     2333        333         333         TRAV        11180     2335        335         335         DSC         11150     2340        340         340         HISTORY     14771     2345        345         345         TLC         11158     2363        363         363         ESPN        10179     2364        364         364         ESPN2       12444     2382        382         382         NBCSN       15952     3602        602         602         CBS2-HD     20454     3605        605         605         WMAQDT      20452     3607        607         607         WLS-HD      20456     3608        608         608         WPWRDT      34662     3609        609         609         WGNDT       20455     3611        611         611         WTTW-HD     30415     3612        612         612         WTTW-DT2    20361     3615        615         615         WCPXDT      24024     3620        620         620         AETVHD      51529     3621        621         621         BRAVOHD     58625     3622        622         622         TBSHD       58515     3623        623         623         TNTHD       42642     3624        624         624         USAHD       58452     3625        625         625         SPIKEHD     59186     3626        626         626         FXHD        58574     3630        630         630         SYFYHD      58623     3631        631         631         APLHD       57394     3632        632         632         CCHD        62420     3637        637         637         EHD         61812     3643        643         643         HGTVD       49788     3655        655         655         WEATHHD     58812     3661        661         661         DSCHD       56905     3662        662         662         HSTRYHD     57708     3663        663         663         TLCHD       57391     3667        667         667         AMCHD       59337     3691        691         691         NBCSNHD     48639
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/190#issuecomment-25561819
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
atsc_major_chan is the 2nd column in the previous post.
There is no atsc_major column (I assume you were just
abbreviating.) It's much more readable on the issues list
(as opposed to email, at least my email client.)

**Comment by billmeek** [comment]
No duplicates, no invalid data. Closing. Opened #213 to
track the single unexpected channel 2143 in the table.
