### ISSUE TITLE
Guide: Invalid channel icons for channels that don't have an icon defined

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#191]
Examples: Channel 340 appears on video sources 2 and 3
and it's the same History channel.

One channel 340 correctly displays the History icon. The other
displays the FOXNEWS icon.

In the MAF DB, there is an entry for 2340, but not 3340:

```
2340        340         HISTORY               history.jpg
```

The 2nd type of invalid icon is for a single channel: Channel 643
is only in video source 3 and is the HGTVHD channel. It's icon,
however, is CSPAN. There is no DB entry for channel 3643.

**Comment by dmfrey** [comment]
@billmeek can you verify on your backend that the channel that doesn't have an icon has one set?

**Comment by dmfrey** [comment]
I think you are seeing the wrong icons because of a timing issue.  It updates the visible views once scrolling has stopped, so it does take a second then to download .  A forthcoming update will also not call the backend if the the backend url has not been set.

**Comment by billmeek** [comment]
You beat me to it. For the record:

``` sql
select chanid,channum,callsign,icon from channel where chanid in (1112,2340,3340);
+--------+---------+----------+-------------+
| chanid | channum | callsign | icon        |
+--------+---------+----------+-------------+
|   1112 | 11_2    | WTTW-DT  |             |
|   2340 | 340     | HISTORY  | history.jpg |
|   3340 | 340     | HISTORY  |             |
+--------+---------+----------+-------------+
3 rows in set (0.01 sec)

select chan_id,chan_num,callsign,icon_url from channel where chan_id in (1112,2340,3340);
1112        11_2        WTTW-DT                                                       
2340        340         HISTORY               history.jpg                             
3340        340         HISTORY
```

**Comment by billmeek** [comment]
On an empty MAF DB, the initial screen with my example 11_2
is now correct (no icon.) I can't honestly say if my initial finding
was based on an empty DB.

However, if I scroll down so that 11_2 is gone and then scroll up
again to display 11_2, it now has an icon for 'Turner'.

``` sql
select chan_id,chan_num,callsign,icon_url from channel where chan_id in (1112,2107);
1112        11_2        WTTW-DT                                                           
2107        107         TBS                   turner_broadcasting_system.jpg
```

As for the rest other channels in the 3xx and 6xx range, there are still
cases with incorrect icons, but let's treat that after #190.

**Comment by billmeek** [comment]
If this is going to be disabled, I'd suggest removing the
option from the setup screen too.

**Comment by dmfrey** [comment]
ok, will remove that as well.  This should speed up the scrolling as well.
 I think downloading will get moved to the channel loader, then this view
can just pull from cache.

On Mon, Sep 30, 2013 at 12:14 PM, billmeek notifications@github.com wrote:

> If this is going to be disabled, I'd suggest removing the
> option from the setup screen too.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/191#issuecomment-25377522
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey
