### ISSUE TITLE
Choreographer skipped frames question

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#193]
Opening this as a question only at this time. I've just
started seeing this message in LogCat, probably in
the last week. I can see it's informational, but does
this require fixing?

```
09-25 23:08:36.101: I/Choreographer(10853): Skipped 613 frames!  The application may be doing too much work on its main thread
```

**Comment by dmfrey** [comment]
I found some info on this here:
http://stackoverflow.com/questions/11266535/meaning-of-choreographer-messages-in-logcat

**Comment by dmfrey** [comment]
I found this on stackoverflow: http://stackoverflow.com/questions/15963969/choreographer639-skipped-50-frames
- Loading database information on the UI thread. Use a Loader
- Running long processes on the UI thread. Use an AsyncTaskLoader
- The emulator is just slow, as you don't overload the UI thread. Try your code on a real device or follow the guidelines here and here
- There is a lot to do onCreate: set the activity with configChanges

We are already doing most of these items (some do not apply).  

I think it is safe to close this issue.
