### ISSUE TITLE
Gallery: Undefined Storage Group isn't reported to user.

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#194]
This is a MythTV configuration error that MAF doesn't report.

To duplicate,

```
Make sure the MythTV backend doesn't have the Images SG
Make sure that the MAF DB is empty
Start and configure MAF
Go to the Multimedia screen
```

If the new Multimedia screen attempts to get a storage group
that doens't exist, it displays an empty screen and a spinning
circle.

User's can exit by simply pressing the return button

Correcting the Master Backend solves the problem.

The backend receives the following:

```
/Myth/GetStorageGroupDirs?GroupName=Images&HostName=mc0
```

And returns a 200 OK with:

```
<StorageGroupDirList version="1.0" serializerVersion="1.1">
<StorageGroupDirs/>
</StorageGroupDirList>
```

**Comment by billmeek** [comment]
The above is correct, but the spinner never shuts off, even
when the proper Storage Group is defined.

**Comment by dmfrey** [comment]
Is that because it is still loading metadata for the images and building
the grid of images?

On Thu, Sep 26, 2013 at 12:46 PM, billmeek notifications@github.com wrote:

> The above is correct, but the spinner never shuts off, even
> when the proper Storage Group is defined.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/194#issuecomment-25183536
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
@dmfrey, I don't know if it's still loading the grid. I don't
think so. I think the spinner just isn't getting turned off.
I only have 92 pictures on my MBE and I've looked at
all the thumbnails as well as the pictires, all display A-OK.

**Comment by dmfrey** [comment]
ok, i will look into it

On Thu, Sep 26, 2013 at 1:31 PM, billmeek notifications@github.com wrote:

> @dmfrey https://github.com/dmfrey, I don't know if it's still loading
> the grid. I don't
> think so. I think the spinner just isn't getting turned off.
> I only have 92 pictures on my MBE and I've looked at
> all the thumbnails as well as the pictires, all display A-OK.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/194#issuecomment-25187022
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by dmfrey** [comment]
@espenaf can you take a look at this?  I think I am missing something in your original code.  I think it is around line 524 in GalleryGridAdapter.java

**Comment by billmeek** [comment]
@dmfrey,

I looked at the commit. Since this is a new MAF feature, we can recommend
only one storage group, not one for 0.26 and one for 0.27. Of course, there's
always #204 that says the storage group name should be "Photographs". I
would recommend "Photographs". The idea being to keep users from changing
the Storage Group name. Of course, the MythTV developers can change the
name again... Help strings/translations will need to change. I can do that.

**Comment by dmfrey** [comment]
Gotcha. I thought the issue was it was one way in v0.26 and changing going
forward in v0.27. I misunderstood.

We can get rid of all that branching I am doing for versions.

I am good with Photographs as the storage group name.
