### ISSUE TITLE
Speedup, Checking if a Master Backend is alive.

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#199]
Design discussion for now.

What follows is an analysis of the protocol exchanged
between MAF, FE and MBE whenever a single key
is pressed.

The key speedup here would be a change from getting
"/" from the MBE to using Myth/GetHostName That should
save about 3,160 bytes in 2 PSH and 2 ACK messages.

As is, 12 messages are exchanged between MAF
and the MBE for a total of 4,423 bytes to see if it's
alive.

The FE conversation consists of 8 messages using
1,571 bytes to see if the FE is alive followed by 10
messages using 1,305 bytes to send the keypress.

As for MythMote, is testing that the BE is alive necessary?

```
Synopsis of protocol exchanged from MAF to the MBE when a single MythMote button is pressed:

      1 0.000000    mythandroid.local     mc0.local             TCP      74     40985 > myth-sapi [SYN]
      2 0.000035    mc0.local             mythandroid.local     TCP      74     myth-sapi > 40985 [SYN, ACK]
      3 0.001356    mythandroid.local     mc0.local             TCP      66     40985 > myth-sapi [ACK]
      4 0.002425    mythandroid.local     mc0.local             TCP      232    40985 > myth-sapi [PSH, ACK]
      5 0.002444    mc0.local             mythandroid.local     TCP      66     myth-sapi > 40985 [ACK]
X     6 0.002968    mc0.local             mythandroid.local     TCP      1514   myth-sapi > 40985 [ACK]
X     7 0.002992    mc0.local             mythandroid.local     TCP      1514   myth-sapi > 40985 [ACK]
      8 0.003020    mc0.local             mythandroid.local     TCP      485    myth-sapi > 40985 [PSH, ACK]
X     9 0.005776    mythandroid.local     mc0.local             TCP      66     40985 > myth-sapi [ACK]
X    10 0.008782    mythandroid.local     mc0.local             TCP      66     40985 > myth-sapi [ACK]
     11 0.009059    mythandroid.local     mc0.local             TCP      66     40985 > myth-sapi [ACK]
     12 0.021640    mythandroid.local     mc0.local             TCP      66     40985 > myth-sapi [RST, ACK]

For a total of 4,423 bytes exchanged! The bulk of it being done by the GET / (3513 bytes)

This is what frame 4 is actually sending:

GET / HTTP/1.1 User-Agent: Dalvik/1.6.0 (Linux; U; Android 4. 1.2; SM-T210R Build/JZO54K)
Host: 192.168.1.204:6544
Connection: Keep-Alive
Accept-Encoding: gzip

Protocol exchanged between MAF and FE when any MythMote is pressed

See if the FE is alive (1,517 bytes):

     13 0.400463    mythandroid.local     ofc0.local            TCP      74     38361 > myth-fe [SYN]
     14 0.400518    ofc0.local            mythandroid.local     TCP      74     myth-fe > 38361 [SYN, ACK]
     15 0.402581    mythandroid.local     ofc0.local            TCP      66     38361 > myth-fe [ACK]
     16 0.422518    mythandroid.local     ofc0.local            TCP      232    38361 > myth-fe [PSH, ACK] GET /
     17 0.422573    ofc0.local            mythandroid.local     TCP      66     myth-fe > 38361 [ACK]
S    18 0.423629    ofc0.local            mythandroid.local     TCP      933    myth-fe > 38361 [PSH, ACK]
     19 0.434243    mythandroid.local     ofc0.local            TCP      66     38361 > myth-fe [ACK]
     20 0.472854    mythandroid.local     ofc0.local            TCP      66     38361 > myth-fe [RST, ACK]

Actual keypress (1,305 bytes):

     21 0.549718    mythandroid.local     ofc0.local            TCP      74     59397 > myth-fe [SYN]
     22 0.549768    ofc0.local            mythandroid.local     TCP      74     myth-fe > 59397 [SYN, ACK]
     23 0.551664    mythandroid.local     ofc0.local            TCP      66     59397 > myth-fe [ACK]
     24 0.552114    mythandroid.local     ofc0.local            TCP      327    59397 > myth-fe [PSH, ACK] GET /Frontend/SendAction?Action=SELECT&Width=0&Height=0
     25 0.552146    ofc0.local            mythandroid.local     TCP      66     myth-fe > 59397 [ACK]
     27 0.552915    ofc0.local            mythandroid.local     TCP      434    myth-fe > 59397 [PSH, ACK]
     30 0.554224    mythandroid.local     ofc0.local            TCP      66     59397 > myth-fe [ACK]
     36 0.697339    mythandroid.local     ofc0.local            TCP      66     59397 > myth-fe [FIN, ACK]
     37 0.697396    ofc0.local            mythandroid.local     TCP      66     myth-fe > 59397 [FIN, ACK]
     38 0.700618    mythandroid.local     ofc0.local            TCP      66     59397 > myth-fe [ACK]
```

**Comment by billmeek** [comment]
This is what I'm testing now. it saves 4 messages and 3,183
bytes each time isMasterBackendConnected is used. Just
going to the Status screen uses isMasterBackendConnected
9 times (a 28,647 bytes savings.).

``` diff
--- a/src/org/mythtv/service/util/NetworkHelper.java
+++ b/src/org/mythtv/service/util/NetworkHelper.java
@@ -116,7 +116,7 @@ public class NetworkHelper {
        }

         try {
-            final URL url = new URL( profile.getUrl() );
+            final URL url = new URL( profile.getUrl() + "Myth/GetHostName" );

```

The only downside I see is that if the endpoint changes, it will
start failing. That should only happen during a new version of
MythTV and would show up in initial testing.

**Comment by dmfrey** [comment]
I think what you are seeing with the BackendStatusFragment is after it gets back status results, it then calls all the individual services to get channels, recorded, upcoming and program guide which are service intents, each of which does a check against the backend to make sure it is up and running before making a call to get their respective data.  These intent services are made to be run in isolation which is why they each call the backend to verify it is awake.

**Comment by billmeek** [comment]
Agreed, and checking that the BE is up is a good thing. My suggestion
is that rather than asking for a 3K response, we should ask for the simplest
thing possible and GetHost was the smallest one I could find.

**Comment by dmfrey** [comment]
In https://github.com/MythTV-Clients/MythTV-Android-Frontend/blob/master/src/org/mythtv/service/util/NetworkHelper.java#L98 it just opens a connection with the server and expects an HTTP 200 coming back.  it doesn't request any data and isn't expecting any.  It just opens and closes the connection.  I am not sure where the extra data coming back is coming from.

**Comment by billmeek** [comment]
Yes, that's exactly it. That request does does cause data to
be returned from the backend. I understand what you're
saying that MAF doesn't use it.

Ah, the speedup I'm addressing isn't MAF but underlying code
and the network.  You can see the diff in the 3 block in this issue.

**Comment by billmeek** [comment]
Closing, via #215 and 98ade5e. Adding bug label, moved back to 1.20.0
