### ISSUE TITLE
Guide: Unregistered Double Tap Listener

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#202]
While swiping through the Upcoming screen, the following
Debug/Information messages were observed. Is this of
any concern?

```
09-29 11:44:14.906: D/AbsListView(2699): [unregisterDoubleTapMotionListener]
09-29 11:44:14.914: I/MotionRecognitionManager(2699):   .unregisterListener : / listener count = 0->0,  
```

Sometimes they fire, usually not. I took care not to double tap,
only swipe. The greatest number seen on one swipe was 12.

**Comment by dmfrey** [comment]
I don't think this is an issue for the app. Those aren't anything that we are doing with the code.

**Comment by billmeek** [comment]
OK, re: unregisterListener, it only happens on my 4.1.2 tablet and
LogCat doesn't save it, but the application is: org.mythtv. I'll close 
it.
