### ISSUE TITLE
NPE in BackendStatusService

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#206]
Note that I have my NetworkHelper isMasterBackendConnected
change that adds GetHostName active.

Went to Recordings screen, notices LogCat had
stopped with this:

```
09-30 15:45:32.716: D/BackendStatusService(12322): onHandleIntent : enter
09-30 15:45:32.846: I/BackendStatusService(12322): onHandleIntent : DOWNLOAD action selected
09-30 15:45:32.856: E/BackendStatusService(12322): onHandleIntent : error
09-30 15:45:32.856: E/BackendStatusService(12322): java.lang.NullPointerException
09-30 15:45:32.856: E/BackendStatusService(12322):  at org.mythtv.service.status.BackendStatusService.onHandleIntent(BackendStatusService.java:59)
09-30 15:45:32.856: E/BackendStatusService(12322):  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
09-30 15:45:32.856: E/BackendStatusService(12322):  at android.os.Handler.dispatchMessage(Handler.java:99)
09-30 15:45:32.856: E/BackendStatusService(12322):  at android.os.Looper.loop(Looper.java:137)
09-30 15:45:32.856: E/BackendStatusService(12322):  at android.os.HandlerThread.run(HandlerThread.java:60)
09-30 15:45:32.856: V/BackendStatusService(12322): sendCompleteNotConnected : enter
09-30 15:45:32.856: V/BackendStatusService(12322): sendCompleteNotConnected : exit
09-30 15:45:32.856: D/BackendStatusService(12322): onHandleIntent : exit
09-30 15:45:48.436: D/BackendStatusService(12322): onHandleIntent : enter
09-30 15:45:48.456: I/BackendStatusService(12322): onHandleIntent : DOWNLOAD action selected
09-30 15:45:48.456: D/BackendStatusHelperV27(12322): process : enter
09-30 15:45:48.516: V/BackendStatusHelperV27(12322): downloadBackendStatus : enter
09-30 15:45:48.686: D/dalvikvm(12322): GC_CONCURRENT freed 1771K, 20% free 8896K/11079K, paused 2ms+5ms
09-30 15:45:48.916: D/dalvikvm(12322): GC_CONCURRENT freed 1257K, 20% free 8919K/11079K, paused 3ms+3ms
09-30 15:45:49.146: D/dalvikvm(12322): GC_CONCURRENT freed 1242K, 20% free 8956K/11079K, paused 4ms+5ms
09-30 15:45:49.326: D/dalvikvm(12322): GC_CONCURRENT freed 1321K, 20% free 8915K/11079K, paused 4ms+3ms
09-30 15:45:49.606: D/dalvikvm(12322): GC_CONCURRENT freed 874K, 17% free 9285K/11079K, paused 2ms+3ms
09-30 15:45:49.796: V/BackendStatusHelperV27(12322): updateProgramGuide : enter
09-30 15:45:49.826: V/BackendStatusHelperV27(12322): updateProgramGuide : exit
09-30 15:45:49.826: V/BackendStatusHelperV27(12322): convertBackendStatus : enter
09-30 15:45:49.826: V/BackendStatusHelperV27(12322): convertBackendStatus : exit
09-30 15:45:49.826: D/BackendStatusHelperV27(12322): process : exit
09-30 15:45:49.826: V/BackendStatusService(12322): sendComplete : enter
09-30 15:45:49.876: V/BackendStatusService(12322): sendComplete : exit
09-30 15:45:49.876: D/BackendStatusService(12322): onHandleIntent : exit
```

**Comment by pot8oe** [comment]
@billmeek I notice the offending line is wrapped in a try catch block which should handle this exception properly. Did the application crash or just print the exception? The exception is written to the log as an error when handled. I am not considering this a bug unless the application crashed or malfunctioned in a user visible way. I'm closing for now and you can reopen if you disagree or experienced a crash related to this exception.

**Comment by billmeek** [comment]
@pot8oe, MAF did not crash. But, I saw something red in
LogCat. Mostly for my own memory, I've been marking
Fatal Errors in the subject and labeling them as critical.
If it's not an error, can you make the red go away?
Leaving the issue closed.

**Comment by pot8oe** [comment]
@billmeek It is red because the exception is being written to the log with
Log.e(); which signifies error. I'll discuss with Dan if he thinks we can
move it to a Warning or Debug message which would change it's color.

-Tom

**Comment by billmeek** [comment]
@dmfrey, @pot8oe, here's a proposal:

If the exception is caught, then don't print the stack. Leave
the Log.e, but make the text say "expected" or "caught" ...

I'm taking the position that if it's not a bug, then the stack
shouldn't print in LogCat. Does that make sense?

I absolutely know I can't remember the acceptable x.java
file names let alone the line numbers of non-failures.

The only 'bad' news is that there are 72 of these in the existing
code. I'm not suggesting a wholesale change, at least for now.

**Comment by pot8oe** [comment]
@billmeek. Good idea. No need to print the whole stack if it's expected.
