### ISSUE TITLE
DB: AIR_DATE stored incorrectly

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#207]
XML Air date is YYYY-MM-DD only, yet there are non-printing
characters in the MAF DB.

``` xml
<Airdate>1998-04-04</Airdate>
```

``` sql
SELECT title,air_date FROM guide WHERE air_date != '';        
The Daily Show With Jon Stewart    2013-09-30T��:��:��             
NCIS                               2013-10-01T��:��:��             
NCIS: Los Angeles                  2013-10-01T��:��:��
...
```

**Comment by dmfrey** [comment]
I thought this was just coming across as text. I will look into it.

**Comment by pot8oe** [comment]
Just looks like questionable times to me. ;-)

**Comment by billmeek** [comment]
@pot8oe, I with it were as easy as corrupt data being passed ;) 

@dmfrey, correct, it does come in as text. All of the entries in
the guide table are like the above. The field is date only in the
MythTV DB and in the XML. It would appear to me that it's getting
stored as DateTime.

It may be a line like this in service/dvr/v27/ProgramHelperV27.java:

``` java
airDate = new DateTime( cursor.getLong( cursor.getColumnIndex( ProgramConstants.FIELD_AIR_DATE ) ) );
```

I don't know where its being used at this time, so I'm marking it as a bug and setting
the milestone for 1.30.0

**Comment by pot8oe** [comment]
@billmeek When I use sqliteman I see 2013-10-01T00:00:00. The field in the DB is TEXT. What are you using to view the SQL results that prints ��:��:�� ? Looks like airDate does not need to be converted to DateTime unless being used in the UI as a Date.

**Comment by billmeek** [comment]
@pot8oe, sqlitebrowser & sqlite3 both show a timestamp
addition to the stored date. I see your point about the 
field in the MAF DB being text. Something's adding a
null timestamp.

I'd say air_date never should be shown as DateTime as it's
only stored in the MythTV DB as a Date.

**Comment by billmeek** [comment]
Perfect. Several were missing dates and they were
also missing in the MythTV DB. Closing.
