### ISSUE TITLE
"Unfortunately, MythTV has stopped" when rotating

### ISSUE THREAD

**Issue by Prefect47** [MythTV-Clients/MythTV-Android-Frontend#21]
0) Keep the phone in portrait mode until step 5.
1) Enter recordings
2) Start playback
3) Press back before the "preparing" dialog has disappeared.
4) Wait until the list reappears.
5) Rotate your phone to landscape.

I've also got the error repeatingly with no chance to press back with some combination of playback, phone rotation, and quickly pressing back before playback starts. The recodings list was showing behind the "unfortunately..." dialog, but every tap on "ok" just produced another one.

Also, a quicker way:
1) Be in recordings list
2) Get an alarm triggered
3) Snooze the alarm

**Comment by dmfrey** [comment]
@Prefect47 is this happening in the default player or one of the external players?  I believe I have run a stream on bs player lite and rotated it with no issue.  If you are using an external player, then it might be an issue with that player.  I would try another player just to be sure. Thanks.

**Comment by rhpot1991** [comment]
@dmfrey Sounds like an issue with onResume in the recordings page.

**Comment by dmfrey** [comment]
@rhpot1991 i will look into it

**Comment by dmfrey** [comment]
@Prefect47 can you check this again with the current development release.  If it is no longer happening, can you close the ticket?

**Comment by dmfrey** [comment]
This does not appear to be happening anymore.  If you find this still occurs, please re-open the ticket and update with your findings.
