### ISSUE TITLE
Usability: Guide screen: Difficulties with 'elevator'

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#210]
Especially on my 7" tablet, the blue elevator is difficult
to grab and conflicts with the Navigation drawer.
(Sometimes I try to grab the elevator and the drawer
starts to come out so I slide it back and try again. This
could be a function of finger size ;) )

This is the elevator on the left side used to rapidly
move to another screen of channels.

Additionally, if a user (ok, me) inadvertently presses the
elevator rather than a channel  while attempting to do a
small scroll e.g. up/down one screen of channels, they are
likely to find themselves on a screen of channels much
farther away than expected.

Finally, the elevator is blue. The same blue used for a
selected channel. Thus, it's 'hidden' and can be grabbed
in error with the same result as the previous paragraph.

I would suggest removing it. Any other observations?

**Comment by dmfrey** [comment]
I am good with removing it.  It is just commenting or deleting the code
that enables FastScroll.

On Tue, Oct 1, 2013 at 3:51 PM, billmeek notifications@github.com wrote:

> Especially on my 7" tablet, the blue elevator is difficult
> to grab and conflicts with the Navigation drawer.
> (Sometimes I try to grab the elevator and the drawer
> starts to come out so I slide it back and try again. This
> could be a function of finger size ;) )
> 
> This is the elevator on the left side used to rapidly
> move to another screen of channels.
> 
> Additionally, if a user (ok, me) inadvertently presses the
> elevator rather than a channel while attempting to do a
> small scroll e.g. up/down one screen of channels, they are
> likely to find themselves on a screen of channels much
> farther away than expected.
> 
> Finally, the elevator is blue. The same blue used for a
> selected channel. Thus, it's 'hidden' and can be grabbed
> in error with the same result as the previous paragraph.
> 
> I would suggest removing it. Any other observations?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/210
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
@dmfrey, if I look at the way the 'channel icons' option was done, I'm
pretty sure I can make a similar one for 'Allow Fast Guide Scrolling' or
better words. Would you like me to add it?

**Comment by dmfrey** [comment]
It is already enabled. That is the only way the scroll bar appears when
fast scroll is enabled. I am good with turning it off. I only turned it on
because I have a lot of channels to go through, but, like you said, it is
more of a problem than it worth. I have also run into those issues as well.

**Comment by billmeek** [comment]
I meant adding an option so users could turn it on/off at will.
I'm working on it just to see if I can pull it off. Folks with bigger
screens might want it.

**Comment by dmfrey** [comment]
Ah, I misunderstood. I get it now. Go for it.
