### ISSUE TITLE
Non Fatal EOFException fired at start of application. API #17

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#212]
Just started MAF and got the following. Non Fatal and I can't
tell if it's caught.

From:

```
src/main/java/org/mythtv/services/api/v027/impl/ChannelTemplate.java
ResponseEntity<ChannelInfoList> responseEntity = restOperations.exchange( buildUri( "GetChannelInfoList", parameters ), HttpMethod.GET, getRequestEntity(etagInfo), ChannelInfoList.class );
```

10-02 11:39:24.392: D/ChannelDownloadService(2918): onHandleIntent : enter
10-02 11:39:24.392: I/ChannelDownloadService(2918): onHandleIntent : DOWNLOAD action selected
10-02 11:39:24.402: V/ChannelHelperV27(2918): process : enter
10-02 11:39:24.562: D/dalvikvm(2918): GC_CONCURRENT freed 1340K, 17% free 8764K/10503K, paused 2ms+3ms
10-02 11:39:24.592: I/ChannelHelperV27(2918): process : response returned HTTP 200
10-02 11:39:24.592: I/ChannelHelperV27(2918): process : videoSourceId = '1'
10-02 11:39:24.592: V/ChannelHelperV27(2918): process : downloading channels
10-02 11:39:24.592: V/ChannelHelperV27(2918): downloadChannels : enter
10-02 11:39:24.772: D/dalvikvm(2918): GC_CONCURRENT freed 1225K, 17% free 8819K/10503K, paused 2ms+4ms
10-02 11:39:24.932: D/dalvikvm(2918): GC_CONCURRENT freed 1237K, 16% free 8861K/10503K, paused 2ms+3ms
10-02 11:39:25.092: D/dalvikvm(2918): GC_CONCURRENT freed 1315K, 16% free 8826K/10503K, paused 2ms+3ms
10-02 11:39:25.232: I/ChannelHelperV27(2918): downloadChannels : GetChannelInfoList returned 304 Not Modified
10-02 11:39:25.292: D/ChannelHelperV27(2918): downloadChannels : exit
10-02 11:39:25.292: I/ChannelHelperV27(2918): process : sleeping 1000 ms
10-02 11:39:26.292: I/ChannelHelperV27(2918): process : videoSourceId = '2'
10-02 11:39:26.432: V/ChannelHelperV27(2918): process : downloading channels
10-02 11:39:26.432: V/ChannelHelperV27(2918): downloadChannels : enter
10-02 11:39:26.592: I/ChannelHelperV27(2918): downloadChannels : GetChannelInfoList returned 304 Not Modified
10-02 11:39:26.652: D/ChannelHelperV27(2918): downloadChannels : exit
10-02 11:39:26.662: I/ChannelHelperV27(2918): process : sleeping 1000 ms
10-02 11:39:27.662: I/ChannelHelperV27(2918): process : videoSourceId = '3'
10-02 11:39:27.682: V/ChannelHelperV27(2918): process : downloading channels
10-02 11:39:27.682: V/ChannelHelperV27(2918): downloadChannels : enter
10-02 11:39:27.842: I/ChannelHelperV27(2918): downloadChannels : GetChannelInfoList returned 304 Not Modified
10-02 11:39:27.922: D/ChannelHelperV27(2918): downloadChannels : exit
10-02 11:39:27.922: V/ChannelHelperV27(2918): downloadVideoSources : exit
10-02 11:39:27.932: D/ChannelDownloadService(2918): onHandleIntent : exit
10-02 11:39:53.952: D/ChannelDownloadService(2918): onHandleIntent : enter
10-02 11:39:53.952: I/ChannelDownloadService(2918): onHandleIntent : DOWNLOAD action selected
10-02 11:39:53.962: V/ChannelHelperV27(2918): process : enter
10-02 11:39:54.172: D/dalvikvm(2918): GC_CONCURRENT freed 1346K, 17% free 8759K/10503K, paused 2ms+2ms
10-02 11:39:54.212: I/ChannelHelperV27(2918): process : response returned HTTP 200
10-02 11:39:54.212: I/ChannelHelperV27(2918): process : videoSourceId = '1'
10-02 11:39:54.222: V/ChannelHelperV27(2918): process : downloading channels
10-02 11:39:54.222: V/ChannelHelperV27(2918): downloadChannels : enter
10-02 11:39:54.392: D/dalvikvm(2918): GC_CONCURRENT freed 1232K, 17% free 8806K/10503K, paused 2ms+3ms
10-02 11:39:54.562: D/dalvikvm(2918): GC_CONCURRENT freed 1238K, 16% free 8848K/10503K, paused 2ms+2ms
10-02 11:39:54.732: D/dalvikvm(2918): GC_CONCURRENT freed 1301K, 16% free 8826K/10503K, paused 2ms+2ms
10-02 11:39:54.882: I/ChannelHelperV27(2918): downloadChannels : GetChannelInfoList returned 304 Not Modified
10-02 11:39:54.932: D/dalvikvm(2918): GC_EXPLICIT freed 648K, 17% free 8791K/10503K, paused 2ms+4ms
10-02 11:39:55.092: D/ChannelHelperV27(2918): downloadChannels : exit
10-02 11:39:55.092: I/ChannelHelperV27(2918): process : sleeping 1000 ms
10-02 11:39:56.092: I/ChannelHelperV27(2918): process : videoSourceId = '2'
10-02 11:39:56.102: V/ChannelHelperV27(2918): process : downloading channels
10-02 11:39:56.102: V/ChannelHelperV27(2918): downloadChannels : enter
10-02 11:39:56.242: I/ChannelHelperV27(2918): downloadChannels : GetChannelInfoList returned 304 Not Modified
10-02 11:39:56.362: D/ChannelHelperV27(2918): downloadChannels : exit
10-02 11:39:56.372: I/ChannelHelperV27(2918): process : sleeping 1000 ms
10-02 11:39:57.372: I/ChannelHelperV27(2918): process : videoSourceId = '3'
10-02 11:39:57.392: V/ChannelHelperV27(2918): process : downloading channels
10-02 11:39:57.392: V/ChannelHelperV27(2918): downloadChannels : enter
10-02 11:39:57.422: E/ChannelHelperV27(2918): process : error
10-02 11:39:57.422: E/ChannelHelperV27(2918): org.springframework.web.client.ResourceAccessException: I/O error: null; nested exception is java.io.EOFException
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:491)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:453)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:429)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at org.mythtv.services.api.v027.impl.ChannelTemplate.getChannelInfoList(ChannelTemplate.java:163)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at org.mythtv.service.channel.v27.ChannelHelperV27.downloadChannels(ChannelHelperV27.java:209)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at org.mythtv.service.channel.v27.ChannelHelperV27.process(ChannelHelperV27.java:120)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at org.mythtv.service.channel.ChannelDownloadService.onHandleIntent(ChannelDownloadService.java:92)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at android.os.Handler.dispatchMessage(Handler.java:99)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at android.os.Looper.loop(Looper.java:137)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at android.os.HandlerThread.run(HandlerThread.java:60)
10-02 11:39:57.422: E/ChannelHelperV27(2918): Caused by: java.io.EOFException
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at libcore.io.Streams.readAsciiLine(Streams.java:203)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at libcore.net.http.HttpEngine.readResponseHeaders(HttpEngine.java:544)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at libcore.net.http.HttpEngine.readResponse(HttpEngine.java:784)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at libcore.net.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:274)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at libcore.net.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:479)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at org.springframework.http.client.SimpleClientHttpResponse.getRawStatusCode(SimpleClientHttpResponse.java:54)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at org.springframework.http.client.SimpleClientHttpResponse.getStatusCode(SimpleClientHttpResponse.java:80)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at org.springframework.web.client.DefaultResponseErrorHandler.hasError(DefaultResponseErrorHandler.java:46)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:477)
10-02 11:39:57.422: E/ChannelHelperV27(2918):   ... 10 more
10-02 11:39:57.422: V/ChannelHelperV27(2918): downloadVideoSources : exit

**Comment by dmfrey** [comment]
I believe this is relate to an existing bug in the Myth Services API https://github.com/MythTV-Clients/MythTV-Service-API/issues/17

The underlying issue seems to be related to something in the android version of the HTTP Client used in android 4.x+.  This doesn't happen in android prior to 3.x.

There is a work around that requires us to send in a HTTP Header "Connection" and set it to "close", however, I believe this will affect network performance.

**Comment by billmeek** [comment]
The Connection header is of interest. Every Services API endpoint
is a new connection. One of the MythTV design choices that I've
seen discussed on their developer's channel. It eats up 7 extra
messages on every message. They're talking about using persistent 
connections in the future.

@dmfrey, if you could tell me where to add the Connection header,
I'd love to test it. It should have no affect on the existing implementation,
but MAY affect the TCP resets I've been seeing.

**Comment by dmfrey** [comment]
@billmeek,

you would need to add to the following file:
https://github.com/MythTV-Clients/MythTV-Service-API/blob/master/src/main/java/org/mythtv/services/api/AbstractOperations.java#L133

The code:

requestHeaders.add( "Connection", "close" );

Then you would have to do the following on the command line: ./gradle
install

Then in your MAF maven.pom file, update the mythtv services api version to
snapshot version that was just installed.  Check your
~/.m2/repository/org/mythtv/android dir for the correct snapshot version if
it doesn't output it for you anywhere.

Let me know if you have any questions.

On Thu, Oct 3, 2013 at 9:15 AM, billmeek notifications@github.com wrote:

> The Connection header is of interest. Every Services API endpoint
> is a new connection. One of the MythTV design choices that I've
> seen discussed on their developer's channel. It eats up 7 extra
> messages on every message. They're talking about using persistent
> connections in the future.
> 
> @dmfrey https://github.com/dmfrey, if you could tell me where to add
> the Connection header,
> I'd love to test it. It should have no affect on the existing
> implementation,
> but MAY affect the TCP resets I've been seeing.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/212#issuecomment-25619139
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
@dmfrey, Good tips. The Servces API is done and the NetworkHelper too.
There's just one place I can't find that's getting the "/" page from the backend.
It may be: java/org/mythtv/services/api/v027/impl/StatusTemplate.java but I
don't know for sure. Do you know how to find the remaining culprit and add
the "Connection", "close" to it?

**Comment by dmfrey** [comment]
All of the templates extend the AbstractOperations class which is where you set that up.  It is calling getRequestEntity which is actually setting that up.

**Comment by billmeek** [comment]
Added the "Connection:", "Close" to:
https://github.com/MythTV-Clients/MythTV-Service-API/blob/master/src/main/java/org/mythtv/services/api/connect/MythAccessFactory.java#L100 and after line 132

There's at least one left. It happens when Content/GetRecordingArtwork is used.
This one's more serious. I've captured protocol where a successful Banner is
conversation is almost done and a 2nd attempt is made to use the same port
by MAF. Of course, the conversation is reset. Could this have something to do
with the Image Loader?
0060  72 6b 3f 54 79 70 65 3d 42 61 6e 6e 65 72 26 49   rk?

**Comment by dmfrey** [comment]
Yes, that would be in the Android Universal Image Loader library.  Might
have to open a ticket with them to get it implemented.  Or possibly fork
their repo, fix it and issue a pull request to get it included.

Have you noticed any network performance issues by adding this to our
network calls?  That was an issue for concern in some of the posts i read.

On Fri, Oct 4, 2013 at 9:27 AM, billmeek notifications@github.com wrote:

> Added the "Connection:", "Close" to:
> 
> https://github.com/MythTV-Clients/MythTV-Service-API/blob/master/src/main/java/org/mythtv/services/api/connect/MythAccessFactory.java#L100and after line 132
> 
> There's at least one left. It happens when Content/GetRecordingArtwork is
> used.
> This one's more serious. I've captured protocol where a successful Banner
> is
> conversation is almost done and a 2nd attempt is made to use the same port
> by MAF. Of course, the conversation is reset. Could this have something to
> do
> with the Image Loader?
> 0060 72 6b 3f 54 79 70 65 3d 42 61 6e 6e 65 72 26 49 rk?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/212#issuecomment-25698231
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by dmfrey** [comment]
mythtv-services-api-1.0.5 released to maven central
