### ISSUE TITLE
DB: Channel table has one channel that isn't visible (trivial)

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#213]
Channels marked as visible=0 in the MythTV DB don't
normally appear in the MAF DB.

2143 shows up even though in the MythTV DB it is marked
with visible=0. 2143 is also the last channel in the unsorted
MAF list of channels. It's not last in the XML.

```
http://mc0:6544/Channel/GetChannelInfoList?SourceID=2
returns <Visible>false</Visible> for 2143.
```

**Comment by dmfrey** [comment]
do you have any recorded programs that were recorded on this channel, but this channel is no longer visible?

**Comment by billmeek** [comment]
Yes, one. I'll mark this closed, invalid. Let me know if it should be otherwise.
