### ISSUE TITLE
Guide: Reconsider display of time blocks at top of screen

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#222]
It's just as easy to scroll through 48 half hour listings
as it ti to scroll through the time blocks and click on
one. Consider not displaying the blocks for screens
with a small number of listings. Let's start with 48 as
the definition of a small number

Additionally, if time blocks are displayed and one is
selected, it should be highlighted like the channel
blocks are.

**Comment by dmfrey** [comment]
I think i am going to just turn off the upper time slots for the time being
