### ISSUE TITLE
Forced Close while loading recordings

### ISSUE THREAD

**Issue by yunosh** [MythTV-Clients/MythTV-Android-Frontend#23]
If going to recordings, a few seconds after the spinner starts, I get a FC and am dumped back to the start screen.

**Comment by dmfrey** [comment]
@yunosh  what phone/tablet are you using?  What version of android?  Would it be possible to get a logcat of your exceptions and email it to me?

**Comment by dmfrey** [comment]
@yunosh can you try it again with the new dowload i placed out there today?  Also, post your phone/tablet and android version.  If all is well, please close the issue.

Thanks.

**Comment by dmfrey** [comment]
@yunosh with the latest development version, are you still seeing this issue?  If you are, please update the ticket.  If not, please close it.

Thank you.

**Comment by dmfrey** [comment]
@yunosh Closing the issue for now.  If this issue is still occurring, please re-open the issue and update it with your findings.
