### ISSUE TITLE
Beta test comment. Should MAF play archived LiveTV

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#232]
Design discussion.

LiveTV is detected by looking at the record group. A user on the beta test
G+ site has recordings that were live and has archived them.

Obviously, they don't display.

I don't see any reason why this shouldn't be allowed. Additionally, I know
the reason for NOT doing live TV has been that the MythTV Services API
doesn't support it. In reality, it's just another file, so what prevents us from
doing it? It could be that an 'in-progress' recording can't be transcoded.

This is a frequent complaint and likely the cause of lower than deserved
ratings.

**Comment by dmfrey** [comment]
Live TV for some reason exists in the GetRecordedList.  I would be
interested to know how the user is archiving them.  I am not sure I care
why, but seems odd to me to want to do this when you can just as easily hit
the Record button on the remote.  Not for this list.

The problem I see it is that LiveTV Programs can be deleted at the
discretion of the backend.  So we might be showing it, but the recording no
longer exists.

We should probably mark an episode as Recording and prevent certain actions
from being able to be performed on it.  I am thinking native live playback
would work, but i don't believe HLS can be performed while it is recording.

On Mon, Oct 14, 2013 at 12:50 PM, billmeek notifications@github.com wrote:

> Design discussion.
> 
> LiveTV is detected by looking at the record group. A user on the beta test
> G+ site has recordings that were live and has archived them.
> 
> Obviously, they don't display.
> 
> I don't see any reason why this shouldn't be allowed. Additionally, I know
> the reason for NOT doing live TV has been that the MythTV Services API
> doesn't support it. In reality, it's just another file, so what prevents
> us from
> doing it? It could be that an 'in-progress' recording can't be transcoded.
> 
> This is a frequent complaint and likely the cause of lower than deserved
> ratings.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/232
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by tafypz** [comment]
@billmeek technically nothing stops anybody to do "livetv" with the services api, as you mentioned it is just a chain of recordings as opposed to the old ringbuffer. Here is the problem with true livetv, the server requires some type of registration via the protocol of a frontend, then this frontend can kick off a livetv stream by hooking to a free recorder.
However for this livetv stream to continue being written to the disk the registered frontend needs to stay up. If the frontend doesn't stay up then the backend will stop writing to the file. The easiest way to see the behavior is to run mythfrontend, start live tv and then kill -9 mythfrontend. the backend will stop the recording... (unless I am mistaken)

**Comment by tafypz** [comment]
@dmfrey LiveTV show up under the LiveTV storage group, pulling all recordings regardless of storage group will pull livetv ones as well.

**Comment by tafypz** [comment]
@dmfrey you are correct, the current implementation of HLS does not run on livetv or in-progress recordings

**Comment by dmfrey** [comment]
Correct, and currently I am throwing away anything in LiveTV recording Group

On Mon, Oct 14, 2013 at 1:01 PM, Sebastien Astie
notifications@github.comwrote:

> @dmfrey https://github.com/dmfrey you are correct, the current
> implementation of HLS does not run on livetv or in-progress recordings
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/232#issuecomment-26271155
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
Made a LiveTV recording from MythTV. Pressed 'r'. Checked the MythTV DB
and found the record group had changed from LiveTV to Default. Which does
get displayed in MAF. Closing.
