### ISSUE TITLE
Recordings: Not getting a choice between Direct and HTTP Live Stream

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#236]
Press See icon, no ProgressDialog allows choice between Live and Stream.
Opening as a question. Episode had NOT been transcoded before.
Is this correct?

**Comment by dmfrey** [comment]
hmm, i get the Use HLS? dialog. Was this episode currently hls transcoding?  When you are on your home network, you should get the option to play native or via hls with the Use HLS? dialog.  If you were away, then the only option will be to use HLS, so no dialog should be presented.

**Comment by billmeek** [comment]
Closing. I was testing using the Away profile.
