### ISSUE TITLE
Prevent TCP resets if error text received by Android Universal Image Loader isn't read

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#246]
Solution provided by Image Loader developer: nostra13/Android-Universal-Image-Loader/issues/418.

**Comment by dmfrey** [comment]
Did he push an updated version?

**Comment by billmeek** [comment]
No, his comment after the proposed solution is: "But I decided not include these changes into library."
Which I don't understand, as it's a valid issue. Perhaps most users of his app don't return the text that
the MythTV Services API does. Or, most people don't search the protocol for RSTs.

**Comment by dmfrey** [comment]
I looked at koush's Ion library for another project. You can find it on
github. Might be a better fit for what we are doing.

**Comment by billmeek** [comment]
I cloned the koush Ion library, but I can't spot the solution there.

However, citing: http://docs.oracle.com/javase/6/docs/technotes/guides/net/http-keepalive.html,
(probably the section: What can you do to help with Keep-Alive?)
nostra13 has reopened the issue and added 2 commits. I can't install the SNAPSHOT
because my version of maven is too old. I'll work on that.

The section just below the above says that: Changes in Java SE 6 will read up to 512 bytes
(by default and configurable for more/less.)

**Comment by billmeek** [comment]
Got my system updated and built 1.9.2-SNAPSHOT. TCP RSTs are gone.
I added a comment on his issues list, so hopefully he'll push to maven 
central. There are a few changes required in MAF to allow this to build.
I'll push them to 1.30 when 1.9.2 is pushed, like these:

``` diff
-import com.nostra13.universalimageloader.core.assist.PauseOnScrollListener;
-import com.nostra13.universalimageloader.core.assist.SimpleImageLoadingListener;
+import com.nostra13.universalimageloader.core.listener.PauseOnScrollListener;
+import com.nostra13.universalimageloader.core.listener.SimpleImageLoadingListener;
```

**Comment by billmeek** [comment]
1.9.2 was published on 23-May-2014. Working on some depricated warnings.

**Comment by billmeek** [comment]
Commit didn't close this one? But I will here.
