### ISSUE TITLE
Abstract out the MythTV Api Services

### ISSUE THREAD

**Issue by sherzberg** [MythTV-Clients/MythTV-Android-Frontend#25]
EDIT:

Would you guys be willing to separate out the API Services to a separate jar by either moving the source to another git repo? Or perhaps refactor all of the code to use a maven module for the android source and a maven module for the api service code? I would be more then willing to help.

**Comment by dmfrey** [comment]
@whelmingbytes it is on the list of things to do.  The project originally started as a maven project,  but there were issues getting it working in environments other than my own. If you like,  feel free to take a stab at abstracting the myth services api out and do a pull request to get the changes applied. We would want to add the new api project into this github organization. Let me know what you think.

**Comment by dmfrey** [comment]
@whelmingbytes also, one of the tasks is to create unit tests for all these apis.  I want to be able to test the apis directly, the apis as a part of the new content provider services i have been adding.

There will also be a need to add ETag support as well as GZip compression.  I previously added gzip, but it had some issues in one of the support libraries i was using.  I believe that has been resolved now, so i will need to add that back in.

**Comment by sherzberg** [comment]
@dmfrey I started work on it, but ran into some maven-android-plugin issues. I posted about it here: https://groups.google.com/forum/?fromgroups#!topic/maven-android-developers/LUXvzIvw-Qs to see if I could get some help. I was thinking that maybe it was due to the api services jar was dependent on android for logging. 

Just to confirm, you want a new git repo for the api services? That may make it easier, as I have it as a maven module in the current repo.

**Comment by dmfrey** [comment]
@whelmingbytes yes, I figure we can create a new git repo housed along side the main application.  I can create one here, or you might be able to transfer yours over to this github organization.  Keep one place for anyone to access either the lib or main application.

If the logging dependency becomes a problem, feel free to remove it.  Could probably replace it with just java.logging.

**Comment by dmfrey** [comment]
@whelmingbytes One more thing to note, be sure to do regular pulls as I am still modifying some of those api calls.

**Comment by tafypz** [comment]
I created a repository using your code and keeping only the service api portion. The only thing I modified is the logging in AbstractOperations to use java.util.logging.Logger instead of android.util.Log directly. There are 2 branches, master is android based (android spring framework); "java" is J2SE based and uses the J2SE 7 spring framework libraries ...
Feel free to use it anyway you want.
I also used the main/java test/java structure so that people using gradle or maven don't have to customize their script

**Comment by dmfrey** [comment]
@tafypz Thank you for this.  Can you contribute it to our github repository?  I think we can create a separate repo just for this in here so we can keep everything in one place.

Also, have you kept your code up to date with any recent changes we made to the services api?

**Comment by tafypz** [comment]
the code is up to date as of  last night, so it is exactly the same as what you have (not counting the logging change)...
I can contribute that to your github repo, would you like me to do a transfer ?

**Comment by dmfrey** [comment]
That would be great if you could transfer it over.  I will add you to the project if you like as well.

**Comment by tafypz** [comment]
sure you can add me to the project, I am planning on doing the MythTV GoogleTV integration (like what dish network has)  via their "device controller API" as soon as they make the API public...

**Comment by dmfrey** [comment]
@tafypz actually, one of the goals we have is make this app available on googletv as well as phones and tablets.  This would be great if we can all base off of a single code base and reach all platforms.

**Comment by tafypz** [comment]
sounds like a plan to me

**Comment by dmfrey** [comment]
I think i need your email address in order to add you to the team. can you send it to me at gmail?

**Comment by tafypz** [comment]
Thanks, i transferred the repository
On Aug 6, 2012 12:39 PM, "Daniel Frey" <
reply@reply.github.com>
wrote:
