### ISSUE TITLE
Shows programs but no episodes

### ISSUE THREAD

**Issue by cormanaz** [MythTV-Clients/MythTV-Android-Frontend#252]
I've got the Play Store release installed on a Galaxy Note 10.1 2014, talking to a new install of the latest Mythbuntu as a backend.  It seems to talk to the backend fine.  Shows the guide, and give a list of programs.  But when I touch one of the programs it shows no episodes.  What to do?

**Comment by billmeek** [comment]
Closing this issue because it's being addressed on the MythTV -users mailing list where it was asked (and answered) before this was  posted. See: http://www.gossamer-threads.com/lists/mythtv/users/565179 . Feel free to reopen if that thread wasn't created by you.
