### ISSUE TITLE
Recordings start to play then stop

### ISSUE THREAD

**Issue by bazzawill** [MythTV-Clients/MythTV-Android-Frontend#26]
When I select a recording it start to play then stops and goes back a blank screen of the mythtv app. I have tried this with both the stock android player and mx player. BS player comes up loading forever.

I have a htc desire running ics 

and I am using a dvb-t card

**Comment by dmfrey** [comment]
@bazzawill can you try this again and update this issue with your findings.  If it is no longer occurring, please close the ticket.

**Comment by dmfrey** [comment]
@bazzawill closing this issue for now.  If the issue still persists, please reopen the ticket.
