### ISSUE TITLE
No release to playstore

### ISSUE THREAD

**Issue by netmindz** [MythTV-Clients/MythTV-Android-Frontend#261]
Is there any reason why there hasn't been a release to the playstore since 2013 ?

**Comment by netmindz** [comment]
No comment ?

**Comment by dmfrey** [comment]
Sorry, I was away on vacation last week.

It has really come down to timing. I had 3 major migrations at work over
the last year. My time was really thin between work and family. I am
finishing a few things up for some other projects and will be back on this.

**Comment by netmindz** [comment]
You might like to check out my fork, in an attempt to help get my head round how the app works, make it easier to develop for and remove duplication, I have replaced all of the classes that relate to the myth api with the classes provided with the ones that are already present in https://github.com/MythTV-Clients/MythTV-Service-API

In the interest of speed, I have also swapped to v27 only given it's over a year old, so users should really have updated by now given we are on the 4th release of v27

Everything I tried appears to be working, bar the backend status page that just sits there leading for ever, but as that is the page i'm using the status.beans package, there is probably just some minor oversight there

**Comment by dmfrey** [comment]
Where is your fork?

I have been considering using Square Retrofit to annotate the the classes
and endpoints in java.  My hope is to be able to avoid having all these
versions of the api lying around, as it really complicates coding the
interface to the correct version.

On Thu, Oct 23, 2014 at 8:58 AM, netmindz notifications@github.com wrote:

> You might like to check out my fork, in an attempt to help get my head
> round how the app works, make it easier to develop for and remove
> duplication, I have replaced all of the classes that relate to the myth api
> with the classes provided with the ones that are already present in
> https://github.com/MythTV-Clients/MythTV-Service-API
> 
> In the interest of speed, I have also swapped to v27 only given it's over
> a year old, so users should really have updated by now given we are on the
> 4th release of v27
> 
> Everything I tried appears to be working, bar the backend status page that
> just sits there leading for ever, but as that is the page i'm using the
> status.beans package, there is probably just some minor oversight there
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/261#issuecomment-60234337
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey
