### ISSUE TITLE
'About' page should show info about currently installed app

### ISSUE THREAD

**Issue by askvictor** [MythTV-Clients/MythTV-Android-Frontend#262]
The 'about' section of an app/application should show info about the currently installed app (e.g. full name, website, version, developer), not just redirect to a webpage. I've found it surprisingly difficult to determine the version number of the installed version of this app.

**Comment by billmeek** [comment]
Hi,
The next release (currently available to beta users) has the version displayed on the
navigation drawer. The help area has been enhanced, however continues to use links
to the Wiki.
