### ISSUE TITLE
Persistent 'Receiving Recording Rules

### ISSUE THREAD

**Issue by admered1** [MythTV-Clients/MythTV-Android-Frontend#263]
The notification pops up at startup and stays.
Thanks for the great app. Very nice :-)

**Comment by billmeek** [comment]
Hi,

What version are you running e.g. 1.10.x or 1.20.x (guessing 1.10.x because I don't see that
message.) You might want to try the 1.20 beta: https://play.google.com/apps/testing/org.mythtv

**Comment by admered1** [comment]
On 09/10/14 20:03, billmeek wrote:

> Hi,
> 
> What version are you running e.g. 1.10.x or 1.20.x?

Sorry, should have said. V 1.10

Can't find any way of asking the app for the version though so going on
the comments in the appstore page.

Happy to try the beta

Andy M

## 

This message has been scanned for viruses and
dangerous content by MailScanner, and is
believed to be clean.

**Comment by billmeek** [comment]
Good. The link above should get you going. The only 'downside' is that 
in order to use Google's Beta apps, you must be a Google Group member.
The link above should work and the Group is here:
https://plus.google.com/communities/104432707624078706786
There hasn't, and likely won't be any development on 1.10. Please 
reopen if 1.20 doesn't help.

**Comment by admered1** [comment]
On 10/10/14 12:52, billmeek wrote:

> Good. The link above should get you going. The only 'downside' is that
> in order to use Google's Beta apps, you must be a Google Group member.
> The link above should work and the Group is here:
> https://plus.google.com/communities/104432707624078706786
> There hasn't, and likely won't be any development on 1.10. Please
> reopen if 1.20 doesn't help.

Thanks for that. Have signed up for the beta program, so will expect to
see an update in the near future.

Again, keep up the great work :-)

Andy M

## 

This message has been scanned for viruses and
dangerous content by MailScanner, and is
believed to be clean.
