### ISSUE TITLE
Cannot connect to backend when setting up a profile

### ISSUE THREAD

**Issue by 321liftoff** [MythTV-Clients/MythTV-Android-Frontend#264]
When I connect to my backend running on an ARM-based NAS, I get the following message out of mythbackend:

2014-10-29 21:45:40.932 MythSocket(29c318:46): Protocol error: 'GET /Myt' is not a valid size prefix. 152 bytes pending.

This message appears when trying to connect to either v0.24.4 or v0.25.4.  Meanwhile, the android is stuck on the screen "Please wait....  Retrieving Master Backend Details..."

Any suggestions?

**Comment by billmeek** [comment]
Hi,
MAF doesn't work below 0.25, so 0.24 should fail.  But 0.25 should work. There
are some tips here: https://github.com/MythTV-Clients/MythTV-Android-Frontend/wiki/Connection-Troubleshooting-Guidelines

If you're running 1.10.x from the Play Store, note the Beta version of 1.20.6 is available:
https://play.google.com/apps/testing/org.mythtv .

**Comment by 321liftoff** [comment]
Hi billmeek,

I determined that my problem was typing in the ip address with a port of 6543 instead of 6544.  Using 6544 allows it to connect to v0.25 and it doesn't work with v0.24 as you say.

Thanks for the quick response!
