### ISSUE TITLE
Possible BSPlayer crash on Samsung Galaxy Nexus

### ISSUE THREAD

**Issue by pla1** [MythTV-Clients/MythTV-Android-Frontend#29]
Built from source. 

Attempting to playback NBC Nightly News. BSPlayer appears to crash. Check my LogCat around 07-03 20:00:26.163: A/libc(1650): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1). 

Samsung Galaxy Nexus LogCat - https://docs.google.com/open?id=0B_WwphlQixTbUkZHTXhpOElfVDg

**Comment by pla1** [comment]
Samsung Galaxy Tab has the same behavior. 

Samsung Galaxy Tab LogCat - https://docs.google.com/open?id=0B_WwphlQixTbYVpDRkhaZ1FMQWs (UPDATED link - removed some work related log entries)

**Comment by dmfrey** [comment]
@pla1 do you have the correct bsplayer plugin for your devices?  My galaxy tab has no issues playing the videos.  One other thing to check...is it happening on all videos, or just that one?

Now that I think about it, i think there were a few kids shows that it would happen to as well, but it wasn't for everything.

Does the mythtv for android app appear to be failing or is it just bsplayer lite?  I didn't see any mythtv for android errors in the logs you posted, unless I am missing them.

**Comment by pla1** [comment]
@dmfrey My Samsung Tab was working. I have the BSPlayer FREE with the BSPLayer Armv7 VFP CPU support plug-in installed on both the tab and the Galaxy Nexus. I removed the Arm7 plug-in on the Galaxy Nexus to see if that had something to do with it but I still can't play any videos. Unfortunately BS Player is the only game in town. I will do some more troubleshooting this weekend and let you know how it goes.

**Comment by pla1** [comment]
@dmfrey I think it is a BSPlayer issue. To troubleshoot I changed BSPlayer decoding modem from HW decoding. I tried both SW decoding and System HW decoding. BSPlayer did not crash. I did not play the video either but it didn't crash. I am on BSPlayer lite version 1.3.126. What version of BSPlayer do you have?

**Comment by dmfrey** [comment]
@pla1 actually, there is a commit downstream in myth backend that broke HLS for the time being.

**Comment by pla1** [comment]
@dmfrey OK. Thanks for the heads-up.

**Comment by pla1** [comment]
As a side note I can playback MythTV recordings via BubbleUPnP and BSPlayer on my Samsung Galaxy Nexus. Here is a screenshot of Jimmy Fallon. https://docs.google.com/open?id=0B_WwphlQixTbTnVKRERId05POU0

**Comment by dmfrey** [comment]
Bsplayer is a general purpose media player.

The upper server on myth backend doesn't appear to have been affected by
the HLS bug.
On Jul 7, 2012 10:49 AM, "Patrick L Archibald" <
reply@reply.github.com>
wrote:

**Comment by dmfrey** [comment]
This issue should be resolved now due to backend bug fix

**Comment by pla1** [comment]
@dmfrey Great. I'll give it a shot tonight on my Nexus 7. Thanks, PLA
