### ISSUE TITLE
Episodes are displayed in alphabetical order.

### ISSUE THREAD

**Issue by MarcT** [MythTV-Clients/MythTV-Android-Frontend#30]
Episodes should be displayed in one of 2 ways. Recorded date, or via season/episode based on metadata.
Preferred option would be to display in season/episode order.

**Comment by dmfrey** [comment]
@MarcT The program groups are in alphabetical order, just like the Watch Recordings are listed in a Mythtv Fronted.  The episodes themselves are ordered newest recorded to oldest recorded.  If this is insufficient, please explain why the other way is preferable.

**Comment by MarcT** [comment]
Shows are listed alphabetically yes, but sometimes incorrectly so. I will be creating a new bug for articles at the start of show names placing shows in incorrect positions in the show list.
This issue is that the recorded episodes for a show are not displayed in recorded order, or even reverse recorded order.
For example, For The Mentalist I have 4 recorded shows:
On April 26th I recorded Ruby Slippers (4x21)
May 3rd was So Long, and Thanks for All the Red Snapper (4x22)
On May 10th was Red Rover, Red Rover (4x23)
And on May 17th was The Crimson Hat (4x24)
In my frontend and in mythweb they show in reverse recorded date order, The Crimson Hat is at the top and Ruby Slippers is at the bottom. However in this app they show in alphabetical order ignoring metadata and recorded order.
Red Rover, Red Rover (4x23)
Ruby Slippers (4x21)
So Long, and Thanks for All the Red Snapper (4x22)
The Crimson Hat (4x24)
That's the order they display in MythTV for Android.
The idea of showing them in reverse recorded order is good, and would match myth itself, but I think it would be better for the users if, when metadata is available, you display in order of metadata. That way if a long running show airs a repeat that you missed it shows above/below the rest of the shows so you can watch them in the correct order, as opposed to recorded order.

**Comment by MarcT** [comment]
An example of a long running show that I am not caught up on is CSI: NY. I have not watched Season 8 yet and have a bunch of backdated recordings. For some reason Myth recorded 8x09 on June 22nd when the original air date was Dec 02. I do not know it is out of order when looking in MythTV for Android. Placing this show in the correct position by metadata would be better than leaving it in order of recorded date.
