### ISSUE TITLE
Feature request: resume playback from bookmark

### ISSUE THREAD

**Issue by jesseosby** [MythTV-Clients/MythTV-Android-Frontend#32]
Great app!  I was able to get it working on my Nexus tablet with no issues.  Any chance of having it set/resume bookmarks like the regular frontend on a PC does?  

That is, it'd be great if I could watch half of a show on my PC, set a bookmark where I stopped, then switch over to your app on my tablet and have it resume where I left off - and then optionally set a new bookmark if I stopped watching on the tablet before the show was over.

I realize it's probably an issue of whether the MythTV API supports that or not, but if it does, I'd love to see this added as a feature.  Thank!

**Comment by dmfrey** [comment]
@jesseosby I would love to add this, unfortunately, at this time the Myth Services API does support it. I believe they are considering this and honoring comm flags as well for a future release.  When they add this support, we will add the capability to the app.  Thanks.
