### ISSUE TITLE
Exception with my Samsung Galaxy SII

### ISSUE THREAD

**Issue by hobbes1069** [MythTV-Clients/MythTV-Android-Frontend#34]
Works for browsing recording, but when I pick one I get the following:

Exception
org.springframework.web.client.HttpClientErrorException: 404 Not Found

**Comment by dmfrey** [comment]
@hobbes1069 do you have a full stacktrace that shows which url you are attempting to access that isn't found?  Also, are you using the latest apk or building from source?

**Comment by hobbes1069** [comment]
I just tried the latest apk and also installed BS Player. This time I got something to the effect of "Error opening GetFile."

How would I go about getting the full stacktrace?

**Comment by dmfrey** [comment]
@hobbes1069 looking into this.  I think this is an issue on the backend.

**Comment by hobbes1069** [comment]
I'm running  a pretty recent 0.25.2 build (I'm the RPM Fusion MythTV maintainer). Should I update to the lastest 0.25/fixes?

**Comment by dmfrey** [comment]
@hobbes1069  I have run into this issue as well.  It may be related to the backend, not the app.  Will let you know when I know further.

**Comment by dmfrey** [comment]
@hobbes1069 Can you try MX Player and see if this still occurs.  BS Player was causing this for me as well, and now it appears that BS Player HLS support seems to be broken.  I am closing this issue for now, since it is related to a third party app, but if you are still having trouble with it, please re-open the issue and update with your findings.

**Comment by hobbes1069** [comment]
I tried MX but it doesn't seem to want to work. Say something about not being able to play the file. I worked with Chris P. on the Mythtv side and he got my an APK of BS Player that doesn't have the m3u8 loading issue and it now works.

**Comment by dmfrey** [comment]
On Mon, Oct 8, 2012 at 12:15 PM, Richard notifications@github.com wrote:

> I tried MX but it doesn't seem to want to work. Say something about not
> being able to play the file. I worked with Chris P. on the Mythtv side and
> he got my an APK of BS Player that doesn't have the m3u8 loading issue and
> it now works.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/34#issuecomment-9231011.

Thanks for the update.  Not sure why MX Player isn't working for you.
 Please feel free to close the issue if is no longer a problem.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by hobbes1069** [comment]
Well I just tried MX Player with the google play store version and now it's working... Go figure. 
Looks like it's already closed.
