### ISSUE TITLE
App forces use of internal player

### ISSUE THREAD

**Issue by vendion** [MythTV-Clients/MythTV-Android-Frontend#35]
Using the latest apk when I select a recording to watch using my Xoom running Jelly Bean playback automatically starts in the internal player without prompting if I want it opened with a different player, I also have mxplayer which worked well with the last apk.

**Comment by dmfrey** [comment]
@vendion On my htc one x running ICS, if I swipe down the status bar and select settings, I get an option called "App Associations" where I can edit the Streaming Media Link.  Mine is currently set to BS Player. You should be able to change it there.

The app does not try to set a default player.

**Comment by vendion** [comment]
I do not see that on my Xoom nor my Nexus S running Cyanogenmod 9.1 (ICS
based).  The app used to pop up a system prompt asking what app I want the
video playback done in and that is where I can set the default app which is
still handled by the OS.

**Comment by dmfrey** [comment]
@vendion the app was never doing that explicitly.  That is handled by the OS.  The app has no knowledge of any other apps installed on your devices.  When I execute an activity that requires an external app, and there are more than one installed, the OS will prompt you for which player you want to use.  There should be a way to specify what your default apps are.  Maybe google 'specify default apps on cyanogenmod' or some derivative there of.

One think you may want to try is to delete all the players you installed from the market, then reinstall them.  See if that clears out your default settings for the type of app that gets executed.

**Comment by dmfrey** [comment]
@vendion no update on this issue.  Closing for now. If it is still occurring, please re-open the ticket and update with your current findings.
