### ISSUE TITLE
First Time Users - Click Home, kick off scan for mythtv backend

### ISSUE THREAD

**Issue by dmfrey** [MythTV-Clients/MythTV-Android-Frontend#36]
When a new users launches the app for the first time, and the user clicks the Home button, and no home profiles are created, kick off a zeroconf scan and auto configure the backend.

**Comment by dmfrey** [comment]
@pot8oe can this be looked at as a part of v1.20.0 and the sliding menu enhancement?

**Comment by pot8oe** [comment]
Yes. We should have an initial greeting and jump to adding backend(s).

**Comment by dmfrey** [comment]
backend status page now indicates this in a dialog box when no profiles are configured per home and away profiles
