### ISSUE TITLE
Program Guide doesn't swipe to next day

### ISSUE THREAD

**Issue by tgm4883** [MythTV-Clients/MythTV-Android-Frontend#38]
When swiping late at night, the ProgramGuide will not swipe to the next day (instead it ends at 11:59 PM). While it is simple enough to click the next button to get the next day, this causes two issues.

1) Clicking next to get to the next day takes you back to the current hour it is, rather than the hour you were looking at (or really, the hour you want to look at which would be 12:00 AM)

2) Intuitively, you would expect that swiping when you got to the end of one day to take you to the next day starting at 12:00 AM.

**Comment by billmeek** [comment]
In 1.20.0, the Guide has been reworked and this format is no longer used.
