### ISSUE TITLE
Guide times are incorrect in 0.26

### ISSUE THREAD

**Issue by ldkronos** [MythTV-Clients/MythTV-Android-Frontend#50]
Myth 0.26 has switched to using UTC times for recordings. Because of this, the info in the guide is now incorrect. I see midnight showings being listed at 8PM in the app.

Because this behavior differs between myth versions, if you want to maintain compatability with 0.25 then you will need to detect the myth version and have your code adjust it only if on 0.26 and newer.

**Comment by billmeek** [comment]
I ran 0.26 and am now on 0.27-pre and don't have this problem (I'm in UTC-5.)

Is this still an issue? The MythTV Services API Wiki (http://www.mythtv.org/wiki/Services_API#Proper_use_of_APIs) says that all times are returned in UTC. You can verify your backend's response with:

<pre>
 http://yourHostName:6544/Guide/GetProgramGuide?StartTime=2012-10-22T00:00:00&EndTime=2012-10-31T23:59:59&StartChanId=1000&NumChannels=10
</pre>

The response should include lines like: <StartTime>2012-10-22T23:30:00Z</StartTime> for each program, where the trailing Z indicates that the time is in UTC.

**Comment by dmfrey** [comment]
I upgraded to .26 this morning and checked the program guide specifically
for this issue and have been unable to reproduce it as well.

**Comment by ldkronos** [comment]
I'm not seeing this problem any more. I'm not positive how I originally came to the conclusion it was wrong, but I'm betting I was comparing the app's guide to mythweb. I discovered earlier this week that I forgot to upgrade mythweb (thus running 0.26 backend with 0.25 mythweb) and that was causing the times to be wrong in mythweb. So I incorrectly determined it was your app that was wrong, when it was actually mythweb that was wrong. Sorry for the confusion. Feel free to close this ticket as incorrect.

**Comment by dmfrey** [comment]
@ldkronos Thanks for the update.  I am gonna close the ticket.  If you see anything else let us know.
