### ISSUE TITLE
Mythmote part

### ISSUE THREAD

**Issue by cragon** [MythTV-Clients/MythTV-Android-Frontend#52]
The old mythmote had a section called numbers which included 0-9 backspace an enter.  It also included a keyboard input which is ideal for mythnetvision.

Is it possible this could be included into mythmote within the Andriod client?

TIA

**Comment by pot8oe** [comment]
Yes it can be added. I was trying to make a single screen interface and
excluded the numbers. I'll do a viewpager and put the numbers in a separate
view. Ill have to investigate if the keyboard entry is available through
the services api.

There is always mythmote 1 which will always use the telnet interface. I
plan on giving that a refresh soon and update it to newer android apis.

-Tom

**Comment by pot8oe** [comment]
Closing issue because I added this about a month ago.
