### ISSUE TITLE
Retrieving Video

### ISSUE THREAD

**Issue by outlaws42** [MythTV-Clients/MythTV-Android-Frontend#58]
I can browse my recordings but when I select one to watch.  It just says retrieving Video.  It will do this forever if  I don't  cancel it.   Doesn't give me any kind of error message.   My device is a Samsung Galaxy Player.  I'm Really  looking forward to this app.   Can make cheap android frontends. 

Thanks for all the hard work
Guys

**Comment by dmfrey** [comment]
@outlaws42 Are you running the stock rom or a modded rom on the Samsung Galaxy Player?  What version, etc.

Also, can you tell me a little about your backend?  Have you tried lowering the streaming profile settings?  Also, check your logs to see if there are any errors and post them here if there are.  What version is your mythbackend?

**Comment by outlaws42** [comment]
I am using  the stock rom on my galaxy player.  I am running Gingerbrread.
I  set  the video playback setting to the lowest profile with the same results. 
Not sure what to tell about the backend. Specs? AMD Athlon 2  2.4GHZ  2GB RAM 
I am running .025 on the backend  
If need anymore info just let me know

Here is the last few lines of my mythbackend log file when i  would try to play a video in the app.

Oct 17 03:26:06 frankstv mythbackend[1507]: E HttpServer64 httplivestream.cpp:666 (LoadFromDB) HLS(): Unable to query DB info for stream 47
Oct 17 03:26:12 frankstv mythbackend[1507]: E HttpServer62 httplivestream.cpp:666 (LoadFromDB) HLS(): Unable to query DB info for stream 47
Oct 17 03:26:13 frankstv mythbackend[1507]: E HttpServer62 servicehost.cpp:134 (Invoke) MethodInfo::Invoke - An Exception Occurred: GetFile - FileName missing.
Oct 17 03:26:13 frankstv mythbackend[1507]: E HttpServer62 servicehost.cpp:405 (ProcessRequest) GetFile - FileName missing.
Oct 17 03:26:23 frankstv mythbackend[1507]: E HttpServer64 servicehost.cpp:134 (Invoke) MethodInfo::Invoke - An Exception Occurred: GetFile - FileName missing.
Oct 17 03:26:23 frankstv mythbackend[1507]: E HttpServer64 servicehost.cpp:405 (ProcessRequest) GetFile - FileName missing.
Oct 17 03:26:23 frankstv mythbackend[1507]: E HttpServer62 servicehost.cpp:134 (Invoke) MethodInfo::Invoke - An Exception Occurred: GetFile - FileName missing.
Oct 17 03:26:23 frankstv mythbackend[1507]: E HttpServer62 servicehost.cpp:405 (ProcessRequest) GetFile - FileName missing.
Oct 17 03:26:25 frankstv mythbackend[1507]: E HttpServer64 servicehost.cpp:134 (Invoke) MethodInfo::Invoke - An Exception Occurred: GetFile - FileName missing.
Oct 17 03:26:25 frankstv mythbackend[1507]: E HttpServer64 servicehost.cpp:405 (ProcessRequest) GetFile - FileName missing.
Oct 17 03:26:25 frankstv mythbackend[1507]: E HttpServer62 servicehost.cpp:134 (Invoke) MethodInfo::Invoke - An Exception Occurred: GetFile - FileName missing.
Oct 17 03:26:25 frankstv mythbackend[1507]: E HttpServer62 servicehost.cpp:405 (ProcessRequest) GetFile - FileName missing.
Oct 17 03:26:25 frankstv mythbackend[1507]: E HttpServer62 servicehost.cpp:134 (Invoke) MethodInfo::Invoke - An Exception Occurred: GetFile - FileName missing.
Oct 17 03:26:25 frankstv mythbackend[1507]: E HttpServer62 servicehost.cpp:405 (ProcessRequest) GetFile - FileName missing.
Oct 17 03:26:30 frankstv mythbackend[1507]: I ProcessRequest mainserver.cpp:1360 (HandleAnnounce) MainServer::ANN Monitor
Oct 17 03:26:30 frankstv mythbackend[1507]: I ProcessRequest mainserver.cpp:1362 (HandleAnnounce) adding: frankstv as a client (events: 0)
Oct 17 03:26:30 frankstv mythbackend[1507]: I ProcessRequest mainserver.cpp:1360 (HandleAnnounce) MainServer::ANN Monitor
Oct 17 03:26:30 frankstv mythbackend[1507]: I ProcessRequest mainserver.cpp:1362 (HandleAnnounce) adding: frankstv as a client (events: 1)
Oct 17 03:26:31 frankstv mythbackend[1507]: W HTTPLiveStream httplivestream.cpp:82 (run) HLS(): Command '/usr/bin/mythtranscode --hls --hlsstreamid 48 --verbose general --loglevel info --syslog local7' returned 255

**Comment by dmfrey** [comment]
How up to date is your backend?  This is similar to an issue that was
occurring on the backend a few weeks back.

Also, are you running from the version in the market, building the app
yourself, or the latest download from here?

One more thing, what player are you using?

**Comment by pot8oe** [comment]
Looks like the backend is not serving up the HLS() stream according to the
log.

**Comment by outlaws42** [comment]
I just updated the backend   yesterday.   I tried to watch a recording this morning  when i posted the log file.
I am running the version from the market.  
It never asks what player but i have MX Player Installed

Do you have to do anything to get the backend to serve up the stream. I am running Mythbuntu  12.04.  
I can watch my recordings through mythweb  is this a different stream?

**Comment by dmfrey** [comment]
MX Player has been causing problems lately, much like BS Player is.  Please
try VPlayer or Dice Player.  They seem to work more reliably.

Let me know if that solves your issue.

BTW...HTTP Live Streaming on MythTV is different than watching a video via
mythweb.

On Wed, Oct 17, 2012 at 4:45 PM, Troy Franks notifications@github.comwrote:

> I just updated the backend yesterday. I tried to watch a recording this
> morning when i posted the log file.
> I am running the version from the market.
> 
> It never asks what player but i have MX Player Installed
> 
> Do you have to do anything to get the backend to serve up the stream. I am
> running Mythbuntu 12.04.
> 
> I can watch my recordings through mythweb is this a different stream?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/58#issuecomment-9543113.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by outlaws42** [comment]
Neither  of those players solved the problem.    I will do some more googling and see if for some reason there is something  wrong with backend.

**Comment by billmeek** [comment]
I suspect  pot8oe was referring to the last line of your backend file:

<pre>
 HLS(): Command '/usr/bin/mythtranscode --hls --hlsstreamid 48 --verbose general --loglevel info --syslog local7' returned 255
</pre>

mythtranscode either failed to start, or it aborted.  Start a new session and grep for mythtranscode in /var/log/syslog. If it's working, you'll see lines like:

<pre>
... mythtranscode: 10% Completed @ 27.6789 fps.
</pre>

My percents run from 0 to 99 almost inclusive (sometimes I'll see a number repeat.)  I'm on Mythbuntu 12.04 too, however, I build it from source. If you're doing that, make sure that when you run configure that --enable-libx264 is
added.

It might be helpful if you could pastbin the entire output of mythtranscode.

I'm running Android 4.0.4 Ice Cream Sandwich on a Samsung Galaxy 10.1 and MythTV 0.27-pre on an AMD Athlon(tm) 64 X2 6000+.

**Comment by outlaws42** [comment]
Here is the message i get in my /var/log/mythtv/mythtranscode.log file  when i try to open a video on the App
http://pastebin.com/V0FhSCJS
Not sure what it means but it does seem that mythtranscode is failing.

**Comment by billmeek** [comment]
Good log, thanks. There are 4 checks made by InitForWrite. The last one would have printed an error message (which isn't there.) Unfortunately, the 1st 3 checks only print errors if '--verbose record' is set. You can change that without restarting the backend by typing: mythbackend --setverbose record. Could you please do that, try to play another recording and post the mythtranscode output again?

I expect to see an error message ( E ) with the name of the file that couldn't be written.  Something like:

<pre>/home/mythtv/.mythtv/tmp/hls/2117_20121004030000.mpg.720x544_1000kV_128kA.html
</pre>

Maybe this will just be a permissions problem, e.g. user mythtv can't write to the directory/file reported in the log. The path above is where my HLS goes, but yours could be different. The path may be defined in a Storage Group.

Restore 'normal' logging with: mythbackend --setvebose general (sorry if you already knew that.)

**Comment by outlaws42** [comment]
Here is the new log
http://pastebin.com/8kwRQgEi
Anything new i can learn I'm up for it  so don't worry if your telling me something I might already know. 
Thanks so much for your help.
Troy

**Comment by billmeek** [comment]
Line 7 in your pastebin is the answer. It says mythtranscode is trying to write to /, which it can't (and never should.) Since /home/mythtv/.mythtv/tmp/hls/... isn't being used, that suggests that there is a Streaming Storage Group built, perhaps automatically by Mythbuntu. Use mythtv-setup to put a valid directory in the Streaming group. A popular choice would be /var/lib/mythtv/streaming and that directory must have an owner/group of mythtv/mythtv with permissions of 775.

Good luck.

**Comment by dmfrey** [comment]
Yes, I am not sure why i didn't think of this before.  If you upgraded from
.24 to .25, you needed to manually go in and add this storage group in
mythtv-setup.  However, if you installed .25 fresh, you would not need to
add the directory.

I think we should maybe make note of that in the readme as well.

On Mon, Oct 22, 2012 at 6:21 PM, billmeek notifications@github.com wrote:

> Line 7 in your pastebin is the answer. It says mythtranscode is trying to
> write to /, which it can't (and never should.) Since
> /home/mythtv/.mythtv/tmp/hls/... isn't being used, that suggests that there
> is a Streaming Storage Group built, perhaps automatically by Mythbuntu. Use
> mythtv-setup to put a valid directory in the Streaming group. A popular
> choice would be /var/lib/mythtv/streaming and that directory must have an
> owner/group of mythtv/mythtv with permissions of 775.
> 
> Good luck.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/58#issuecomment-9683048.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by outlaws42** [comment]
I am looking at the Storage Groups in mythsetup and it doesn't have one for streaming.  Can i just create one? and how would know to use it?  

I think i did upgrade from .24 but im not sure.

**Comment by dmfrey** [comment]
I believe it is just called 'streaming'.  Just point it to
/var/lib/mythtv/streaming.  Make sure that you have write access to that
directory.

On Mon, Oct 22, 2012 at 6:38 PM, Troy Franks notifications@github.comwrote:

> I am looking at the Storage Groups in mythsetup and it doesn't have one
> for streaming. Can i just create one? and how would know to use it?
> 
> I think i did upgrade from .24 but im not sure.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/58#issuecomment-9683480.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
On 10/22/2012 05:24 PM, Daniel Frey wrote:

> Yes, I am not sure why i didn't think of this before.  If you upgraded from
> .24 to .25, you needed to manually go in and add this storage group in
> mythtv-setup.  However, if you installed .25 fresh, you would not need to
> add the directory.

Dan;

Is that a Mythbuntu'ism? I've been building from source since 0.24.

Until today, I never had a Streaming Storage Group but it is one of the built in
Storage Groups MythTV uses. It forms the path automatically with either $HOME or
$MYTHCONFDIR + /.mythtv/tmp/hls. Thats where my streaming files were going.

I did add the Streaming group today as a test - to make sure it no longer wrote
to the default place.

The name I used for the group is in fact Streaming. That matches the name in the
Storage Group code.  I never tried it with a lower case s.

**Comment by dmfrey** [comment]
Bill,

I recall talking to rhpot1991 about it when I was first doing my upgrade.
 After setting it, it wall worked.  Maybe since you were building from
source, it was already being taken care of.  But the traditional upgrade
path via apt-get was not doing this automatically.  Yes, it is a mythbuntu
issue.

Dan

On Mon, Oct 22, 2012 at 6:51 PM, billmeek notifications@github.com wrote:

> On 10/22/2012 05:24 PM, Daniel Frey wrote:
> 
> > Yes, I am not sure why i didn't think of this before. If you upgraded
> > from
> > .24 to .25, you needed to manually go in and add this storage group in
> > mythtv-setup. However, if you installed .25 fresh, you would not need to
> > add the directory.
> 
> Dan;
> 
> Is that a Mythbuntu'ism? I've been building from source since 0.24.
> 
> Until today, I never had a Streaming Storage Group but it is one of the
> built in
> Storage Groups MythTV uses. It forms the path automatically with either
> $HOME or
> $MYTHCONFDIR + /.mythtv/tmp/hls. Thats where my streaming files were going.
> 
> I did add the Streaming group today as a test - to make sure it no longer
> wrote
> to the default place.
> 
> The name I used for the group is in fact Streaming. That matches the name
> in the
> Storage Group code. I never tried it with a lower case s.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/58#issuecomment-9683795.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by outlaws42** [comment]
Guys that worked.  The app now works great.  
Thanks for your help.   I am very grateful. Not only is it fixed but I have learned something.
Thanks again for your help
Troy

**Comment by billmeek** [comment]
Troy;

I'd like to see if there is another error message regarding the built in Storage Group. Please try:

<pre>
grep "Error: Could not create builtin" /var/log/mythtv/mythbackend.log
</pre>

Did any  lines print? If there's one for Streaming, please post it here.

**Comment by dmfrey** [comment]
Closes #58

On Mon, Oct 22, 2012 at 7:00 PM, Troy Franks notifications@github.comwrote:

> Guys that worked. The app now works great.
> 
> Thanks for your help. I am very grateful. Not only is it fixed but I have
> learned something.
> Thanks again for your help
> Troy
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/58#issuecomment-9684043.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by outlaws42** [comment]
This is the return
Oct 22 18:48:46 frankstv mythbackend[20187]: E CoreContext storagegroup.cpp:85 (StaticInit) SG() Error: Could not create builtinStorage Group directory '/home/mythtv/.mythtv/tmp/hls' for 'Streaming'

**Comment by billmeek** [comment]
@ outlaws42, check the permissions on the directory above. It must be writable
by the user running the mythbackend, typically, that would be mythtv. Another
way, and perhaps a better way, is to create a Streaming Storage Group, and
choose a directory such as /var/lib/mythtv/streaming. mythtv permissions apply
here too.
