### ISSUE TITLE
Recordings With No Subtitle Repeat the Title for Every Recording

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#59]
On the Recordings screen, "Meet The Press" for example, displays all recordings as
"Meet The Press". I'd suggest it would be more useful to show the date of the show.

Something like this:

<pre>
diff --git a/src/org/mythtv/client/ui/dvr/ProgramGroupFragment.java b/src/org/mythtv/client/ui/dvr/ProgramGroupFragment.java
index 50b4336..60d6bb7 100644
--- a/src/org/mythtv/client/ui/dvr/ProgramGroupFragment.java
+++ b/src/org/mythtv/client/ui/dvr/ProgramGroupFragment.java
@@ -141,7 +141,7 @@ public class ProgramGroupFragment extends MythtvListFragment {
                        
            Program program = programGroups.get( position );
 
-           mHolder.subTitle.setText( !"".equals( program.getSubTitle() ) ? program.getSubTitle() : program.getTitle() );
+           mHolder.subTitle.setText( !"".equals( program.getSubTitle() ) ? program.getSubTitle() : program.getStartTime().toString() );
            mHolder.category.setBackgroundColor( mProgramHelper.getCategoryColor( program.getCategory() ) );
            
            Log.v( TAG, "ProgramGroupRowAdapter.getView : exit" );
</pre>

This works although the recordings are displayed in UTC.

**Comment by pot8oe** [comment]
Good idea to eliminate redundant titles. All times from the backend are in
UTC and need to be converted to local timezone for display.

Thanks,
Tom

**Comment by dmfrey** [comment]
i am making this change now. The fragment has changed from what is
currently in git.  The data behind this is now stored in the db.  I will
read that timestamp and display it.

On Fri, Oct 19, 2012 at 11:06 PM, Thomas G. Kenny Jr <
notifications@github.com> wrote:

> Good idea to eliminate redundant titles. All times from the backend are in
> UTC and need to be converted to local timezone for display.
> 
> Thanks,
> Tom
> On Oct 19, 2012 10:31 PM, "billmeek" notifications@github.com wrote:
> 
> > On the Recordings screen, "Meet The Press" for example, displays all
> > recordings as
> > "Meet The Press". I'd suggest it would be more useful to show the date
> > of
> > the show.
> > 
> > Something like this:
> > 
> > diff --git a/src/org/mythtv/client/ui/dvr/ProgramGroupFragment.java
> > b/src/org/mythtv/client/ui/dvr/ProgramGroupFragment.java
> > index 50b4336..60d6bb7 100644
> > --- a/src/org/mythtv/client/ui/dvr/ProgramGroupFragment.java
> > +++ b/src/org/mythtv/client/ui/dvr/ProgramGroupFragment.java
> > @@ -141,7 +141,7 @@ public class ProgramGroupFragment extends
> > MythtvListFragment {
> > 
> > Program program = programGroups.get( position );
> > - mHolder.subTitle.setText( !"".equals( program.getSubTitle() ) ?
> >   program.getSubTitle() : program.getTitle() );
> > - mHolder.subTitle.setText( !"".equals( program.getSubTitle() ) ?
> >   program.getSubTitle() : program.getStartTime().toString() );
> >   mHolder.category.setBackgroundColor( mProgramHelper.getCategoryColor(
> >   program.getCategory() ) );
> > 
> > Log.v( TAG, "ProgramGroupRowAdapter.getView : exit" );
> > 
> > This works although the recordings are displayed in UTC.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/59>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/59#issuecomment-9627534.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by dmfrey** [comment]
this has been added and will be in the next release.

On Fri, Oct 19, 2012 at 11:08 PM, Daniel Frey dmfrey@gmail.com wrote:

> i am making this change now. The fragment has changed from what is
> currently in git.  The data behind this is now stored in the db.  I will
> read that timestamp and display it.
> 
> On Fri, Oct 19, 2012 at 11:06 PM, Thomas G. Kenny Jr <
> notifications@github.com> wrote:
> 
> > Good idea to eliminate redundant titles. All times from the backend are
> > in
> > UTC and need to be converted to local timezone for display.
> > 
> > Thanks,
> > Tom
> > On Oct 19, 2012 10:31 PM, "billmeek" notifications@github.com wrote:
> > 
> > > On the Recordings screen, "Meet The Press" for example, displays all
> > > recordings as
> > > "Meet The Press". I'd suggest it would be more useful to show the date
> > > of
> > > the show.
> > > 
> > > Something like this:
> > > 
> > > diff --git a/src/org/mythtv/client/ui/dvr/ProgramGroupFragment.java
> > > b/src/org/mythtv/client/ui/dvr/ProgramGroupFragment.java
> > > index 50b4336..60d6bb7 100644
> > > --- a/src/org/mythtv/client/ui/dvr/ProgramGroupFragment.java
> > > +++ b/src/org/mythtv/client/ui/dvr/ProgramGroupFragment.java
> > > @@ -141,7 +141,7 @@ public class ProgramGroupFragment extends
> > > MythtvListFragment {
> > > 
> > > Program program = programGroups.get( position );
> > > - mHolder.subTitle.setText( !"".equals( program.getSubTitle() ) ?
> > >   program.getSubTitle() : program.getTitle() );
> > > - mHolder.subTitle.setText( !"".equals( program.getSubTitle() ) ?
> > >   program.getSubTitle() : program.getStartTime().toString() );
> > >   mHolder.category.setBackgroundColor( mProgramHelper.getCategoryColor(
> > >   program.getCategory() ) );
> > > 
> > > Log.v( TAG, "ProgramGroupRowAdapter.getView : exit" );
> > > 
> > > This works although the recordings are displayed in UTC.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/59>.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/59#issuecomment-9627534.
> 
> ## 
> 
> My Google Profile http://www.google.com/profiles/dmfrey

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
I built the latest version, however when I go to the recordings screen and select
any recording, the application stops.

Full details here: http://paste.ubuntu.com/1293423/

**Comment by dmfrey** [comment]
I  have it fixed, but haven't checked it in. Had to go to a wedding :-)

I will put it in tonight. Had a slight issue with the tablet views but it
is fixed now.

**Comment by dmfrey** [comment]
@billmeek go ahead and do a pull when you can.  Try out the latest change. You should now be able to view the program groups on the tablet.

**Comment by billmeek** [comment]
A-OK (would have said so earlier but I didn't set-up my github notifications correctly.)
