### ISSUE TITLE
Getting Mythmote to work

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#60]
For users failing to get Mythmote to work, I suggest adding text to:

  https://github.com/MythTV-Clients/MythTV-Android-Frontend/blob/master/README

telling users to type mythfrontend --version and make sure that: using_libdns_sd is 
enabled (I had avahi enabled, but the Mythmote still didn't work until I added that library
and recompiled.)

**Comment by dmfrey** [comment]
Bill,

Could you update the readme and issue a pull request on github?

I will merge it in.

Dan

**Comment by billmeek** [comment]
Dan;

I'd be happy to, however, I've not done it before. I see that if I try to edit the file, a fork of the ?entire? project will be created.  After that I can click on Pull Request.

Is this what you had in mind?

Bill

**Comment by dmfrey** [comment]
Bill,

Yes, that should be the process.

Dan
