### ISSUE TITLE
Green and red show titles in the program guide are hard to read

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#62]
I'm running Android 4.0.4 Ice Cream Sandwich on a Samsung Galaxy 10.1 and when I look at the program guide, shows that are marked to record/not record (green/red) are too faint (perhaps too translucent would be more correct) to read. Shows in black or blue are easily read.

I tried (and failed) to change the colors in: src.org.mythtv.client.ui.dvr.GuidePagerFragment.java.

**Comment by dmfrey** [comment]
I will take a look.

Any preference on color?

**Comment by billmeek** [comment]
Thanks, this is what I tried to use:
http://developer.android.com/reference/android/R.color.html#holo_green_dark
but I only 'succeed' in build failures or making the title disappear :)

**Comment by dmfrey** [comment]
what if we invert the colors?  Set text to be white and the background to
be the color?

On Tue, Oct 23, 2012 at 2:30 PM, billmeek notifications@github.com wrote:

> Thanks, this is what I tried to use:
> http://developer.android.com/reference/android/R.color.html#holo_green_dark
> but I only 'succeed' in build failures or making the title disappear :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/62#issuecomment-9712624.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by pot8oe** [comment]
That might work. Also we could do a box outline or an indicator icon like
in myth.

-Tom

**Comment by billmeek** [comment]
I'd be happy to take both of those ideas our for a test drive on my system.
