### ISSUE TITLE
Not deleting re encodes

### ISSUE THREAD

**Issue by liftman** [MythTV-Clients/MythTV-Android-Frontend#64]
after play back finishes, the re encoded files are not always removed from the streaming folder or the database.
this happens always when the player crashes from a broken stream.

would be nice if you could manually clean out the db and streaming directory  in the option section.
i manually do this now in mysql with "truncate livestream;"  then manually delete the files

**Comment by dmfrey** [comment]
We are working on a new episode view and "playlist" view that will allow
for this.

Which player are you using.  The ones that seem to be working the best
right now are:
 VPlayer :
https://play.google.com/store/apps/details?id=me.abitno.vplayer.t&feature=nav_result#?t=W251bGwsMSwxLDMsIm1lLmFiaXRuby52cGxheWVyLnQiXQ..
 DicePlayer :
https://play.google.com/store/apps/details?id=com.inisoft.mediaplayer.a&feature=search_result#?t=W251bGwsMSwxLDEsImNvbS5pbmlzb2Z0Lm1lZGlhcGxheWVyLmEiXQ..

As a side note, you do not need to go directly in the database to remove
live stream recordings.  Just open your browser to
http://backend_ip_address:6544/ then click through to API -> Examples ->
HTTP Live Streaming.  You can just tap the X and kill them there.

On Sun, Oct 28, 2012 at 10:54 AM, liftman notifications@github.com wrote:

> after play back finishes, the re encoded files are not always removed from
> the streaming folder or the database.
> this happens always when the player crashes from a broken stream.
> 
> would be nice if you could manually clean out the db and streaming
> directory in the option section.
> i manually do this now in mysql with "truncate livestream;" then manually
> delete the files
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/64.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by liftman** [comment]
dice player. this was mostly happening over a mobile or non home wifi-
connection, the connection was slow at times and the player would crap out.
vplayer didnt crap out as much(would buffer).
like the app  ;-)
Thanks

**Comment by billmeek** [comment]
Closing after 11 months. The original question was answered in the
2nd comment. Please reopen if necessary.
