### ISSUE TITLE
home and away button stop working when you back out to them.

### ISSUE THREAD

**Issue by liftman** [MythTV-Clients/MythTV-Android-Frontend#65]
in title

**Comment by dmfrey** [comment]
Closes #65

Thank you.  This issue is fixed in git and will be updated on the next
release.

On Sun, Oct 28, 2012 at 10:56 AM, liftman notifications@github.com wrote:

> in title
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/65.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
FYI, Version 1.0.3 is now available.

**Comment by liftman** [comment]
yea i got the update, working good so far haven't seen any issues.
thanks
