### ISSUE TITLE
unable to delete original recording

### ISSUE THREAD

**Issue by liftman** [MythTV-Clients/MythTV-Android-Frontend#66]
not really a problem if it has not a feature
would be nice to delete original recording on server after watching a stream.

**Comment by dmfrey** [comment]
This will be included in the new episode view that is coming in the next
release.

On Sun, Oct 28, 2012 at 10:59 AM, liftman notifications@github.com wrote:

> not really a problem if it has not a feature
> would be nice to delete original recording on server after watching a
> stream.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/66.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by liftman** [comment]
cool cant wait

Thanks

**Comment by dmfrey** [comment]
Closes #66

This is now implemented as of today
