### ISSUE TITLE
android 4.1.2 choosing player

### ISSUE THREAD

**Issue by liftman** [MythTV-Clients/MythTV-Android-Frontend#67]
unable to choose player for "always or just once"

**Comment by dmfrey** [comment]
which players are using?  Which ones are installed on your phone/tablet?

Does it not prompt you the use a player at all?

On Sun, Oct 28, 2012 at 11:40 AM, liftman notifications@github.com wrote:

> unable to choose player for "always or just once"
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/67.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by liftman** [comment]
it does ask for the player, but in android 4.1.2 jelly bean(tablet), the
option to choose a permanent player is not there.   set the default app

Thanks

**Comment by dmfrey** [comment]
Sorry, I had to replace that with a different launcher for now as in lesser
versions, it is not always easy to clear out the default selected player
and choose another one.  I might be able to put some checks in for 4.1.2
and above and have them use the default launcher.

On Sun, Oct 28, 2012 at 12:53 PM, liftman notifications@github.com wrote:

> it does ask for the player, but in android 4.1.2 jelly bean(tablet), the
> option to choose a permanent player is not there. set the default app
> 
> Thanks
> On Oct 28, 2012 12:46 PM, "Daniel Frey" notifications@github.com wrote:
> 
> > which players are using? Which ones are installed on your phone/tablet?
> > 
> > Does it not prompt you the use a player at all?
> > 
> > On Sun, Oct 28, 2012 at 11:40 AM, liftman notifications@github.com
> > wrote:
> > 
> > > unable to choose player for "always or just once"
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > > https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/67>.
> > 
> > ## 
> > 
> > My Google Profile http://www.google.com/profiles/dmfrey
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/67#issuecomment-9847511>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/67#issuecomment-9847592.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by liftman** [comment]
cool
i love the app.
hopefully sometime you will incorporated the ssh and port forwarding into
the mobile choice on the first screen, this would make it wife friendly

Thanks

**Comment by dmfrey** [comment]
Thank you.

That thought has crossed my mind.  I did just start using a library at work
that handles sftp.  So could probably use that to also establish a ssh
tunnel.  Will take some more thought, however.

Also, thought of building our own app to do the actually viewing instead of
having to rely on a third party app.

On Sun, Oct 28, 2012 at 1:10 PM, liftman notifications@github.com wrote:

> cool
> i love the app.
> hopefully sometime you will incorporated the ssh and port forwarding into
> the mobile choice on the first screen, this would make it wife friendly
> 
> Thanks
> On Oct 28, 2012 1:05 PM, "Daniel Frey" notifications@github.com wrote:
> 
> > Sorry, I had to replace that with a different launcher for now as in
> > lesser
> > versions, it is not always easy to clear out the default selected player
> > and choose another one. I might be able to put some checks in for 4.1.2
> > and above and have them use the default launcher.
> > 
> > On Sun, Oct 28, 2012 at 12:53 PM, liftman notifications@github.com
> > wrote:
> > 
> > > it does ask for the player, but in android 4.1.2 jelly bean(tablet),
> > > the
> > > option to choose a permanent player is not there. set the default app
> > > 
> > > Thanks
> > > On Oct 28, 2012 12:46 PM, "Daniel Frey" notifications@github.com
> > > wrote:
> > > 
> > > > which players are using? Which ones are installed on your
> > > > phone/tablet?
> > > > 
> > > > Does it not prompt you the use a player at all?
> > > > 
> > > > On Sun, Oct 28, 2012 at 11:40 AM, liftman notifications@github.com
> > > > 
> > > > wrote:
> > > > 
> > > > > unable to choose player for "always or just once"
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > > > > https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/67>.
> > > > 
> > > > ## 
> > > > 
> > > > My Google Profile http://www.google.com/profiles/dmfrey
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/67#issuecomment-9847511>.
> > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/67#issuecomment-9847592>.
> > 
> > 
> > ## 
> > 
> > My Google Profile http://www.google.com/profiles/dmfrey
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/67#issuecomment-9847715>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/67#issuecomment-9847770.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by liftman** [comment]
internal video would be cool but make sure hardware decoding is in it.
i run a moto 4g xoom with latest android releases (eos stingray roms). have
a 8 core, 16g ram backend.
if you need someone to try beta release let me know.

Thanks

**Comment by dmfrey** [comment]
I would love it if the internal player was better supported, but
unfortunately, it needs some work.  Plus, prior to Honeycomb, there is no
client available other than a third-party app.

Definitely will let you know about testing.  Thanks.

On Sun, Oct 28, 2012 at 1:23 PM, liftman notifications@github.com wrote:

> internal video would be cool but make sure hardware decoding is in it.
> i run a moto 4g xoom with latest android releases (eos stingray roms).
> have
> a 8 core, 16g ram backend.
> if you need someone to try beta release let me know.
> 
> Thanks
> On Oct 28, 2012 1:13 PM, "Daniel Frey" notifications@github.com wrote:
> 
> > Thank you.
> > 
> > That thought has crossed my mind. I did just start using a library at
> > work
> > that handles sftp. So could probably use that to also establish a ssh
> > tunnel. Will take some more thought, however.
> > 
> > Also, thought of building our own app to do the actually viewing instead
> > of
> > having to rely on a third party app.
> > 
> > On Sun, Oct 28, 2012 at 1:10 PM, liftman notifications@github.com
> > wrote:
> > 
> > > cool
> > > i love the app.
> > > hopefully sometime you will incorporated the ssh and port forwarding
> > > into
> > > the mobile choice on the first screen, this would make it wife
> > > friendly
> > > 
> > > Thanks
> > > On Oct 28, 2012 1:05 PM, "Daniel Frey" notifications@github.com
> > > wrote:
> > > 
> > > > Sorry, I had to replace that with a different launcher for now as in
> > > > lesser
> > > > versions, it is not always easy to clear out the default selected
> > > > player
> > > > and choose another one. I might be able to put some checks in for
> > > > 4.1.2
> > > > and above and have them use the default launcher.
> > > > 
> > > > On Sun, Oct 28, 2012 at 12:53 PM, liftman notifications@github.com
> > > > 
> > > > wrote:
> > > > 
> > > > > it does ask for the player, but in android 4.1.2 jelly
> > > > > bean(tablet),
> > > > > the
> > > > > option to choose a permanent player is not there. set the default
> > > > > app
> > > > > 
> > > > > Thanks
> > > > > On Oct 28, 2012 12:46 PM, "Daniel Frey" notifications@github.com
> > > > 
> > > > wrote:
> > > > 
> > > > > > which players are using? Which ones are installed on your
> > > > > > phone/tablet?
> > > > > > 
> > > > > > Does it not prompt you the use a player at all?
> > > > > > 
> > > > > > On Sun, Oct 28, 2012 at 11:40 AM, liftman <
> > > > > > notifications@github.com>
> > > > > > 
> > > > > > wrote:
> > > > > > 
> > > > > > > unable to choose player for "always or just once"
> > > > > > > 
> > > > > > > —
> > > > > > > Reply to this email directly or view it on GitHub<
> > > > > > 
> > > > > > https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/67>.
> > > > > > 
> > > > > > 
> > > > > > ## 
> > > > > > 
> > > > > > My Google Profile http://www.google.com/profiles/dmfrey
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/67#issuecomment-9847511>.
> > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/67#issuecomment-9847592>.
> > 
> > > > ## 
> > > > 
> > > > My Google Profile http://www.google.com/profiles/dmfrey
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/67#issuecomment-9847715>.
> > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/67#issuecomment-9847770>.
> > 
> > 
> > ## 
> > 
> > My Google Profile http://www.google.com/profiles/dmfrey
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/67#issuecomment-9847807>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/67#issuecomment-9847926.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by dmfrey** [comment]
This has been added back.  Now the default choose pops up and allows you to select whichever player you want either Just Once or Always in 4.0+

**Comment by liftman** [comment]
thanks
im running 4.2.2 now- still running good

Thanks

Jay Lang
TK Mobile 614-560-6610
Other 740-807-1238

**Comment by dmfrey** [comment]
This will be available in v1.10
