### ISSUE TITLE
Nothing happens when I click Videos, Music or Pictures

### ISSUE THREAD

**Issue by damnsavage** [MythTV-Clients/MythTV-Android-Frontend#70]
Do you have any documentation for this app? 
Ive just installed it on a samsung galaxy S (v2.3.4 gingerbread), Im on my home network and it automatically found the backend. Mythmote is working fine. 

If I click on Videos, Music or Pictures in the multimedia tab nothing happens. I don't see anything usefull in the /var/log/mythtv/mythbackend.log

Do I need some additional software for the backend? It is already configured to have multiple frontends. I also installed the Vplayer on my phone.

**Comment by dmfrey** [comment]
These functions aren't implemented yet. The text on them is grayed out.
They are upcoming.

**Comment by pot8oe** [comment]
Videos, Music and Pictures are not yet implemented.

**Comment by billmeek** [comment]
Also note that to watch the Services API messages in the backend log,
--verbose upnp must be set. You can change it on-the-fly with:

<pre>
mythbackend --setverbose upnp
</pre>

**Comment by billmeek** [comment]
The Wiki has been updated to reflect the status in the next release. Information
on the current release is correct. Also, in the next release, pressing any of the 
buttons you asked about will result in a message telling a user the feature is
"Coming Soon!"
