### ISSUE TITLE
client doesn't connect at all

### ISSUE THREAD

**Issue by pmattivi** [MythTV-Clients/MythTV-Android-Frontend#72]
I have Samsung GT-S5570 with android 2.2.1, original version.
I installed app from google play and tried to connect to my backend without success.
I added one my home location with this address
http://10.0.0.20:6544/
and it does not work. Scanning network found no servers.
What I tried was changing port to 6543, without success.
My normal HTPC frontend works normally.
Telnet responds on backend server on both ports, 6544 and 6543.
Backend is versin 0.25
What can be wrong?

**Comment by pot8oe** [comment]
What happens if you go to the URL of your backend: http://10.0.0.20:6544/

Do you get the mythbackend web interface? I'm pretty sure telnet should not
be working on port 6544 as it should be responding to HTTP requests.

-Tom

-Tom

**Comment by pmattivi** [comment]
http://10.0.0.20:6544/ gives me html page starting with:
html
head
title
MythTV mythbackend Internal Web Server
/title

**Comment by pot8oe** [comment]
That's good! The backend should be ready and willing to communicate with
the android frontend. Go to the backend URL using your android device's web
browser. This will help determine if the first bullet point below is a
potential issue.
- Is there a firewall running on the backend that may be blocking outside
  connections?
- Is the Android Device using Wifi and on the same network as the backend?
- Is the Selected Home Profile properly set to your manually created
  profile?

Best,
-Tom

-Tom

**Comment by pmattivi** [comment]
- Is there a firewall running on the backend that may be blocking outside connections?
  no firewall issue, that's why I tried telnet client, server gives me response.
- Is the Android Device using Wifi and on the same network as the backend?
  yes, I have only one wifi network at home and I tried to access different services on same server as mythtv and it worked
- Is the Selected Home Profile properly set to your manually created profile?
  yes, I have only one profile of type home, which is set as default

**Comment by pot8oe** [comment]
When you click on the home icon what happens? Do you get the dashboard with
Recordings, Guide, Upcoming, and Recording Rules? Those are the only
implemented items; Videos, Pictures, etc don't work yet.

-Tom

**Comment by pmattivi** [comment]
hmm, I came home yesterday.. and it worked.
I will wait for few days and then make some result.

I hade another issue with playing video stream, but it should not be here I hope.

**Comment by pmattivi** [comment]
BTW I have the same problem while creating new remote connection.
I setup ssh connection using connectbot,
I setup port forwarding,
when I browse on phone to localhost:6544 I get html page from backend,
but when I setup remote profile in mythtv client, I'm not able to connect with message "Master Backend could not be reached. Verify your location profile settings"
maybe it has same point as before, some unusability of "just created profile"

**Comment by pmattivi** [comment]
seems I have an workaroud.
when you setup new profile, you must kill frontend application in processes.
after it, profile is working normally.

**Comment by dmfrey** [comment]
This has been fixed in git. It will be available in the next release.

**Comment by billmeek** [comment]
Please retest with versioin 1.0.3, available on the Play Store as of 11/23/2012. You can reopen this
ticket if necessary.
