### ISSUE TITLE
Corrupts running application stack

### ISSUE THREAD

**Issue by howlett** [MythTV-Clients/MythTV-Android-Frontend#75]
When I start this application, things in my "running applications" stack appear twice.

Way to reproduce:
1. start  some other application
2. start this app
3. press home
4. press and hold home

Bug: the first started app appears twice in the list of opened applications.

I'm running Android 4.1.2 on a Nexus S i9020xxkl1

**Comment by pot8oe** [comment]
I feel like I've seen this bug without running the mythtv frontend app.

-Tom

-Tom

**Comment by dmfrey** [comment]
the app does start up other processes do handle downloading the large
amount of data so as to not interfere with the UI

On Fri, Nov 16, 2012 at 10:03 AM, Thomas G. Kenny Jr <
notifications@github.com> wrote:

> I feel like I've seen this bug without running the mythtv frontend app.
> 
> -Tom
> 
> -Tom
> 
> On Thu, Nov 15, 2012 at 5:27 PM, Liam R. Howlett
> notifications@github.comwrote:
> 
> > When I start this application, things in my "running applications" stack
> > appear twice.
> > 
> > Way to reproduce:
> > 1. start some other application
> > 2. start this app
> > 3. press home
> > 4. press and hold home
> > 
> > Bug: the first started app appears twice in the list of opened
> > applications.
> > 
> > I'm running Android 4.1.2 on a Nexus S i9020xxkl1
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/75>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/75#issuecomment-10449637.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by howlett** [comment]
Yes, but these processes do not get listed in the running application list.  All I know is when I run this app, then everything that was running is duplicated in the list of running apps except this app, which shows up once.  If you know what tasks are started up with this application and have a way I can start the tasks manually, then I am certainly willing to try them one by one to see which one causes this issue.  I have not seen this anywhere else myself, but that's certainly not conclusive.

**Comment by howlett** [comment]
Oh, I noticed that I need to connect to my server to see this.. so there should be another step between 2 and 3 above that should be "connect to a mythtv server".

**Comment by billmeek** [comment]
I'm able to reproduce this ( I think.) Following the 5 steps above, there are 2 MythTV Android Frontend
icons, 1 for the application itself, and one for the video player.

Is that what you're referring to with the "connect to a mythtv server" step added in the last post?

However, I don't need to start another application to see this.

Leaving this open, but please consider retesting on release 1.0.3, which was released today. Thanks.

**Comment by billmeek** [comment]
No response after 30 days. Please consider a retest on version 1.0.4 and
reopen this issue if it still fails. Thanks.
