### ISSUE TITLE
Commercial skip and/or manual skip/fast forward controls

### ISSUE THREAD

**Issue by dreverson** [MythTV-Clients/MythTV-Android-Frontend#76]
I have this working on a Kindle Fire with VPlayer video player.  Mythtv programs stream great but commercial skips are not honored and there doesn't seem to be anyway to manually skip forward/backwards in a recording.  If I restart a video I have to start at the beginning again.  Am I missing how to do this or will it be added in a future release?

Thanks!

**Comment by xavierh** [comment]
in order to be able to seek in the video, the video need to be fully transcoded. unfortunatly mythfrontend for android automatically remove the stream. which is why you are starting at the begining all the time. would be nice to be able to transcode in advance annd go back to it later

**Comment by dmfrey** [comment]
This will be changing in the next release.  You will be able to Pre-transcode by pressing the new + icon in the action bar.  Also, they will no longer be automatically deleted.  There will be an X in the action bar in place of the + once it has been transcoded.  Existing play functionality still works as is, except the stream is not removed automatically anymore.

You should be able to ff/rew depending on your player, but it can be kinda touchy, so use with caution.

Like @xavierh said, commercial skip is not yet supported by HLS on the backend.
