### ISSUE TITLE
Build errors, possible solution.

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#77]
As the project grows, I've been getting errors when attempting to use the
Java Perspective, Run As -> Android Application. The errors aren't always
the same, but the following is typical:

<pre>
Conversion to dalvik format failed unable to execute dex gc overhead limit exceeded
</pre>

I found this: http://stackoverflow.com/questions/9471194/unable-to-execute-dex-gc-overhead-limit-exceeded . By changing lines in eclipse.ini to the following:

<pre>
openFile
--launcher.XXMaxPermSize
512M
-showsplash
org.eclipse.platform
--launcher.XXMaxPermSize
512m
--launcher.defaultAction
openFile
-vmargs
-Dosgi.requiredJavaVersion=1.5
-Xms512m
-Xmx1024m
</pre>

the failures have gone away.

So, with that long setup, the question: is the above a proper solution? If so,
I'd be happy to update the Wiki.

**Comment by dmfrey** [comment]
Yes, this seems like the correct solution.

What type of system are you building on?  I've got a pretty fat dell laptop
with a core i7 (quad-core, eight virtual), 16 gb ram. I do not have these
issues on my system. Although I would imagine you could build this app on a
much smaller machine without issue.

**Comment by billmeek** [comment]
AMD FX(tm)-4100 Quad-Core with 4GB of RAM. I don't have a swap partition.
I just tried again (successfully) with top running and I have about 500KB of RAM
left, eclipse used about 1GB.

I looked in the eclipse menus and didn't find a way to change the settings. So it
appears that manually editing the .ini file is the only solution.

Added a link to this issue in the Wiki.

**Comment by dmfrey** [comment]
I also add some items to mine to take advantage of multiple cores.  Take a
look at mine, specifically after -vmargs:

-vm
/usr/lib/jvm/java-7-openjdk/bin/java
-startup
plugins/org.eclipse.equinox.launcher_1.3.0.v20120522-1813.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.1.200.v20120522-1813
-product
org.eclipse.epp.package.java.product
--launcher.defaultAction
openFile
-showsplash
org.eclipse.platform
--launcher.XXMaxPermSize
256m
--launcher.defaultAction
openFile
-vmargs
-XX:-UseParallelGC
-XX:+AggressiveOpts
-XX:-UseConcMarkSweepGC
-XX:+UseFastAccessorMethods
-Djava.library.path=/usr/lib/jni
-DMAVEN_OPTS="-Xms64m –Xmx128m"
-Xmn128m
-Xss1m
-XX:PermSize=128m
-Dosgi.requiredJavaVersion=1.5
-Dhelp.lucene.tokenizer=standard
-XX:MaxPermSize=384m
-Xms768m
-Xmx1024m

On Sun, Nov 18, 2012 at 10:21 PM, billmeek notifications@github.com wrote:

> AMD FX(tm)-4100 Quad-Core with 4GB of RAM. I don't have a swap partition.
> I just tried again (successfully) with top running and I have about 500KB
> of RAM
> left, eclipse used about 1GB.
> 
> I looked in the eclipse menus and didn't find a way to change the
> settings. So it
> appears that manually editing the .ini file is the only solution.
> 
> Added a link to this issue in the Wiki.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/77#issuecomment-10500284.

## 

My Google Profile http://www.google.com/profiles/dmfrey
