### ISSUE TITLE
Crash if "Recording Rules" is selected and MythTV backend isn't up

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#78]
Running on: mythtv-android-frontend-1.0.2-90-g20a1d12. Apologies if this is
a duplicate of Issue #73.

To duplicate:

<pre>
Make sure the backend isn't accessable
Start the application, select Home->Recording Rules
</pre>

The "Unfortunately, MythTV Android Frontend has stopped message" will
display and after pressing OK the application disappears.

Also note that the 'pulsing download icon' in the lower right of my screen continues
to display until I use the Task Manager to clear RAM.

Log here: http://paste.ubuntu.com/1370688/ the problem starts a line: 915
11-19 12:13:32.344: E/AndroidRuntime(9792): FATAL EXCEPTION: AsyncTask #1

**Comment by dmfrey** [comment]
removing those calls to getHostname now.  Replacing with the NetworkHelper
to check for backend connectivity.

On Mon, Nov 19, 2012 at 1:39 PM, billmeek notifications@github.com wrote:

> Running on: mythtv-android-frontend-1.0.2-90-g20a1d12. Apologies if this is
> a duplicate of Issue #73https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/73
> .
> 
> To duplicate:
> 
> Make sure the backend isn't accessable
> Start the application, select Home->Recording Rules
> 
> The "Unfortunately, MythTV Android Frontend has stopped message" will
> display and after pressing OK the application disappears.
> 
> Also note that the 'pulsing download icon' in the lower right of my screen
> continues
> to display until I use the Task Manager to clear RAM.
> 
> Log here: http://paste.ubuntu.com/1370688/ the problem starts a line: 915
> 11-19 12:13:32.344: E/AndroidRuntime(9792): FATAL EXCEPTION: AsyncTask #1https://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/78.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
Fixed by commit 8218a73. Tested Recordings, Upcoming and Recording Rules
both entering the screen and using the refresh 'circle'.
