### ISSUE TITLE
No "Guide" data displayed

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#81]
Running on: mythtv-android-frontend-1.0.2-93-gd237b65

Before starting this mornings testing, MAF was completely removed,
including all cache and data. Then reinstalled.

However, when I look for Guide data, all I see is:

```
Program Guide is currently downloading
```

I seem to have guide data:

```
http://paste.ubuntu.com/1370838/
```

And the log has this:

```
http://paste.ubuntu.com/1370839/
```

After doing a force stop on the application and deleting all the Guide data,
this is the log showing the new guide being collected but I still get
'Program Guide is currently downloading' displaying again. The download
finished at line 3957 here:

```
http://paste.ubuntu.com/1370879/
```

and the error is at line 4014.

**Comment by dmfrey** [comment]
Bill,

I had to update the myth services api to fix this.  I then deleted my app
and reinstalled and now it seems to be working correctly.  I really need to
get better removing what is installed to test. :)

Dan

On Mon, Nov 19, 2012 at 3:02 PM, billmeek notifications@github.com wrote:

> Running on: mythtv-android-frontend-1.0.2-93-gd237b65
> 
> Before starting this mornings testing, MAF was completely removed,
> including all cache and data. Then reinstalled.
> 
> However, when I look for Guide data, all I see is:
> 
> Program Guide is currently downloading
> 
> I seem to have guide data:
> 
> http://paste.ubuntu.com/1370838/
> 
> And the log has this:
> 
> http://paste.ubuntu.com/1370839/
> 
> After doing a force stop on the application and deleting all the Guide
> data,
> this is the log showing the new guide being collected but I still get
> 'Program Guide is currently downloading' displaying again. The download
> finished at line 3957 here:
> 
> http://paste.ubuntu.com/1370879/
> 
> and the error is at line 4014.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/81.

## 

My Google Profile http://www.google.com/profiles/dmfrey
