### ISSUE TITLE
Title/Timestamps/Detail left on screen when last title of a program is deleted

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#85]
Running on the commit before: mythtv-android-frontend-1.0.2-106-g2a5ce7c

To duplicate:

<pre>
Select any program on the Recordings screen
Select each title and press the delete icon
</pre>

When the last title is deleted, the program will be removed from the list,
however, the last show's details remain.

Clearly, this is not a 1.0.3 showstopper.

**Comment by dmfrey** [comment]
Does this act similarly on phone and tablet?

On Fri, Nov 23, 2012 at 3:10 PM, billmeek notifications@github.com wrote:

> Running on the commit before: mythtv-android-frontend-1.0.2-106-g2a5ce7c
> 
> To duplicate:
> 
> Select any program on the Recordings screen
> Select each title and press the delete icon
> 
> When the last title is deleted, the program will be removed from the list,
> however, the last show's details remain.
> 
> Clearly, this is not a 1.0.3 showstopper.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/85.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
Sorry, I only have an Android tablet. I did retry in the portrait mode (no cover-art)
with the same result.

**Comment by dmfrey** [comment]
still an issue?

**Comment by billmeek** [comment]
Running on: mythtv-android-frontend-1.0.4-26-gf2cd2a0

Short answer: yes.

I had one show with only one episode. When I deleted it, the title (it had no banner)
went away, but the episode detail remained (it had no coverart either.)

A second show had both coverart and a banner and two episodes. When the
one episode was deleted, its detail remained until the remaining episode was
selected. When that episode was deleted, the banner disappeared, but the
detail was left on the screen.

**Comment by dmfrey** [comment]
ah, ok, wasn't considering after delete.  Should be easy enough to fix.

On Thu, Jan 10, 2013 at 4:04 PM, billmeek notifications@github.com wrote:

> Running on: mythtv-android-frontend-1.0.4-26-gf2cd2a0
> 
> Short answer: yes.
> 
> I had one show with only one episode. When I deleted it, the title (it had
> no banner)
> went away, but the episode detail remained (it had no coverart either.)
> 
> A second show had both coverart and a banner and two episodes. When the
> one episode was deleted, its detail remained until the remaining episode
> was
> selected. When that episode was deleted, the banner disappeared, but the
> detail was left on the screen.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/85#issuecomment-12118537.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by dmfrey** [comment]
This has been resolved it the latest commit

d72e7a5
