### ISSUE TITLE
Binder Transaction Too Large

### ISSUE THREAD

**Issue by tekrantz** [MythTV-Clients/MythTV-Android-Frontend#87]
I get an error with recent versions of the MythTV Frontened For Android.

It results in a basically blank screen when selecting the "Recordings" button.

Here is the LogCat showing the issue:

11-26 13:05:22.108: W/AbstractOperations(12063): URI : http://192.168.188.231:6544/Dvr/GetRecordedList
11-26 13:05:22.108: I/AbstractOperations(12063): http://192.168.188.231:6544/Dvr/GetRecordedList
11-26 13:05:22.108: W/AbstractOperations(12063): URI : http://192.168.188.231:6544/Dvr/GetRecordedList
11-26 13:05:22.258: D/dalvikvm(12063): GC_CONCURRENT freed 1005K, 14% free 8453K/9799K, paused 2ms+2ms
11-26 13:05:22.508: D/dalvikvm(12063): GC_CONCURRENT freed 1300K, 17% free 8479K/10119K, paused 2ms+2ms
11-26 13:05:25.538: D/dalvikvm(12063): GC_CONCURRENT freed 1055K, 15% free 8638K/10119K, paused 2ms+2ms
11-26 13:05:26.068: D/dalvikvm(12063): GC_CONCURRENT freed 1013K, 14% free 8893K/10311K, paused 2ms+2ms
11-26 13:05:26.518: D/dalvikvm(12063): GC_CONCURRENT freed 1029K, 14% free 9153K/10567K, paused 2ms+2ms
11-26 13:05:26.968: D/dalvikvm(12063): GC_CONCURRENT freed 1038K, 14% free 9416K/10823K, paused 2ms+2ms
11-26 13:05:27.518: D/dalvikvm(12063): GC_CONCURRENT freed 1028K, 13% free 9675K/11079K, paused 2ms+3ms
11-26 13:05:27.928: D/dalvikvm(12063): GC_CONCURRENT freed 1023K, 13% free 9933K/11335K, paused 1ms+3ms
11-26 13:05:28.278: D/dalvikvm(12063): GC_CONCURRENT freed 1015K, 13% free 10192K/11591K, paused 2ms+3ms
11-26 13:05:28.288: V/RecordedDownloadService(12063): cleanup : enter
11-26 13:05:28.288: V/RecordedDownloadService(12063): cleanup : exit
11-26 13:05:28.288: V/RecordedDownloadService(12063): process : enter
11-26 13:05:28.518: D/dalvikvm(12063): GC_CONCURRENT freed 1345K, 15% free 10062K/11783K, paused 2ms+2ms
11-26 13:05:28.978: D/dalvikvm(12063): GC_CONCURRENT freed 1271K, 15% free 10035K/11783K, paused 1ms+3ms
11-26 13:05:29.378: D/dalvikvm(12063): GC_CONCURRENT freed 1249K, 15% free 10035K/11783K, paused 2ms+2ms
11-26 13:05:29.468: D/RecordedDaoHelper(12063): load : enter
11-26 13:05:29.468: V/ProgramDaoHelper(12063): load : enter
11-26 13:05:29.468: V/ProgramDaoHelper(12063): findAll : enter
11-26 13:05:29.468: V/ProgramDaoHelper(12063): findAll : exit
11-26 13:05:29.528: V/ProgramDaoHelper(12063): load : INSERT channel=#4422, startTime=2011-12-20 07:00 AM
11-26 13:05:29.538: V/ProgramDaoHelper(12063): load : INSERT recording=170, startTime=2011-12-20 07:00 AM
11-26 13:05:29.548: V/ProgramDaoHelper(12063): load : INSERT channel=#4422, startTime=2011-12-24 07:00 AM
11-26 13:05:29.558: V/ProgramDaoHelper(12063): load : INSERT recording=170, startTime=2011-12-24 07:00 AM
11-26 13:05:29.558: V/ProgramDaoHelper(12063): load : INSERT channel=#1046, startTime=2011-12-23 05:59 PM
11-26 13:05:29.568: V/ProgramDaoHelper(12063): load : INSERT recording=714, startTime=2011-12-23 05:59 PM
11-26 13:05:29.578: V/ProgramDaoHelper(12063): load : INSERT channel=#4422, startTime=2011-12-27 05:00 PM
11-26 13:05:29.578: V/ProgramDaoHelper(12063): load : INSERT recording=179, startTime=2011-12-27 05:00 PM
11-26 13:05:29.588: V/ProgramDaoHelper(12063): load : INSERT channel=#4422, startTime=2011-12-27 10:00 PM
11-26 13:05:29.588: V/ProgramDaoHelper(12063): load : INSERT recording=681, startTime=2011-12-27 10:00 PM
11-26 13:05:29.598: V/ProgramDaoHelper(12063): load : INSERT channel=#2361, startTime=2011-10-29 01:00 AM
11-26 13:05:29.608: V/ProgramDaoHelper(12063): load : INSERT recording=651, startTime=2011-10-29 01:00 AM
11-26 13:05:29.608: V/ProgramDaoHelper(12063): load : INSERT channel=#4422, startTime=2012-02-28 07:00 AM

[...]

11-26 13:05:43.478: V/ProgramDaoHelper(12063): load : INSERT recording=783, startTime=2012-11-09 03:02 AM
11-26 13:05:43.488: V/ProgramDaoHelper(12063): load : INSERT channel=3_1, startTime=2012-11-14 03:01 AM
11-26 13:05:43.488: V/ProgramDaoHelper(12063): load : INSERT recording=1025, startTime=2012-11-14 03:01 AM
11-26 13:05:43.498: V/ProgramDaoHelper(12063): load : INSERT channel=1351, startTime=2012-11-13 04:00 PM
11-26 13:05:43.508: V/ProgramDaoHelper(12063): load : INSERT recording=958, startTime=2012-11-13 04:00 PM
11-26 13:05:43.508: V/ProgramDaoHelper(12063): load : INSERT channel=3_1, startTime=2012-11-21 03:02 AM
11-26 13:05:43.518: V/ProgramDaoHelper(12063): load : INSERT recording=1025, startTime=2012-11-21 03:02 AM
11-26 13:05:43.538: V/ProgramDaoHelper(12063): load : INSERT channel=1211, startTime=2012-11-21 10:00 AM
11-26 13:05:43.598: D/dalvikvm(12063): GC_EXPLICIT freed 284K, 6% free 11739K/12487K, paused 2ms+4ms
11-26 13:05:43.608: V/ProgramDaoHelper(12063): load : INSERT recording=996, startTime=2012-11-21 10:00 AM
11-26 13:05:43.618: V/ProgramDaoHelper(12063): load : INSERT channel=11_2, startTime=2012-11-21 04:00 PM
11-26 13:05:43.618: V/ProgramDaoHelper(12063): load : INSERT recording=681, startTime=2012-11-21 04:00 PM
11-26 13:05:43.628: V/ProgramDaoHelper(12063): load : INSERT channel=1327, startTime=2012-11-23 01:00 AM
11-26 13:05:43.628: V/ProgramDaoHelper(12063): load : INSERT recording=42, startTime=2012-11-23 01:00 AM
11-26 13:05:43.638: V/ProgramDaoHelper(12063): load : INSERT channel=1211, startTime=2012-11-22 04:00 AM
11-26 13:05:43.638: V/ProgramDaoHelper(12063): load : INSERT recording=996, startTime=2012-11-22 04:00 AM
11-26 13:05:43.648: V/ProgramDaoHelper(12063): load : INSERT channel=11_2, startTime=2012-11-22 04:00 PM
11-26 13:05:43.658: V/ProgramDaoHelper(12063): load : INSERT recording=681, startTime=2012-11-22 04:00 PM
11-26 13:05:43.718: V/ProgramDaoHelper(12063): load : INSERT channel=11_1, startTime=2012-11-23 02:00 AM
11-26 13:05:43.728: V/ProgramDaoHelper(12063): load : INSERT recording=8, startTime=2012-11-23 02:00 AM
11-26 13:05:43.758: I/dalvikvm(12063): Jit: resizing JitTable from 4096 to 8192
11-26 13:05:43.978: E/JavaBinder(12063): !!! FAILED BINDER TRANSACTION !!!
11-26 13:05:43.978: E/RecordedDownloadService(12063): onHandleIntent : error
11-26 13:05:43.978: E/RecordedDownloadService(12063): android.os.TransactionTooLargeException
11-26 13:05:43.978: E/RecordedDownloadService(12063):   at android.os.BinderProxy.transact(Native Method)
11-26 13:05:43.978: E/RecordedDownloadService(12063):   at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:454)
11-26 13:05:43.978: E/RecordedDownloadService(12063):   at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:120)
11-26 13:05:43.978: E/RecordedDownloadService(12063):   at android.content.ContentResolver.applyBatch(ContentResolver.java:770)
11-26 13:05:43.978: E/RecordedDownloadService(12063):   at org.mythtv.db.dvr.ProgramDaoHelper.load(ProgramDaoHelper.java:313)
11-26 13:05:43.978: E/RecordedDownloadService(12063):   at org.mythtv.db.dvr.RecordedDaoHelper.load(RecordedDaoHelper.java:166)
11-26 13:05:43.978: E/RecordedDownloadService(12063):   at org.mythtv.service.dvr.RecordedDownloadService.process(RecordedDownloadService.java:200)
11-26 13:05:43.978: E/RecordedDownloadService(12063):   at org.mythtv.service.dvr.RecordedDownloadService.download(RecordedDownloadService.java:160)
11-26 13:05:43.978: E/RecordedDownloadService(12063):   at org.mythtv.service.dvr.RecordedDownloadService.onHandleIntent(RecordedDownloadService.java:122)
11-26 13:05:43.978: E/RecordedDownloadService(12063):   at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
11-26 13:05:43.978: E/RecordedDownloadService(12063):   at android.os.Handler.dispatchMessage(Handler.java:99)
11-26 13:05:43.978: E/RecordedDownloadService(12063):   at android.os.Looper.loop(Looper.java:137)
11-26 13:05:43.978: E/RecordedDownloadService(12063):   at android.os.HandlerThread.run(HandlerThread.java:60)
11-26 13:05:43.978: D/RecordedDownloadService(12063): onHandleIntent : exit

**Comment by dmfrey** [comment]
Thank you for the info.  I will add some batching in that call to prevent
this.

**Comment by tekrantz** [comment]
Anytime!

Guess I need to watch some of my recordings!!

Tim

**Comment by billmeek** [comment]
12/18/2012 Note that two users on the mythtv-users mailing list reported their number of
recordings today. One has 2945 and the other 4528.
