### ISSUE TITLE
FATAL EXCEPTION: AsyncTask #3

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#90]
Runnilng: mythtv-android-frontend-1.0.3-50-g52c88cc

To duplicate:

```
With the application and all data removed, installed the above release.
Waited until the Guide download was complete
Pressed Recordings
Pressed the 1st three banners (A-OK so far)
Pressed the next banner (CSI: Crime Scene Investigation)
Exception fires
```

Stop app, clear cache, clear data and removed all sdcard directories except
the "programGuide". Same exception.

LogCat error starts at line 4144 in http://paste.ubuntu.com/1425595/
This log has the entire session from startup to the error.

**Comment by dmfrey** [comment]
Bill,

Did your network connection go away?

What does this url produce if you plug it into a browser?

http://192.168.10.204:6544/Content/GetRecordingArtwork?Inetref=72546&Type=Coverart

Dan

On Tue, Dec 11, 2012 at 12:52 PM, billmeek notifications@github.com wrote:

> Runnilng: mythtv-android-frontend-1.0.3-50-g52c88cc
> 
> To duplicate:
> 
> With the application and all data removed, installed the above release.
> Waited until the Guide download was complete
> Pressed Recordings
> Pressed the 1st three banners (A-OK so far)
> Pressed the next banner (CSI: Crime Scene Investigation)
> Exception fires
> 
> Stop app, clear cache, clear data and removed all sdcard directories except
> the "programGuide". Same exception.
> 
> LogCat error starts at line 4144 in http://paste.ubuntu.com/1425595/
> This log has the entire session from startup to the error.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/90.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
I don't see any messages for my NIC going up or down in /var/log/syslog.

The URL displays the coverart for CSI: Crime Scene Investigation. In the 
backend log, I see this:

<pre>
2012-12-11 10:29:50.637845 I [3331/4388] HttpServer77 httprequest.cpp:1339 (ExtractMethodFromURL) - ExtractMethodFromURL(end) : GetRecordingArtwork : /Content
2012-12-11 10:29:50.637868 I [3331/4388] HttpServer77 servicehost.cpp:281 (ProcessRequest) - ServiceHost::ProcessRequest: GetRecordingArtwork : GET /Content/GetRecordingArtwork?Inetref=72546&Type=Banner HTTP/1.1^M
2012-12-11 10:29:50.639228 I [3331/4388] HttpServer77 httprequest.cpp:230 (SendResponse) - HTTPRequest::SendResponse( File ) :200 OK -> 192.168.10.139:
2012-12-11 10:29:50.639239 I [3331/4388] HttpServer77 httprequest.cpp:339 (SendResponseFile) - SendResponseFile ( /var/lib/mythtv/banners/CSI: Crime Scene Investigation Season 13_banner.jpg )
2012-12-11 10:29:50.639288 I [3331/4388] HttpServer77 httprequest.cpp:892 (TestMimeType) - HTTPRequest::TestMimeType(/var/lib/mythtv/banners/CSI: Crime Scene Investigation Season 13_banner.jpg) - type is image/jpeg
2012-12-11 10:29:50.805959 I [3331/4388] HttpServer77 httprequest.cpp:575 (SendFile) - SendResponseFile : --- size = 0, offset = 620482, sent = 620482
</pre>

**Comment by dmfrey** [comment]
@billmeek did you try the url from my previous post in the browser? did it display the picture in the browser window?

**Comment by billmeek** [comment]
Yes it did. I've been replying using the github issue list rather than email. Not sure you're
seeing everything.

**Comment by dmfrey** [comment]
can you download that coverart image file locally?  Are there any issues with the file itself?  It really sounds to me like the network went away while in the process of downloading.  Can you try the same action again in an emulator so that it doesn't adversely affect your tablet?

**Comment by billmeek** [comment]
I just retried the link you suggested and saved the image. Then I opened it, the file looks OK.

Then I threw fate to the wind and looked at it on the tablet. Both the banner and the coverart
appear fine. I didn't remove the app 1st nor did I delete any files on the sdcard. That may be
important.

Here's a fresh LogCat if you like. Lines 2357, for CSI and 2593 for Undercover Boss seem to
have the same error.  The inetrefs for those two shows are 72546 and 100061 respectively.

You may be on to something with the network.Filtering only for Wifi messages in LogCat, I
see: http://paste.ubuntu.com/1426811/ and in my /var/log/syslog, there are firewall messages
blocking messages between the backend and the tablet. The thing is, all the data is there.

I'll fire up a protocol analyzer and try to see _what_ messages are getting blocked.

**Comment by billmeek** [comment]
No lockups today, but I did capture the protocol as promised. I believe that when
my firewall software is on (ufw in Ubuntu,) incorrect FIN/ACK messages are being
blocked. Incorrect because they appear to be from conversations other than the 
one that is currently ending.

It almost looks like the FIN/ACK messages are being sent to a 'stale' conversation.

With the firewall deactivated, the backend host replies with a RST message. I
believe another indication that the FIN/ACK being send by the tablet is wrong.

I have the raw pcap data from Wireshark and would be happy to supply it in
any format desired.

These two sessions were captured when the Recordings screen was refreshing,
I've annotated them as best I can.

http://paste.ubuntu.com/1428677/  is captured with the firewall deactivated
http://paste.ubuntu.com/1428678/  with the firewall on.

**Comment by dmfrey** [comment]
I did see an app the other day that captured pcap files from android. Will
try to find it and post it later. May be a good tool to have for cases like
this.

**Comment by billmeek** [comment]
I tried "Shark for Root", and as its name implies, it needs a rooted device - mine isn't
Also, "tPacketCapture" which doesn't require being rooted. But it comes up with a
big warning about trusting a VPN. I assume it uses a VPM to bypass the need for
rooting. I was concerned enough about the warning that I removed that app too.

There's also of the capture software slowing down a  VOIP application. That's probably
more data intensive than this app.

I just loaded tshark on my backends. That allows a command line capture session to
be started (no GUI.) The output can be sent to a file in raw pcap format. In my case,
I scp that file to my office computer and run Wireshark on it there.

Here's a nice state table for TCP:

http://upload.wikimedia.org/wikipedia/commons/a/a2/Tcp_state_diagram_fixed.svg

**Comment by billmeek** [comment]
Update running on: mythtv-android-frontend-1.0.3-57-g8938730.

This remains an issue for the new user (e.g. one who has never downloaded
anything.) The text in the initial "To duplicate:" section is correct.

So far, once I've clicked on every show's banner/title, the fatal exception
doesn't repeat.

A fresh LogCat is here: http://paste.ubuntu.com/1460300/ and the exception
fires at line: 3944. 

I also add that when I do this test. I press each banner/text as quickly as I can.

You'll note a number of Uncaught exceptions in the above. There's one just
ahead of the fatal exception on 3921. If you'd like a new issue on this, just
say the word.

**Comment by billmeek** [comment]
This was failing when I tested this morning, but after applying 33f9c62,
I can't get it to fail. Closing this for now.

**Comment by billmeek** [comment]
While testing the 2nd failure mentioned in #73, this was seen. Both in the
Play Store 1.0.4 version and in mythtv-android-frontend-1.0.4-40-g716f6d0.

LocCat is here: http://paste.ubuntu.com/1574413/ and the failure is on line
3972.

One thing of note, unlike my system, @jmturner has no artwork.

I'm not able to duplicate this with my data. Not with 1.0.4 or development.
