### ISSUE TITLE
NPE in ImageCache.java 423

### ISSUE THREAD

**Issue by bhamail** [MythTV-Clients/MythTV-Android-Frontend#92]
Apologies if this is not the right place to report this.

I just cloned the master branch, and I'm running the app in eclipse by launching org.mythtv.client.MainApplication.java.

The app loads in the android simulator nicely, and I was able to scan for a "home" profile just fine. (It found my mythtv backend - way cool!).

The problem is when I open the "home" profile, and then try to open "Recordings", the app crashes with a NullPointerException in org.mythtv.service.util.image.ImageCache.getDiskCacheDir() (line 423).

I'm new to eclipse and android dev, so it is very probable I'm doing something stupid. Any ideas?

Thanks,
Dan

**Comment by bhamail** [comment]
More info: I tried to find the NPE cause, and I think it is in ImageCache.getExternalCacheDir() (line 493).

This bit:

```
public static File getExternalCacheDir(Context context) {
    if (Utils.hasFroyo()) {
        return context.getExternalCacheDir();
    }
```

Utils.hasFroyo() returns true, but the resulting: context.getExternalCacheDir() returns null.

Does that help at all?

**Comment by bhamail** [comment]
So I added the "fix" below, but it is pretty awful, and I'm guessing there is a better solution:

```
diff --git a/src/org/mythtv/service/util/image/ImageCache.java b/src/org/mythtv/service/util/image/ImageCache.java
index e91adaf..8fb16ac 100644
--- a/src/org/mythtv/service/util/image/ImageCache.java
+++ b/src/org/mythtv/service/util/image/ImageCache.java
@@ -419,8 +419,9 @@ public class ImageCache {
         // Check if media is mounted or storage is built-in, if so, try and use external cache dir
         // otherwise use internal cache dir
         final String cachePath =
-                Environment.MEDIA_MOUNTED.equals(Environment.getExternalStorageState()) ||
-                        !isExternalStorageRemovable() ? getExternalCacheDir(context).getPath() :
+                (Environment.MEDIA_MOUNTED.equals(Environment.getExternalStorageState()) ||
+                        !isExternalStorageRemovable()) && (getExternalCacheDir(context) != null)
+                               ? getExternalCacheDir(context).getPath() :
                                 context.getCacheDir().getPath();

         return new File(cachePath + File.separator + uniqueName);
```

**Comment by bhamail** [comment]
Found another NPE, this time in "Guide". (Also not sure this is a valid fix).

```
diff --git a/src/org/mythtv/service/guide/cache/ProgramGuideLruMemoryCache.java     b/src/org/mythtv/service/guide/cache/ProgramGuideLruMemoryCache.j
index d00e1d8..bec939c 100644
--- a/src/org/mythtv/service/guide/cache/ProgramGuideLruMemoryCache.java
+++ b/src/org/mythtv/service/guide/cache/ProgramGuideLruMemoryCache.java
@@ -78,7 +78,7 @@ public class ProgramGuideLruMemoryCache extends LruCache<DateTime, ProgramGuide>
                Log.v( TAG, "create : enter" );

                File programGuideCache = mFileHelper.getProgramGuideDataDirectory();
-               if( programGuideCache.exists() ) {
+               if( programGuideCache != null && programGuideCache.exists() ) {

                        String sStart = DateUtils.fileDateTimeFormatter.print( key );
                        String filename = sStart + MythtvService.FILENAME_EXT;
```

**Comment by bhamail** [comment]
FWIW, the above NPE fixes prevent the app from crashing, but the resulting "Recordings" and "Guide" screens are empty. Both execution paths show a log message: Unable to create external cache directory.

**Comment by pot8oe** [comment]
Hi Dan, Thanks for the debug info. We download data from the backend and
store it json files. Looks like we're failing to get the external storage
dir. What version of android is your device? Does your device support and
have an sdcard installed?

-Tom

**Comment by dmfrey** [comment]
Thanks for the info Dan.

Will take a look.

Is it the context that is null?

Also, the correct way to launch the emulator is too right-click the root of
the app and select Run As -» Android Application.  Never launched it before
like running regular java application, but I assume it's the same.

For your emulator, did you provide a sd card in the settings and give it at
least 512 Mb?

Thanks again,

Dan

**Comment by bhamail** [comment]
Hi Dan,

In ImageCache.java: The returned value of "getExternalCacheDir(context)" was null. This caused the NPE when executing: getExternalCacheDir(context).getPath().

In ProgramGuideLruMemoryCache.java: mFileHelper.getProgramGuideDataDirectory() returned null. This caused NPE when calling: programGuideCache.exists().

Also, No, my emulator does not have a sdcard. Did I miss that in the setup docs (and/or does it need to be doc'd)?
Maybe the app could show a warning message (or throw a specific exception) if a sdcard is required but is missing? 

I added a 512mb card to the emulator, reverted my NPE kludge arounds, and the recorded program list and guide now display fine. Though, ideally, the app should be able to work without a card, yes?.

I would like to help make this app work on the Android GoogleTV devices (eg: sony, vizio), and I don't think those would have an SD card.

Thanks for the pointer on launching as Android App. Any and all additional help is much appreciated!

I would also like to try running some unit tests via the maven command line. Any suggestions in that area?

Two more questions, if I may: 
1. When I try to play a recorded program, after the Please wait...Retrieving video... dialog, I get "Sorry this video can not be played". I'm guessing this is because there is no "player" helper app on my emulator? If so, is there a way to specify one?
2. I apologize for this thread wandering all over. Is there a user and/or dev list that I should post to instead of the Issues list?

Thanks,
-dr

**Comment by dmfrey** [comment]
Dan,

On a physical device, nowadays, the sdcards are always present and usually
not removable.  I setting up the sd card was an over site.  It should be
documented.

For gtv, a native app is currently under development by one of our team.
 We cannot say a whole lot about it yet, but it is coming :)  Ping
@tafypzhttps://github.com/tafypz on
github if you want to help out.

I am not sure maven will be able to be used to run unit tests at this time.
 I am pretty sure you will need to create a separate Androdi Test Project
in eclipse and tie it to the actual App project.  I have been looking into
finding a way to do this all within the same project but have come up
short.  I would love to have unified test project much like we do for the
services api implementation.  If you come up with a way to do this, please
let us know.
1. The emulator will not be able to play the HLS Stream do to a lack of
   codec support in the emulator.  All video testing will have to occur on a
   physical device.  However, all other aspects of the app can be tested in
   the emulator.
2. You can post to the mythtv-users mailing list.  We don't one setup
   specifically here.  I think we can manage the labels on issues in github.
   Maybe we can make up a label named "Discussion" for non-issues, but
   discussions about topics. @billmeek https://github.com/billmeek, do you
   think that is possible?

On Sun, Dec 16, 2012 at 5:05 PM, Dan Rollo notifications@github.com wrote:

> Hi Dan,
> 
> No, my emulator does not have a sdcard. Did I miss that in the setup docs
> (and/or does it need to be doc'd)?
> Maybe the app could show a warning message (or throw a specific exception)
> if a sdcard is required but is missing?
> 
> I added a 512mb card to the emulator, reverted my NPE kludge arounds, and
> the recorded program list and guide now display fine. Though, ideally, the
> app should be able to work without a card, yes?.
> 
> I would like to help make this app work on the Android GoogleTV devices
> (eg: sony, vizio), and I don't think those would have an SD card.
> 
> Thanks for the pointer on launching as Android App. Any and all additional
> help is much appreciated!
> 
> I would also like to try running some unit tests via the maven command
> line. Any suggestions in that area?
> 
> Two more questions, if I may:
> 1. When I try to play a recorded program, the Please wait...Retrieving
> video... dialog never goes away. I'm guessing this is because there is no
> "player" helper app on my emulator? If so, is there way to specify one?
> 1. I apologize for this thread wandering all over. Is there a user
>    and/or dev list that I should post to instead of the Issues list?
> 
> Thanks,
> -dr
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/92#issuecomment-11423648.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by dmfrey** [comment]
Regarding the ImageCache... we should probably never make a network call if
no media is mounted.  We rely on being able to download the files (images,
json, etc.) in order to make the app work.  I guess that is a bug.
 However, if you have no external cache to write to, then I am not sure how
you would be able to use the app. We should have that check in there if,
for example, you hook your phone up to a laptop as an external drive so
that you can transfer files too and from it.  In this case, the sd card
becomes unavailable to the phone/tablet and gets mounted on the host
system.  This should be documented and marked as an issue.

On Sun, Dec 16, 2012 at 9:32 PM, Daniel Frey dmfrey@gmail.com wrote:

> Dan,
> 
> On a physical device, nowadays, the sdcards are always present and usually
> not removable.  I setting up the sd card was an over site.  It should be
> documented.
> 
> For gtv, a native app is currently under development by one of our team.
>  We cannot say a whole lot about it yet, but it is coming :)  Ping @tafypzhttps://github.com/tafypz on
> github if you want to help out.
> 
> I am not sure maven will be able to be used to run unit tests at this
> time.  I am pretty sure you will need to create a separate Androdi Test
> Project in eclipse and tie it to the actual App project.  I have been
> looking into finding a way to do this all within the same project but have
> come up short.  I would love to have unified test project much like we do
> for the services api implementation.  If you come up with a way to do this,
> please let us know.
> 1. The emulator will not be able to play the HLS Stream do to a lack of
>    codec support in the emulator.  All video testing will have to occur on a
>    physical device.  However, all other aspects of the app can be tested in
>    the emulator.
> 2. You can post to the mythtv-users mailing list.  We don't one setup
>    specifically here.  I think we can manage the labels on issues in github.
>    Maybe we can make up a label named "Discussion" for non-issues, but
>    discussions about topics. @billmeek https://github.com/billmeek, do you
>    think that is possible?
> 
> On Sun, Dec 16, 2012 at 5:05 PM, Dan Rollo notifications@github.comwrote:
> 
> > Hi Dan,
> > 
> > No, my emulator does not have a sdcard. Did I miss that in the setup docs
> > (and/or does it need to be doc'd)?
> > Maybe the app could show a warning message (or throw a specific
> > exception) if a sdcard is required but is missing?
> > 
> > I added a 512mb card to the emulator, reverted my NPE kludge arounds, and
> > the recorded program list and guide now display fine. Though, ideally, the
> > app should be able to work without a card, yes?.
> > 
> > I would like to help make this app work on the Android GoogleTV devices
> > (eg: sony, vizio), and I don't think those would have an SD card.
> > 
> > Thanks for the pointer on launching as Android App. Any and all
> > additional help is much appreciated!
> > 
> > I would also like to try running some unit tests via the maven command
> > line. Any suggestions in that area?
> > 
> > Two more questions, if I may:
> > 1. When I try to play a recorded program, the Please wait...Retrieving
> > video... dialog never goes away. I'm guessing this is because there is no
> > "player" helper app on my emulator? If so, is there way to specify one?
> > 1. I apologize for this thread wandering all over. Is there a user
> >    and/or dev list that I should post to instead of the Issues list?
> > 
> > Thanks,
> > -dr
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/92#issuecomment-11423648.
> 
> ## 
> 
> My Google Profile http://www.google.com/profiles/dmfrey

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
@dmfrey discussion label added. I'm not sure what this issue is, bug/enhancement/discussion, all 3?

**Comment by dmfrey** [comment]
I would say for right now, this is just a discussion as it led to the
needing to specify a SD card in the emulator.  But an issue needs to be
created for when the sd card gets unmounted.  I am hoping we can use some
of dan's code to head this issue off from ever occurring on a device.

On Sun, Dec 16, 2012 at 9:43 PM, billmeek notifications@github.com wrote:

> @dmfrey https://github.com/dmfrey discussion label added. I'm not sure
> what this issue is, bug/enhancement/discussion, all 3?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/92#issuecomment-11428820.

## 

My Google Profile http://www.google.com/profiles/dmfrey
