### ISSUE TITLE
Importing the project into eclipse

### ISSUE THREAD

**Issue by frank16** [MythTV-Clients/MythTV-Android-Frontend#97]
I'm trying to build the latest version myself because 1.0.3 app gives me an empty recordings screen and the problem seems to be solved, but the updated app is not yet in google play

I'm a bit of a noob, but I have worked with both eclipse and ADT/NDT in the past, just not in combination.
I managed to install eclipse on mythbuntu (seemed appropriate ;-) from the software center.
I then installed the egit and adt/ndt plugins. Configured adt for the proper android api (1.6 and 1.7)
The got the project from git from within eclipse as per instructions on the wiki
Did a checkout on the frontend-1.0.3 version.
So far, so good.

Then I tried to import it as an android project into my workspace. 
My problem is that eclipse does not recognize the project as an android project on import 'no projects found' when I right click on the git working directory and do 'import existing project'. 
I have tried many ways, from git perspective, from java perspective. I've even imported as a general project, then changed the nature of the .project file to an android project. This last try seemed to do something but got me so many errors I shied away from it.
So, nothing works...

Driving me up the walls this :-(

Could I get a hand with this last step please?
Thanks,
Frank

**Comment by dmfrey** [comment]
I really need to update those instructions for setting up the development
environment on the wiki. As of android sdk 21, they now include a fully
configured eclipse environment.

Also, you will want to import it as an existing maven project.

Let me keep how that goes and, in the meantime, I will try to get the wiki
updated. It will probably be after Christmas, however.

Dan

**Comment by dmfrey** [comment]
@billmeek do we have a label for 'Request' or 'Help' or something similar?
This is really not an Issue but, but more a request or request for help.

@frank16 this message is really more for our internal tagging in the github
issues tracker. Nothing wrong with your question.

**Comment by billmeek** [comment]
@dmfrey, I'll reply off list.

**Comment by frank16** [comment]
Installing the Moron-Aid-Virtue-ENabler plugin in eclipse did it...
Maven took it from there. I am now on the latest from master. Finally the recordings are there!
(but, in all honesty, I haven't got a clue what I have done, which bothers me a bit)

Many thanks, 
have a great holiday!

**Comment by billmeek** [comment]
Updated Wiki: https://github.com/MythTV-Clients/MythTV-Android-Frontend/wiki/Development-Environment-Setup

Closing issue.

**Comment by dmfrey** [comment]
These are great. Thanks for finishing that up. Been on my list for quite
some time and long overdue.
