### ISSUE TITLE
Upcoming recordings that start at midnight display on the previous day's screen

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#98]
If a show starts a 0600Z (and I'm in UTC-6 land) then the show
is displayed on the Upcoming recordings screen for the previous
day.

  http://paste.ubuntu.com/1461150/ = LogCat after pressing Upcoming
  http://paste.ubuntu.com/1461159/  = http://mc0:6544/Dvr/GetUpcomingList?ShowAll=false 

I had to replace all of the <'s in the xml with LessThanSign- in order for the pastebin
to accept it.

In the above, the 1st show (Castle) starts on 12/24 at Midnight or 0600
UTC, but appears with the correct starttime (0000) on the 'Today' screen
(12/23.)

I edited out the remaining shows. This was the 1st show in the
response from the backend.

**Comment by dmfrey** [comment]
Program Guide is going to be refactored to use the Content provider.  Keep this open, but the current implementation will go away.
