### ISSUE TITLE
Retrieving master backend hangs

### ISSUE THREAD

**Issue by netmindz** [MythTV-Clients/MythTV-Android-Frontend#99]
If I try and add a new away profile when away home home the app gets stuck at retrieving the master back end details. If I try the URL I am entering into the browser, the web services site opens fine

**Comment by netmindz** [comment]
P.s same behavior on jelly bean and ice cream sandwich devices

**Comment by netmindz** [comment]
Found the issue. The app adds the default port to the URL if none is defined rather than using the http default. Regardless of this, the app shouldn't just ”spin forever ”, there should be an appropriate timeout and error displayed to user ”connection timeout" or "connection refused"

**Comment by dmfrey** [comment]
Are you port forwarding your mythtv backend port (default: 6544) to port 80 or 8080 or something like that?  We default to 6544 since most people will not change the default port.  Can you tell me what your public settings are?  Feel free to mask your server name.

**Comment by billmeek** [comment]
No response after a month, but I can duplicate the condition.

To Duplicate:

<pre>
Add a new Home/Away profile
Enter an invalid IPv4 address and or port
Press Save
</pre>

The following will pop up:

<pre>
Please wait...
Retrieving Master Backend Details
</pre>

The above never times out and the Task Manager must be used
to stop the application.

LogCat here: http://paste.ubuntu.com/1614734/ note that on line 92 I
entered a valid IPv4 address and an invalid port number 6666 to allow
me to capture protocol on the host.

Protocol here: http://paste.ubuntu.com/1614735/ note on line 20 the host
has sent a RST.

Changing the label to: bug.

**Comment by dmfrey** [comment]
fixed with commit 64a418d

closed with issue #104
